<#
    Tidings task runner — TODO 1.4.

    This is `make.ps1` and not a `Makefile` for one reason: **there is no `make` on
    this box.** Verified 2026-07-26 (`command -v make` → missing), and per the
    Windows-native testing rule there is no WSL or Docker in the loop to borrow one
    from. Shipping a Makefile nobody here can run, plus a script everyone actually
    runs, is two build systems where one of them is a lie.

    The verb set is exactly the one TODO 1.4 specifies, so the names stay portable
    if a Makefile ever becomes worth having:

        gen build test wasm run lint migrate

    plus `tools` (build gwc.exe), `dev` (build + serve, the loop Cam watches) and
    `clean`.

    Usage:  ./make.ps1 <verb> [-Port 9000]
#>

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('gen', 'build', 'test', 'wasm', 'run', 'dev', 'e2e', 'lint', 'migrate', 'tools', 'clean', 'help')]
    [string]$Target = 'help',

    # 9000 is the port Cam watches to follow along; changing the default moves the
    # thing he has open in a tab.
    [int]$Port = 9000
)

$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

$GWC       = Join-Path $PSScriptRoot 'bin\gwc.exe'
$GWCSource = Join-Path (Split-Path $PSScriptRoot -Parent) 'GoWebComponents'
$ClientApp = Join-Path $PSScriptRoot 'client\app'
$WebSrc    = Join-Path $PSScriptRoot 'web'
$OutDir    = Join-Path $PSScriptRoot 'bin\web'
$WasmOut   = Join-Path $OutDir 'app.wasm'

function Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Fail($msg) { Write-Host "!!! $msg" -ForegroundColor Red; exit 1 }

# Native commands set $LASTEXITCODE; PowerShell will not stop on it by itself.
function Invoke-Checked {
    param([string]$What, [scriptblock]$Body)
    & $Body
    if ($LASTEXITCODE -ne 0) { Fail "$What failed (exit $LASTEXITCODE)" }
}

function Ensure-Tools {
    if (-not (Test-Path $GWC)) {
        Step 'gwc.exe missing — building it from the GWC checkout'
        Invoke-Tools
    }
}

function Invoke-Tools {
    Step "building gwc.exe from $GWCSource"
    if (-not (Test-Path $GWCSource)) {
        Fail "GWC checkout not found at $GWCSource. D0: v5.0.0 was never tagged, so the sibling checkout is not optional."
    }
    Push-Location $GWCSource
    try { Invoke-Checked 'go build (gwc)' { go build -o $GWC ./tools/gwc } }
    finally { Pop-Location }
    Write-Host "    $GWC" -ForegroundColor DarkGray
}

function Invoke-Gen {
    Step 'buf generate'
    Invoke-Checked 'buf lint'     { buf lint }
    Invoke-Checked 'buf generate' { buf generate }
}

function Invoke-Build {
    Step 'go build ./...'
    Invoke-Checked 'go build' { go build -o bin\tidings.exe ./cmd/tidings }
    Invoke-Checked 'go vet'   { go build ./... }
}

function Invoke-Test {
    Step 'go test ./...'
    Invoke-Checked 'go test' { go test ./... }
}

function Invoke-Wasm {
    Ensure-Tools
    if (-not (Test-Path $ClientApp)) {
        Write-Host '    client/app has no main yet (Tier 8) — skipping wasm' -ForegroundColor DarkGray
        return
    }
    Step 'building the web root -> bin/web'
    New-Item -ItemType Directory -Force $OutDir | Out-Null

    # web/ is source; bin/web is the assembled output. Copying rather than
    # serving from web/ keeps every generated byte inside the one ignored
    # directory, so "is this file source?" is answerable from its path.
    Copy-Item (Join-Path $WebSrc 'index.html') (Join-Path $OutDir 'index.html') -Force

    # `go build` directly rather than `gwc build`: the launcher wraps the same
    # toolchain, and this keeps the exact flags visible — -trimpath and -s -w are
    # what the G5 baseline in wasm-baseline.txt was measured with, so building
    # differently would make the CI ratchet compare two different things.
    $env:GOOS = 'js'; $env:GOARCH = 'wasm'
    try {
        Invoke-Checked 'go build (wasm)' {
            go build -trimpath -ldflags="-s -w" -o $WasmOut ./client/app
        }
    } finally { Remove-Item Env:GOOS, Env:GOARCH -ErrorAction SilentlyContinue }

    # wasm_exec.js comes from the toolchain, so it must match the compiler that
    # produced the module. A stale copy from an older Go fails at instantiate
    # with an import mismatch that reads like a corrupt binary.
    $exec = Join-Path (go env GOROOT) 'lib\wasm\wasm_exec.js'
    if (-not (Test-Path $exec)) { $exec = Join-Path (go env GOROOT) 'misc\wasm\wasm_exec.js' }
    Copy-Item $exec (Join-Path $OutDir 'wasm_exec.js') -Force

    # Precompressed siblings. G5 measured 23.8 MB raw against 5.2 MB gzipped;
    # the server prefers the .gz when the client accepts it.
    #
    # Written to a temp file and MOVED into place, never compressed in situ. The
    # server prefers app.wasm.gz over app.wasm, so a .gz that is stale — or
    # truncated, which is what File::Create leaves behind when the compressor
    # throws — means the browser silently runs the previous build. That failure
    # looks exactly like "my change did nothing", and it costs an hour every time.
    #
    # CompressionLevel::Optimal, not SmallestSize: SmallestSize is .NET 5+, and on
    # Windows PowerShell 5.1 it resolves to $null, which surfaces as an
    # unrelated-looking "cannot find an overload for GZipStream".
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    foreach ($f in @($WasmOut, (Join-Path $OutDir 'wasm_exec.js'))) {
        $tmp = "$f.gz.tmp"
        $in  = [System.IO.File]::OpenRead($f)
        $out = [System.IO.File]::Create($tmp)
        $gz  = New-Object System.IO.Compression.GZipStream($out, [System.IO.Compression.CompressionLevel]::Optimal)
        try { $in.CopyTo($gz) } finally { $gz.Dispose(); $out.Dispose(); $in.Dispose() }
        Move-Item $tmp "$f.gz" -Force
    }

    # G5 / R4: the wasm size decides whether A5 (offline packs in the browser)
    # stays affordable. Print it every build so the number is never a surprise.
    $raw = [math]::Round((Get-Item $WasmOut).Length / 1MB, 1)
    $gzs = [math]::Round((Get-Item "$WasmOut.gz").Length / 1MB, 1)
    Write-Host "    app.wasm = $raw MB raw / $gzs MB gzipped  (G5 ratchet - plan.md R4)" -ForegroundColor DarkGray
}

function Invoke-Lint {
    Step 'go vet'
    Invoke-Checked 'go vet' { go vet ./... }
    Step 'buf lint'
    Invoke-Checked 'buf lint' { buf lint }
    Step 'structural guards (A26 + tenancy)'
    Invoke-Checked 'guards' { go run ./internal/tools/guards }
}

function Invoke-Migrate {
    Ensure-Build
    Step 'tidings migrate'
    Invoke-Checked 'migrate' { & (Join-Path $PSScriptRoot 'bin\tidings.exe') migrate }
}

function Ensure-Build { if (-not (Test-Path 'bin\tidings.exe')) { Invoke-Build } }

function Invoke-Run {
    Invoke-Build
    Step "serving on http://127.0.0.1:$Port"
    & (Join-Path $PSScriptRoot 'bin\tidings.exe') serve -addr "127.0.0.1:$Port"
}

switch ($Target) {
    'tools'   { Invoke-Tools }
    'gen'     { Invoke-Gen }
    'build'   { Invoke-Build }
    'test'    { Invoke-Test }
    'wasm'    { Invoke-Wasm }
    'lint'    { Invoke-Lint }
    'migrate' { Invoke-Migrate }
    'run'     { Invoke-Run }
    'dev'     { Invoke-Wasm; Invoke-Run }
    'e2e'     {
        Invoke-Build
        Invoke-Wasm
        Step 'playwright'
        Push-Location (Join-Path $PSScriptRoot 'e2e')
        try {
            if (-not (Test-Path 'node_modules')) { Invoke-Checked 'npm install' { npm install } }
            Invoke-Checked 'playwright' { npx playwright test }
        } finally { Pop-Location }
    }
    'clean'   {
        Step 'clean'
        # One directory, because everything generated lives in it.
        if (Test-Path 'bin') { Remove-Item -Recurse -Force 'bin' }
    }
    default {
        Write-Host @'
Tidings task runner (TODO 1.4)

  ./make.ps1 tools      build gwc.exe from ../GoWebComponents  (D0: no published tag)
  ./make.ps1 gen        buf lint + buf generate -> internal/pb
  ./make.ps1 build      go build -> bin/tidings.exe
  ./make.ps1 test       go test ./...
  ./make.ps1 wasm       build the client into bin/web, prints the G5 size
  ./make.ps1 lint       go vet + buf lint + the A26/tenancy structural guards
  ./make.ps1 migrate    apply migrations
  ./make.ps1 run        build, then serve on :9000
  ./make.ps1 dev        wasm + run          <- the loop to leave open
  ./make.ps1 e2e        build, then run the Playwright suite (desktop + phone)
  ./make.ps1 clean      remove bin/ (which is all generated output)

Override the port with -Port; 9000 is the default because that is the tab Cam
has open.
'@
    }
}
