// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: articleflux/v1/auth.proto

package articlefluxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedeemRecoveryCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username names the account. Recovery is by definition attempted by somebody
	// who cannot present a session, so there is no other way to say whose account
	// this is.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// code is one entry from the printed sheet. Case, dashes and spaces are all
	// normalised away server-side (authn.NormalizeRecoveryCode) — they carry no
	// entropy, and the person typing this is already locked out and already
	// annoyed.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// new_password replaces the forgotten one, checked against the same policy as
	// every other password on the instance.
	NewPassword   string `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemRecoveryCodeRequest) Reset() {
	*x = RedeemRecoveryCodeRequest{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemRecoveryCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemRecoveryCodeRequest) ProtoMessage() {}

func (x *RedeemRecoveryCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemRecoveryCodeRequest.ProtoReflect.Descriptor instead.
func (*RedeemRecoveryCodeRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RedeemRecoveryCodeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RedeemRecoveryCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RedeemRecoveryCodeRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type RedeemRecoveryCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A session, so the reader lands in the app rather than at a login screen
	// typing the password they just set.
	Token     string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt string `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Username  string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Role      string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// codes_remaining is how many entries on the sheet are still unused. The
	// number is the whole signal that it is time to regenerate — "codes are
	// configured" tells nobody anything, and somebody on their last one should be
	// told so on the screen where they just used the second to last.
	CodesRemaining int32 `protobuf:"varint,5,opt,name=codes_remaining,json=codesRemaining,proto3" json:"codes_remaining,omitempty"`
	// sessions_ended counts what this recovery revoked. A person recovering an
	// account often suspects somebody else was in it, and "signed out of 4 other
	// devices" is the confirmation that the thing they were afraid of is over.
	SessionsEnded int32 `protobuf:"varint,6,opt,name=sessions_ended,json=sessionsEnded,proto3" json:"sessions_ended,omitempty"`
	// The refresh half, on exactly the same terms as LoginResponse's (§7.3a
	// SEC4). Empty on an instance that does not issue refresh tokens.
	//
	// Added because the alternative was worse than it looked: once an access
	// token lives twelve hours rather than thirty days, a session minted WITHOUT
	// a way to renew it is one that ends before lunch. Recovery is the rarest
	// path here and it is also the one where being logged out again would be
	// cruellest — somebody has just proved possession of a recovery code and
	// chosen a new password.
	RefreshRecordId string `protobuf:"bytes,7,opt,name=refresh_record_id,json=refreshRecordId,proto3" json:"refresh_record_id,omitempty"`
	RefreshToken    string `protobuf:"bytes,8,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RedeemRecoveryCodeResponse) Reset() {
	*x = RedeemRecoveryCodeResponse{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemRecoveryCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemRecoveryCodeResponse) ProtoMessage() {}

func (x *RedeemRecoveryCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemRecoveryCodeResponse.ProtoReflect.Descriptor instead.
func (*RedeemRecoveryCodeResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RedeemRecoveryCodeResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RedeemRecoveryCodeResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *RedeemRecoveryCodeResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RedeemRecoveryCodeResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RedeemRecoveryCodeResponse) GetCodesRemaining() int32 {
	if x != nil {
		return x.CodesRemaining
	}
	return 0
}

func (x *RedeemRecoveryCodeResponse) GetSessionsEnded() int32 {
	if x != nil {
		return x.SessionsEnded
	}
	return 0
}

func (x *RedeemRecoveryCodeResponse) GetRefreshRecordId() string {
	if x != nil {
		return x.RefreshRecordId
	}
	return ""
}

func (x *RedeemRecoveryCodeResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RedeemResetTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is the value the admin minted and handed over. It names the account
	// by itself — there is no username field, because the token IS the
	// authorisation and asking for a username alongside it would add a field an
	// attacker can vary while proving nothing.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword   string `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"` // No `label`, for the reason given on RedeemRecoveryCodeRequest.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemResetTokenRequest) Reset() {
	*x = RedeemResetTokenRequest{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemResetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemResetTokenRequest) ProtoMessage() {}

func (x *RedeemResetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemResetTokenRequest.ProtoReflect.Descriptor instead.
func (*RedeemResetTokenRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RedeemResetTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RedeemResetTokenRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type RedeemResetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	SessionsEnded int32                  `protobuf:"varint,5,opt,name=sessions_ended,json=sessionsEnded,proto3" json:"sessions_ended,omitempty"`
	// The refresh half — see RedeemRecoveryCodeResponse's note.
	RefreshRecordId string `protobuf:"bytes,6,opt,name=refresh_record_id,json=refreshRecordId,proto3" json:"refresh_record_id,omitempty"`
	RefreshToken    string `protobuf:"bytes,7,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RedeemResetTokenResponse) Reset() {
	*x = RedeemResetTokenResponse{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemResetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemResetTokenResponse) ProtoMessage() {}

func (x *RedeemResetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemResetTokenResponse.ProtoReflect.Descriptor instead.
func (*RedeemResetTokenResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RedeemResetTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RedeemResetTokenResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *RedeemResetTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RedeemResetTokenResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RedeemResetTokenResponse) GetSessionsEnded() int32 {
	if x != nil {
		return x.SessionsEnded
	}
	return 0
}

func (x *RedeemResetTokenResponse) GetRefreshRecordId() string {
	if x != nil {
		return x.RefreshRecordId
	}
	return ""
}

func (x *RedeemResetTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ReauthenticateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// password is the caller's current password. There is no username: the
	// session already says who this is, and accepting one would let a caller
	// re-authenticate as somebody else on a session that is not theirs.
	Password      string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReauthenticateRequest) Reset() {
	*x = ReauthenticateRequest{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReauthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReauthenticateRequest) ProtoMessage() {}

func (x *ReauthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReauthenticateRequest.ProtoReflect.Descriptor instead.
func (*ReauthenticateRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ReauthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ReauthenticateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sudo_expires_at is when the window closes, RFC3339. Returned so the client
	// can hide an action that is about to need the password again rather than
	// offering it and failing — the number is not a secret, and the alternative
	// is a UI that guesses at a constant the server owns.
	SudoExpiresAt string `protobuf:"bytes,1,opt,name=sudo_expires_at,json=sudoExpiresAt,proto3" json:"sudo_expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReauthenticateResponse) Reset() {
	*x = ReauthenticateResponse{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReauthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReauthenticateResponse) ProtoMessage() {}

func (x *ReauthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReauthenticateResponse.ProtoReflect.Descriptor instead.
func (*ReauthenticateResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ReauthenticateResponse) GetSudoExpiresAt() string {
	if x != nil {
		return x.SudoExpiresAt
	}
	return ""
}

type ChangePasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// new_password is checked against the same policy as any other password:
	// length, and the bundled breached-password list with its folding. A password
	// change is the one moment someone is thinking about their password, which
	// makes it the best moment to refuse a bad one.
	NewPassword   string `protobuf:"bytes,1,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sessions_ended counts the OTHER sessions revoked, so the client can say
	// "signed out of 3 other devices" rather than leaving someone to wonder
	// whether the change did anything beyond the password.
	SessionsEnded int32 `protobuf:"varint,1,opt,name=sessions_ended,json=sessionsEnded,proto3" json:"sessions_ended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ChangePasswordResponse) GetSessionsEnded() int32 {
	if x != nil {
		return x.SessionsEnded
	}
	return 0
}

type RegenerateRecoveryCodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateRecoveryCodesRequest) Reset() {
	*x = RegenerateRecoveryCodesRequest{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateRecoveryCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateRecoveryCodesRequest) ProtoMessage() {}

func (x *RegenerateRecoveryCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateRecoveryCodesRequest.ProtoReflect.Descriptor instead.
func (*RegenerateRecoveryCodesRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{8}
}

type RegenerateRecoveryCodesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// codes are plaintext and appear here exactly once.
	Codes         []string `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateRecoveryCodesResponse) Reset() {
	*x = RegenerateRecoveryCodesResponse{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateRecoveryCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateRecoveryCodesResponse) ProtoMessage() {}

func (x *RegenerateRecoveryCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateRecoveryCodesResponse.ProtoReflect.Descriptor instead.
func (*RegenerateRecoveryCodesResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RegenerateRecoveryCodesResponse) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type RefreshSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// refresh_record_id names which device row is refreshing. Server-generated
	// at Login/Setup time (§7.3a SEC1) — never accepted from a client as a
	// primary key, because a client-chosen id that collides with someone else's
	// row is exactly the cross-account session-minting bug this field replaced
	// (`device_id` used to be a client-minted timestamp). The refresh token
	// alone would be enough to find the row, but naming it means a token
	// presented against the wrong record is a mismatch rather than a lookup
	// that happens to succeed.
	RefreshRecordId string `protobuf:"bytes,1,opt,name=refresh_record_id,json=refreshRecordId,proto3" json:"refresh_record_id,omitempty"`
	RefreshToken    string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefreshSessionRequest) Reset() {
	*x = RefreshSessionRequest{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionRequest) ProtoMessage() {}

func (x *RefreshSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshSessionRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshSessionRequest) GetRefreshRecordId() string {
	if x != nil {
		return x.RefreshRecordId
	}
	return ""
}

func (x *RefreshSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A fresh session token, exactly as Login returns.
	Token     string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt string `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// And a fresh REFRESH token. The old one is dead the moment this returns:
	// that is what makes presenting it again evidence of a replay rather than an
	// ordinary retry.
	RefreshToken  string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionResponse) Reset() {
	*x = RefreshSessionResponse{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionResponse) ProtoMessage() {}

func (x *RefreshSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionResponse.ProtoReflect.Descriptor instead.
func (*RefreshSessionResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshSessionResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshSessionResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *RefreshSessionResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Username string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// label is a client-stable browser value ("this laptop"), for PRESENTATION
	// ONLY (§7.3a SEC1). It is never used as a row identifier: the account
	// screen can show it back, and nothing else may depend on it, because a
	// label is a string the caller chose and a security boundary cannot be
	// built on a string the caller chose.
	Label         string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is the bearer credential. Sent on every subsequent RPC as
	// `authorization: Bearer <token>`.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// expires_at is RFC3339. The client uses it to decide when to stop trusting a
	// stored token without a round trip; the server checks it in SQL regardless,
	// because a client-side expiry is a suggestion.
	ExpiresAt string `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Username  string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Role      string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// refresh_record_id is the server-generated, unguessable id (idgen.DeviceID,
	// 128 bits of CSPRNG) of the devices row this login registered. Present it
	// to RefreshSession alongside refresh_token; it is never derived from, or
	// equal to, anything the client sent (§7.3a SEC1).
	RefreshRecordId string `protobuf:"bytes,5,opt,name=refresh_record_id,json=refreshRecordId,proto3" json:"refresh_record_id,omitempty"`
	// refresh_token is the FIRST token of this device's family (§7.3).
	//
	// Handed out at login rather than fetched later, because a client that has to
	// ask for one has a window in which it holds a session it cannot renew — and
	// the whole point of the family is that renewal is the only way a session
	// continues, so reuse is detectable.
	RefreshToken  string `protobuf:"bytes,6,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *LoginResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LoginResponse) GetRefreshRecordId() string {
	if x != nil {
		return x.RefreshRecordId
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{14}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{15}
}

type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{16}
}

type SetupRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Username string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Stored, and honest about what it is for: this instance sends no mail. It
	// identifies the account and it is what a future reset flow would need. The
	// thing that actually recovers an account here is the codes below.
	Email         string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *SetupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SetupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SetupResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Token     string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Username  string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Role      string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// refresh_record_id — see LoginResponse.refresh_record_id.
	RefreshRecordId string `protobuf:"bytes,5,opt,name=refresh_record_id,json=refreshRecordId,proto3" json:"refresh_record_id,omitempty"`
	RefreshToken    string `protobuf:"bytes,6,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Shown once and never again: they are stored hashed, so this response is the
	// only moment they exist in readable form anywhere.
	RecoveryCodes []string `protobuf:"bytes,7,rep,name=recovery_codes,json=recoveryCodes,proto3" json:"recovery_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupResponse) Reset() {
	*x = SetupResponse{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupResponse) ProtoMessage() {}

func (x *SetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupResponse.ProtoReflect.Descriptor instead.
func (*SetupResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *SetupResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SetupResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *SetupResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetupResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SetupResponse) GetRefreshRecordId() string {
	if x != nil {
		return x.RefreshRecordId
	}
	return ""
}

func (x *SetupResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SetupResponse) GetRecoveryCodes() []string {
	if x != nil {
		return x.RecoveryCodes
	}
	return nil
}

type WhoAmIResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Username string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role     string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	TenantId string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// dev_mode reports that the server is serving an unauthenticated local
	// account. Surfaced so the client can say so out loud — an instance that
	// thinks it is a private laptop while facing the internet is exactly the
	// failure this service was added to prevent, and it should be visible rather
	// than inferred.
	DevMode bool `protobuf:"varint,4,opt,name=dev_mode,json=devMode,proto3" json:"dev_mode,omitempty"`
	// needs_setup reports an instance with no accounts at all, so the client shows
	// the setup screen instead of a password prompt nothing can satisfy. Answered
	// to an unauthenticated caller on purpose: it is the one fact a stranger must
	// know before they can become the owner, and it discloses only that the box is
	// unclaimed.
	NeedsSetup    bool `protobuf:"varint,5,opt,name=needs_setup,json=needsSetup,proto3" json:"needs_setup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_articleflux_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *WhoAmIResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WhoAmIResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WhoAmIResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WhoAmIResponse) GetDevMode() bool {
	if x != nil {
		return x.DevMode
	}
	return false
}

func (x *WhoAmIResponse) GetNeedsSetup() bool {
	if x != nil {
		return x.NeedsSetup
	}
	return false
}

var File_articleflux_v1_auth_proto protoreflect.FileDescriptor

const file_articleflux_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x19articleflux/v1/auth.proto\x12\x0earticleflux.v1\"n\n" +
	"\x19RedeemRecoveryCodeRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"\xa2\x02\n" +
	"\x1aRedeemRecoveryCodeResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12'\n" +
	"\x0fcodes_remaining\x18\x05 \x01(\x05R\x0ecodesRemaining\x12%\n" +
	"\x0esessions_ended\x18\x06 \x01(\x05R\rsessionsEnded\x12*\n" +
	"\x11refresh_record_id\x18\a \x01(\tR\x0frefreshRecordId\x12#\n" +
	"\rrefresh_token\x18\b \x01(\tR\frefreshToken\"R\n" +
	"\x17RedeemResetTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\xf7\x01\n" +
	"\x18RedeemResetTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12%\n" +
	"\x0esessions_ended\x18\x05 \x01(\x05R\rsessionsEnded\x12*\n" +
	"\x11refresh_record_id\x18\x06 \x01(\tR\x0frefreshRecordId\x12#\n" +
	"\rrefresh_token\x18\a \x01(\tR\frefreshToken\"3\n" +
	"\x15ReauthenticateRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"@\n" +
	"\x16ReauthenticateResponse\x12&\n" +
	"\x0fsudo_expires_at\x18\x01 \x01(\tR\rsudoExpiresAt\":\n" +
	"\x15ChangePasswordRequest\x12!\n" +
	"\fnew_password\x18\x01 \x01(\tR\vnewPassword\"?\n" +
	"\x16ChangePasswordResponse\x12%\n" +
	"\x0esessions_ended\x18\x01 \x01(\x05R\rsessionsEnded\" \n" +
	"\x1eRegenerateRecoveryCodesRequest\"7\n" +
	"\x1fRegenerateRecoveryCodesResponse\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"h\n" +
	"\x15RefreshSessionRequest\x12*\n" +
	"\x11refresh_record_id\x18\x01 \x01(\tR\x0frefreshRecordId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"r\n" +
	"\x16RefreshSessionResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"\\\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"\xc5\x01\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12*\n" +
	"\x11refresh_record_id\x18\x05 \x01(\tR\x0frefreshRecordId\x12#\n" +
	"\rrefresh_token\x18\x06 \x01(\tR\frefreshToken\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\"\x0f\n" +
	"\rWhoAmIRequest\"\\\n" +
	"\fSetupRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\xec\x01\n" +
	"\rSetupResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12*\n" +
	"\x11refresh_record_id\x18\x05 \x01(\tR\x0frefreshRecordId\x12#\n" +
	"\rrefresh_token\x18\x06 \x01(\tR\frefreshToken\x12%\n" +
	"\x0erecovery_codes\x18\a \x03(\tR\rrecoveryCodes\"\x99\x01\n" +
	"\x0eWhoAmIResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x19\n" +
	"\bdev_mode\x18\x04 \x01(\bR\adevMode\x12\x1f\n" +
	"\vneeds_setup\x18\x05 \x01(\bR\n" +
	"needsSetup2\x9e\a\n" +
	"\vAuthService\x12D\n" +
	"\x05Setup\x12\x1c.articleflux.v1.SetupRequest\x1a\x1d.articleflux.v1.SetupResponse\x12D\n" +
	"\x05Login\x12\x1c.articleflux.v1.LoginRequest\x1a\x1d.articleflux.v1.LoginResponse\x12G\n" +
	"\x06Logout\x12\x1d.articleflux.v1.LogoutRequest\x1a\x1e.articleflux.v1.LogoutResponse\x12G\n" +
	"\x06WhoAmI\x12\x1d.articleflux.v1.WhoAmIRequest\x1a\x1e.articleflux.v1.WhoAmIResponse\x12_\n" +
	"\x0eRefreshSession\x12%.articleflux.v1.RefreshSessionRequest\x1a&.articleflux.v1.RefreshSessionResponse\x12_\n" +
	"\x0eReauthenticate\x12%.articleflux.v1.ReauthenticateRequest\x1a&.articleflux.v1.ReauthenticateResponse\x12_\n" +
	"\x0eChangePassword\x12%.articleflux.v1.ChangePasswordRequest\x1a&.articleflux.v1.ChangePasswordResponse\x12z\n" +
	"\x17RegenerateRecoveryCodes\x12..articleflux.v1.RegenerateRecoveryCodesRequest\x1a/.articleflux.v1.RegenerateRecoveryCodesResponse\x12k\n" +
	"\x12RedeemRecoveryCode\x12).articleflux.v1.RedeemRecoveryCodeRequest\x1a*.articleflux.v1.RedeemRecoveryCodeResponse\x12e\n" +
	"\x10RedeemResetToken\x12'.articleflux.v1.RedeemResetTokenRequest\x1a(.articleflux.v1.RedeemResetTokenResponseBPZNgithub.com/monstercameron/ArticleFlux/internal/pb/articleflux/v1;articlefluxv1b\x06proto3"

var (
	file_articleflux_v1_auth_proto_rawDescOnce sync.Once
	file_articleflux_v1_auth_proto_rawDescData []byte
)

func file_articleflux_v1_auth_proto_rawDescGZIP() []byte {
	file_articleflux_v1_auth_proto_rawDescOnce.Do(func() {
		file_articleflux_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_articleflux_v1_auth_proto_rawDesc), len(file_articleflux_v1_auth_proto_rawDesc)))
	})
	return file_articleflux_v1_auth_proto_rawDescData
}

var file_articleflux_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_articleflux_v1_auth_proto_goTypes = []any{
	(*RedeemRecoveryCodeRequest)(nil),       // 0: articleflux.v1.RedeemRecoveryCodeRequest
	(*RedeemRecoveryCodeResponse)(nil),      // 1: articleflux.v1.RedeemRecoveryCodeResponse
	(*RedeemResetTokenRequest)(nil),         // 2: articleflux.v1.RedeemResetTokenRequest
	(*RedeemResetTokenResponse)(nil),        // 3: articleflux.v1.RedeemResetTokenResponse
	(*ReauthenticateRequest)(nil),           // 4: articleflux.v1.ReauthenticateRequest
	(*ReauthenticateResponse)(nil),          // 5: articleflux.v1.ReauthenticateResponse
	(*ChangePasswordRequest)(nil),           // 6: articleflux.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),          // 7: articleflux.v1.ChangePasswordResponse
	(*RegenerateRecoveryCodesRequest)(nil),  // 8: articleflux.v1.RegenerateRecoveryCodesRequest
	(*RegenerateRecoveryCodesResponse)(nil), // 9: articleflux.v1.RegenerateRecoveryCodesResponse
	(*RefreshSessionRequest)(nil),           // 10: articleflux.v1.RefreshSessionRequest
	(*RefreshSessionResponse)(nil),          // 11: articleflux.v1.RefreshSessionResponse
	(*LoginRequest)(nil),                    // 12: articleflux.v1.LoginRequest
	(*LoginResponse)(nil),                   // 13: articleflux.v1.LoginResponse
	(*LogoutRequest)(nil),                   // 14: articleflux.v1.LogoutRequest
	(*LogoutResponse)(nil),                  // 15: articleflux.v1.LogoutResponse
	(*WhoAmIRequest)(nil),                   // 16: articleflux.v1.WhoAmIRequest
	(*SetupRequest)(nil),                    // 17: articleflux.v1.SetupRequest
	(*SetupResponse)(nil),                   // 18: articleflux.v1.SetupResponse
	(*WhoAmIResponse)(nil),                  // 19: articleflux.v1.WhoAmIResponse
}
var file_articleflux_v1_auth_proto_depIdxs = []int32{
	17, // 0: articleflux.v1.AuthService.Setup:input_type -> articleflux.v1.SetupRequest
	12, // 1: articleflux.v1.AuthService.Login:input_type -> articleflux.v1.LoginRequest
	14, // 2: articleflux.v1.AuthService.Logout:input_type -> articleflux.v1.LogoutRequest
	16, // 3: articleflux.v1.AuthService.WhoAmI:input_type -> articleflux.v1.WhoAmIRequest
	10, // 4: articleflux.v1.AuthService.RefreshSession:input_type -> articleflux.v1.RefreshSessionRequest
	4,  // 5: articleflux.v1.AuthService.Reauthenticate:input_type -> articleflux.v1.ReauthenticateRequest
	6,  // 6: articleflux.v1.AuthService.ChangePassword:input_type -> articleflux.v1.ChangePasswordRequest
	8,  // 7: articleflux.v1.AuthService.RegenerateRecoveryCodes:input_type -> articleflux.v1.RegenerateRecoveryCodesRequest
	0,  // 8: articleflux.v1.AuthService.RedeemRecoveryCode:input_type -> articleflux.v1.RedeemRecoveryCodeRequest
	2,  // 9: articleflux.v1.AuthService.RedeemResetToken:input_type -> articleflux.v1.RedeemResetTokenRequest
	18, // 10: articleflux.v1.AuthService.Setup:output_type -> articleflux.v1.SetupResponse
	13, // 11: articleflux.v1.AuthService.Login:output_type -> articleflux.v1.LoginResponse
	15, // 12: articleflux.v1.AuthService.Logout:output_type -> articleflux.v1.LogoutResponse
	19, // 13: articleflux.v1.AuthService.WhoAmI:output_type -> articleflux.v1.WhoAmIResponse
	11, // 14: articleflux.v1.AuthService.RefreshSession:output_type -> articleflux.v1.RefreshSessionResponse
	5,  // 15: articleflux.v1.AuthService.Reauthenticate:output_type -> articleflux.v1.ReauthenticateResponse
	7,  // 16: articleflux.v1.AuthService.ChangePassword:output_type -> articleflux.v1.ChangePasswordResponse
	9,  // 17: articleflux.v1.AuthService.RegenerateRecoveryCodes:output_type -> articleflux.v1.RegenerateRecoveryCodesResponse
	1,  // 18: articleflux.v1.AuthService.RedeemRecoveryCode:output_type -> articleflux.v1.RedeemRecoveryCodeResponse
	3,  // 19: articleflux.v1.AuthService.RedeemResetToken:output_type -> articleflux.v1.RedeemResetTokenResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_articleflux_v1_auth_proto_init() }
func file_articleflux_v1_auth_proto_init() {
	if File_articleflux_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_articleflux_v1_auth_proto_rawDesc), len(file_articleflux_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_articleflux_v1_auth_proto_goTypes,
		DependencyIndexes: file_articleflux_v1_auth_proto_depIdxs,
		MessageInfos:      file_articleflux_v1_auth_proto_msgTypes,
	}.Build()
	File_articleflux_v1_auth_proto = out.File
	file_articleflux_v1_auth_proto_goTypes = nil
	file_articleflux_v1_auth_proto_depIdxs = nil
}
