// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: articleflux/v1/errors.proto

package articlefluxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorDetail carries a TRANSLATABLE identity for a failure, attached to a gRPC
// status alongside its English message.
//
// The problem it solves: a status message is prose written on the server, and
// the client renders it verbatim — so every refusal the reader sees ("only an
// administrator can change Smart+ settings", "invalid username or password")
// was English no matter what language the interface was in. The server cannot
// translate it either, because the language is a per-device choice held in the
// browser.
//
// So the server sends the KEY and the ARGUMENTS, and the client looks them up
// in the same catalog everything else comes from. The status message stays as
// the English fallback, which matters for the two consumers that have no
// catalog: the Google Reader-compatible sync API (§20.7) and anyone reading the
// error off a curl.
type ErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Catalog key in flat "namespace.key" form — always the "srv" namespace, so
	// one file holds every message the server can send a person.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Placeholder values for the message, already stringified. Server-side
	// identifiers only: never the reader's own content, which does not belong in
	// an error the server composed.
	Args          map[string]string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_articleflux_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ErrorDetail) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_articleflux_v1_errors_proto protoreflect.FileDescriptor

const file_articleflux_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x1barticleflux/v1/errors.proto\x12\x0earticleflux.v1\"\x93\x01\n" +
	"\vErrorDetail\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x04args\x18\x02 \x03(\v2%.articleflux.v1.ErrorDetail.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BPZNgithub.com/monstercameron/ArticleFlux/internal/pb/articleflux/v1;articlefluxv1b\x06proto3"

var (
	file_articleflux_v1_errors_proto_rawDescOnce sync.Once
	file_articleflux_v1_errors_proto_rawDescData []byte
)

func file_articleflux_v1_errors_proto_rawDescGZIP() []byte {
	file_articleflux_v1_errors_proto_rawDescOnce.Do(func() {
		file_articleflux_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_articleflux_v1_errors_proto_rawDesc), len(file_articleflux_v1_errors_proto_rawDesc)))
	})
	return file_articleflux_v1_errors_proto_rawDescData
}

var file_articleflux_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_articleflux_v1_errors_proto_goTypes = []any{
	(*ErrorDetail)(nil), // 0: articleflux.v1.ErrorDetail
	nil,                 // 1: articleflux.v1.ErrorDetail.ArgsEntry
}
var file_articleflux_v1_errors_proto_depIdxs = []int32{
	1, // 0: articleflux.v1.ErrorDetail.args:type_name -> articleflux.v1.ErrorDetail.ArgsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_articleflux_v1_errors_proto_init() }
func file_articleflux_v1_errors_proto_init() {
	if File_articleflux_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_articleflux_v1_errors_proto_rawDesc), len(file_articleflux_v1_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_articleflux_v1_errors_proto_goTypes,
		DependencyIndexes: file_articleflux_v1_errors_proto_depIdxs,
		MessageInfos:      file_articleflux_v1_errors_proto_msgTypes,
	}.Build()
	File_articleflux_v1_errors_proto = out.File
	file_articleflux_v1_errors_proto_goTypes = nil
	file_articleflux_v1_errors_proto_depIdxs = nil
}
