// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: articleflux/v1/events.proto

package articlefluxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventService_WatchEvents_FullMethodName = "/articleflux.v1.EventService/WatchEvents"
)

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventService tells a connected client that something changed (§20.3, TODO 8.7).
//
// Its own service and its own file rather than another method on ReaderService,
// because it is the only STREAMING surface in the API and streams fail
// differently: a unary call that errors is one request, while this one holds a
// goroutine, a subscription and a tunnel stream for as long as the tab is open.
// Keeping it separate means the thing with a different lifetime also has a
// different place to look when it misbehaves.
//
// # What this is not
//
// Not a data channel. Events carry IDS, never rows — an event carrying a full
// item is a second serialisation of the same record that can disagree with the
// query the client makes next, and the client would have two sources of truth
// for one article. The event says "this changed"; the client's existing read
// path says what it now is.
//
// Not a replacement for polling the feeds either. The server polls sources on
// its own schedule; this only reports what that polling FOUND, to a client that
// would otherwise show yesterday's list until somebody pressed something.
type EventServiceClient interface {
	// WatchEvents streams changes for the caller's own scope until the client
	// goes away.
	//
	// `since` resumes: a client that reconnects asks for everything after the
	// last sequence it saw, so a reconnect inside the buffer window costs a
	// catch-up batch rather than a full reload. Zero means "only what happens
	// from now on", which is what a fresh tab wants — replaying a thousand
	// buffered events into a page that is about to fetch the current state anyway
	// is work that ends in the same place.
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEventsResponse], error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventService_ServiceDesc.Streams[0], EventService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, WatchEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_WatchEventsClient = grpc.ServerStreamingClient[WatchEventsResponse]

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility.
//
// EventService tells a connected client that something changed (§20.3, TODO 8.7).
//
// Its own service and its own file rather than another method on ReaderService,
// because it is the only STREAMING surface in the API and streams fail
// differently: a unary call that errors is one request, while this one holds a
// goroutine, a subscription and a tunnel stream for as long as the tab is open.
// Keeping it separate means the thing with a different lifetime also has a
// different place to look when it misbehaves.
//
// # What this is not
//
// Not a data channel. Events carry IDS, never rows — an event carrying a full
// item is a second serialisation of the same record that can disagree with the
// query the client makes next, and the client would have two sources of truth
// for one article. The event says "this changed"; the client's existing read
// path says what it now is.
//
// Not a replacement for polling the feeds either. The server polls sources on
// its own schedule; this only reports what that polling FOUND, to a client that
// would otherwise show yesterday's list until somebody pressed something.
type EventServiceServer interface {
	// WatchEvents streams changes for the caller's own scope until the client
	// goes away.
	//
	// `since` resumes: a client that reconnects asks for everything after the
	// last sequence it saw, so a reconnect inside the buffer window costs a
	// catch-up batch rather than a full reload. Zero means "only what happens
	// from now on", which is what a fresh tab wants — replaying a thousand
	// buffered events into a page that is about to fetch the current state anyway
	// is work that ends in the same place.
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[WatchEventsResponse]) error
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventServiceServer struct{}

func (UnimplementedEventServiceServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[WatchEventsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}
func (UnimplementedEventServiceServer) testEmbeddedByValue()                      {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventServiceServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, WatchEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventService_WatchEventsServer = grpc.ServerStreamingServer[WatchEventsResponse]

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "articleflux.v1.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _EventService_WatchEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "articleflux/v1/events.proto",
}
