// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: articleflux/v1/reader.proto

package articlefluxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReaderService_ListFeeds_FullMethodName              = "/articleflux.v1.ReaderService/ListFeeds"
	ReaderService_ListItems_FullMethodName              = "/articleflux.v1.ReaderService/ListItems"
	ReaderService_GetItem_FullMethodName                = "/articleflux.v1.ReaderService/GetItem"
	ReaderService_GetItemRevisions_FullMethodName       = "/articleflux.v1.ReaderService/GetItemRevisions"
	ReaderService_ScrollLiveView_FullMethodName         = "/articleflux.v1.ReaderService/ScrollLiveView"
	ReaderService_SetItemState_FullMethodName           = "/articleflux.v1.ReaderService/SetItemState"
	ReaderService_UndoMarkAllRead_FullMethodName        = "/articleflux.v1.ReaderService/UndoMarkAllRead"
	ReaderService_MarkAllRead_FullMethodName            = "/articleflux.v1.ReaderService/MarkAllRead"
	ReaderService_Subscribe_FullMethodName              = "/articleflux.v1.ReaderService/Subscribe"
	ReaderService_Unsubscribe_FullMethodName            = "/articleflux.v1.ReaderService/Unsubscribe"
	ReaderService_ImportOpml_FullMethodName             = "/articleflux.v1.ReaderService/ImportOpml"
	ReaderService_ExportOpml_FullMethodName             = "/articleflux.v1.ReaderService/ExportOpml"
	ReaderService_AnalyzeSite_FullMethodName            = "/articleflux.v1.ReaderService/AnalyzeSite"
	ReaderService_SubscribeScrape_FullMethodName        = "/articleflux.v1.ReaderService/SubscribeScrape"
	ReaderService_Refresh_FullMethodName                = "/articleflux.v1.ReaderService/Refresh"
	ReaderService_Search_FullMethodName                 = "/articleflux.v1.ReaderService/Search"
	ReaderService_GetPrefs_FullMethodName               = "/articleflux.v1.ReaderService/GetPrefs"
	ReaderService_SetPrefs_FullMethodName               = "/articleflux.v1.ReaderService/SetPrefs"
	ReaderService_ListTags_FullMethodName               = "/articleflux.v1.ReaderService/ListTags"
	ReaderService_SetFeedTag_FullMethodName             = "/articleflux.v1.ReaderService/SetFeedTag"
	ReaderService_UpdateTag_FullMethodName              = "/articleflux.v1.ReaderService/UpdateTag"
	ReaderService_ListFolders_FullMethodName            = "/articleflux.v1.ReaderService/ListFolders"
	ReaderService_CreateFolder_FullMethodName           = "/articleflux.v1.ReaderService/CreateFolder"
	ReaderService_RenameFolder_FullMethodName           = "/articleflux.v1.ReaderService/RenameFolder"
	ReaderService_DeleteFolder_FullMethodName           = "/articleflux.v1.ReaderService/DeleteFolder"
	ReaderService_SetFeedFolder_FullMethodName          = "/articleflux.v1.ReaderService/SetFeedFolder"
	ReaderService_SetNote_FullMethodName                = "/articleflux.v1.ReaderService/SetNote"
	ReaderService_ListNotes_FullMethodName              = "/articleflux.v1.ReaderService/ListNotes"
	ReaderService_GetFeedSettings_FullMethodName        = "/articleflux.v1.ReaderService/GetFeedSettings"
	ReaderService_UpdateFeedSettings_FullMethodName     = "/articleflux.v1.ReaderService/UpdateFeedSettings"
	ReaderService_RecordEngagements_FullMethodName      = "/articleflux.v1.ReaderService/RecordEngagements"
	ReaderService_GetInterestProfile_FullMethodName     = "/articleflux.v1.ReaderService/GetInterestProfile"
	ReaderService_SteerInterest_FullMethodName          = "/articleflux.v1.ReaderService/SteerInterest"
	ReaderService_ListRecommendations_FullMethodName    = "/articleflux.v1.ReaderService/ListRecommendations"
	ReaderService_RefreshRecommendations_FullMethodName = "/articleflux.v1.ReaderService/RefreshRecommendations"
	ReaderService_AcceptRecommendation_FullMethodName   = "/articleflux.v1.ReaderService/AcceptRecommendation"
	ReaderService_RejectRecommendation_FullMethodName   = "/articleflux.v1.ReaderService/RejectRecommendation"
)

// ReaderServiceClient is the client API for ReaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReaderService is the reading surface: the sidebar, the list, the article, and
// the four state changes a reader can make.
//
// One service rather than several because all three transports (§20.7) route
// through one service layer — the gRPC tunnel the web client uses, the plain
// HTTPS offline-pack channel, and the Google Reader-compatible REST API that
// Reeder and NetNewsWire speak. Splitting them would let "marked read in Reeder"
// diverge from the web UI, which is the failure the single layer exists to
// prevent.
type ReaderServiceClient interface {
	// ListFeeds returns the sidebar: every subscription with its unread count.
	ListFeeds(ctx context.Context, in *ListFeedsRequest, opts ...grpc.CallOption) (*ListFeedsResponse, error)
	// ListItems returns one page of the item list.
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	// GetItem returns one item with its full content.
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
	// What an article used to say (TODO F34). Separate from GetItem because the
	// history is several full copies of a body and almost nobody asks for it: it
	// is a click on the "edited" badge, not part of opening an article.
	GetItemRevisions(ctx context.Context, in *GetItemRevisionsRequest, opts ...grpc.CallOption) (*GetItemRevisionsResponse, error)
	// Scrolls a live view (§10.1d). Unary and coalesced client-side: wheel events
	// fire dozens per second and one RPC each would flood the tunnel to move a
	// page a few hundred pixels.
	ScrollLiveView(ctx context.Context, in *ScrollLiveViewRequest, opts ...grpc.CallOption) (*ScrollLiveViewResponse, error)
	// SetItemState marks read/unread and starred/unstarred. One RPC rather than
	// four because they share a row, a rev, and an idempotency key — and because
	// the offline outbox replays them together.
	SetItemState(ctx context.Context, in *SetItemStateRequest, opts ...grpc.CallOption) (*SetItemStateResponse, error)
	// UndoMarkAllRead reverses one bulk mark, using the token that mark returned.
	//
	// Bulk marking is the largest irreversible action in the app: one press turns
	// thousands of unread items into none, and a reader who meant one feed and had
	// "All feeds" selected has lost their backlog. Every row in a batch shares the
	// exact read_at the operation wrote, so the batch is identifiable without a
	// journal table — and rows that were ALREADY read keep their earlier stamp, so
	// an undo cannot resurrect something read last week.
	UndoMarkAllRead(ctx context.Context, in *UndoMarkAllReadRequest, opts ...grpc.CallOption) (*UndoMarkAllReadResponse, error)
	// MarkAllRead marks a whole feed or the whole megafeed read.
	MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error)
	// Subscribe adds a feed by URL. The source is global (A14), so this usually
	// attaches an existing row rather than creating one.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	// Unsubscribe removes the subscription. It never deletes the source (A22).
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
	// ImportOpml subscribes to everything in an OPML file, folders and all.
	//
	// This is how somebody ARRIVES. Until it existed the only importer was
	// `articleflux import`, which needs a shell on the server — so on a
	// multi-tenant instance (A13) a member had no path at all, and the operator
	// had to SSH in to add a feed list. Every competitor ships this in the UI.
	//
	// The whole file travels in one message rather than a stream of rows: a
	// 151-feed export is ~32 KB, the parse has to see the document to unwrap a
	// FreshRSS "Subscriptions" wrapper, and a partial upload is not half an
	// import — it is a subscription list missing feeds nobody would notice.
	//
	// It subscribes without fetching. Filling 151 feeds is minutes of network,
	// and an import that appears to hang is one people interrupt halfway; the
	// poller fills them in behind the reader, who has a usable sidebar at once.
	ImportOpml(ctx context.Context, in *ImportOpmlRequest, opts ...grpc.CallOption) (*ImportOpmlResponse, error)
	// ExportOpml writes this reader's subscriptions back out.
	//
	// An importer without an exporter is a roach motel. It is also the check on
	// the importer: the file this returns has to import back into the app.
	ExportOpml(ctx context.Context, in *ExportOpmlRequest, opts ...grpc.CallOption) (*ExportOpmlResponse, error)
	// AnalyzeSite answers "can I follow this page?" for an address that is not
	// itself a feed — the subscribe ladder of §11, deterministic first.
	//
	// Rungs 1-3 are free and always run: <link rel="alternate">, then a short
	// list of conventional paths, each candidate FETCHED AND PARSED before it is
	// offered. The LLM proposes and the parser disposes, which here means no
	// candidate reaches the reader on a model's say-so.
	//
	// Rung 5 — a scrape rule written by the model — runs only when `smart` is set,
	// which the client sends only when the reader pressed the button that says
	// what it costs. It sends the page's markup to OpenAI (§18.8), so it is
	// per-request consent rather than a setting somebody turned on last month.
	AnalyzeSite(ctx context.Context, in *AnalyzeSiteRequest, opts ...grpc.CallOption) (*AnalyzeSiteResponse, error)
	// SubscribeScrape subscribes to a page that has no feed, using a rule
	// AnalyzeSite produced and the reader accepted.
	//
	// Separate from Subscribe rather than a mode of it: this one carries a rule,
	// creates a source with kind='scrape', and is the only path that can write
	// scrape_rules. One RPC that meant two different things would have to accept
	// an empty rule and decide what that meant.
	SubscribeScrape(ctx context.Context, in *SubscribeScrapeRequest, opts ...grpc.CallOption) (*SubscribeScrapeResponse, error)
	// Refresh polls sources now instead of waiting for the scheduler.
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	// Search runs a full-text query (FTS5, G1).
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// GetPrefs returns this user's UI preferences.
	//
	// Server-side rather than localStorage because layout is part of an account,
	// not of a browser: a reader that forgets your pane widths when you open it on
	// a different machine has not remembered anything useful.
	GetPrefs(ctx context.Context, in *GetPrefsRequest, opts ...grpc.CallOption) (*GetPrefsResponse, error)
	// SetPrefs merges keys into this user's preferences. A merge, not a replace,
	// so a stale client cannot erase settings it does not know about.
	SetPrefs(ctx context.Context, in *SetPrefsRequest, opts ...grpc.CallOption) (*SetPrefsResponse, error)
	// ListTags returns this user's tags and which feeds carry them.
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	// SetFeedTag adds or removes a tag on a feed, creating the tag on first use.
	// Nobody wants to manage a taxonomy; they want to label the thing in front of
	// them, and the tag list is the consequence.
	SetFeedTag(ctx context.Context, in *SetFeedTagRequest, opts ...grpc.CallOption) (*SetFeedTagResponse, error)
	// UpdateTag changes how a tag looks in the rail — its label and its glyph —
	// without touching the tag itself.
	//
	// There is no matching GetTagSettings, and that asymmetry with the feed panel
	// is deliberate: ListTags already returns everything the tag panel shows, so
	// fetching it again would be a round trip for data the client is holding. The
	// panel opens instantly as a result, which a settings dialog should.
	UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error)
	// ListFolders returns this user's categories — the named groups the rail
	// files feeds under.
	//
	// A category is WHERE a feed lives; a tag is something you say ABOUT it. That
	// is why a feed has at most one folder and any number of tags, and why the
	// two are separate concepts rather than one with a flag.
	//
	// No feed counts on the wire: ListFeeds already carries folder_id on every
	// feed, so the rail derives them. A second source of the same number is a
	// second thing to keep in step, and the one that drifts is always the one
	// nobody is looking at.
	ListFolders(ctx context.Context, in *ListFoldersRequest, opts ...grpc.CallOption) (*ListFoldersResponse, error)
	// CreateFolder makes a category. Naming one that already exists returns the
	// existing row rather than a duplicate — see the request message.
	CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResponse, error)
	// RenameFolder changes a category's name. Unlike a tag, the name IS editable:
	// nothing else refers to a folder by name, so renaming one renames the row
	// rather than orphaning a key.
	RenameFolder(ctx context.Context, in *RenameFolderRequest, opts ...grpc.CallOption) (*RenameFolderResponse, error)
	// DeleteFolder removes the category and unfiles its feeds. It never
	// unsubscribes anything — deleting a shelf is not deleting the books.
	DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*DeleteFolderResponse, error)
	// SetFeedFolder files a feed, or unfiles it when folder_id is empty.
	SetFeedFolder(ctx context.Context, in *SetFeedFolderRequest, opts ...grpc.CallOption) (*SetFeedFolderResponse, error)
	// SetNote writes or clears the note on an item. An empty body deletes it, so
	// "has a note" stays an existence check.
	SetNote(ctx context.Context, in *SetNoteRequest, opts ...grpc.CallOption) (*SetNoteResponse, error)
	// ListNotes returns the items this user has annotated, most recently written
	// first — it is a list of your own writing, found by when you wrote it.
	ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error)
	// GetFeedSettings returns everything the per-feed panel shows, and
	// UpdateFeedSettings writes back only the fields that were sent.
	//
	// Two RPCs rather than folding this into ListFeeds: the sidebar asks for 151
	// feeds many times a session and does not want health strings, poll intervals
	// or cache depths on any of them.
	GetFeedSettings(ctx context.Context, in *GetFeedSettingsRequest, opts ...grpc.CallOption) (*GetFeedSettingsResponse, error)
	UpdateFeedSettings(ctx context.Context, in *UpdateFeedSettingsRequest, opts ...grpc.CallOption) (*UpdateFeedSettingsResponse, error)
	// RecordEngagements appends observations to the signals log (§18.1).
	//
	// Batched, because the alternative is an RPC per scroll sample. Partial
	// success is a normal outcome rather than an error: one malformed event in a
	// batch of two hundred must not discard the other 199, and the client cannot
	// usefully repair it anyway.
	//
	// This is the one RPC whose failure the client is expected to swallow. A
	// broken signals layer may cost a worse ranking; it may never cost a page
	// that will not load.
	RecordEngagements(ctx context.Context, in *RecordEngagementsRequest, opts ...grpc.CallOption) (*RecordEngagementsResponse, error)
	// GetInterestProfile returns what the interest layer believes about this
	// reader, and SteerInterest is how they say it is wrong (§18.2, §18.9).
	//
	// These two are the other half of the ranked page. Every reason on a My Feed
	// row names a judgement — "about Pro Max, which you follow", "close to your
	// camera reading" — and until there was somewhere to see the whole set of
	// those judgements and change them, the explanation was a statement rather
	// than a control. On a real database the top followed thing was "Pro Max", a
	// phrase the extractor lifted out of a handset headline; nothing about the
	// ranked page was broken, and there was no way to say so.
	//
	// Read and write are separate RPCs rather than one patch-and-return, because
	// the read is expensive (topics, entities, feeds and the factor mix behind the
	// current ranking) and a reader adjusting four rows should not pay for it four
	// times.
	GetInterestProfile(ctx context.Context, in *GetInterestProfileRequest, opts ...grpc.CallOption) (*GetInterestProfileResponse, error)
	SteerInterest(ctx context.Context, in *SteerInterestRequest, opts ...grpc.CallOption) (*SteerInterestResponse, error)
	// ListRecommendations returns the reader's open suggestions (§18.7, M16) —
	// sites they do not follow yet, scored by internal/recommend and, when
	// Smart+'s relevance gate ran, reviewed against two of the candidate's own
	// posts first. Every entry's evidence is shown verbatim; see recommend.go's
	// package doc for why an unexplained suggestion is worth less than none.
	ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...grpc.CallOption) (*ListRecommendationsResponse, error)
	// RefreshRecommendations enqueues a fresh scoring pass (internal/recommendjob).
	// Async — the job runs on the pool, and the client re-polls ListRecommendations
	// rather than blocking a request on a batch of validating fetches.
	RefreshRecommendations(ctx context.Context, in *RefreshRecommendationsRequest, opts ...grpc.CallOption) (*RefreshRecommendationsResponse, error)
	// AcceptRecommendation subscribes to the suggestion's feed URL — the one
	// internal/discover already validated, not a re-discovery from the domain —
	// and marks the suggestion accepted so it stops appearing in the open list.
	AcceptRecommendation(ctx context.Context, in *AcceptRecommendationRequest, opts ...grpc.CallOption) (*AcceptRecommendationResponse, error)
	// RejectRecommendation is permanent (§18.7): the domain is never suggested
	// again on this account.
	RejectRecommendation(ctx context.Context, in *RejectRecommendationRequest, opts ...grpc.CallOption) (*RejectRecommendationResponse, error)
}

type readerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReaderServiceClient(cc grpc.ClientConnInterface) ReaderServiceClient {
	return &readerServiceClient{cc}
}

func (c *readerServiceClient) ListFeeds(ctx context.Context, in *ListFeedsRequest, opts ...grpc.CallOption) (*ListFeedsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeedsResponse)
	err := c.cc.Invoke(ctx, ReaderService_ListFeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, ReaderService_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemResponse)
	err := c.cc.Invoke(ctx, ReaderService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) GetItemRevisions(ctx context.Context, in *GetItemRevisionsRequest, opts ...grpc.CallOption) (*GetItemRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemRevisionsResponse)
	err := c.cc.Invoke(ctx, ReaderService_GetItemRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) ScrollLiveView(ctx context.Context, in *ScrollLiveViewRequest, opts ...grpc.CallOption) (*ScrollLiveViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScrollLiveViewResponse)
	err := c.cc.Invoke(ctx, ReaderService_ScrollLiveView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) SetItemState(ctx context.Context, in *SetItemStateRequest, opts ...grpc.CallOption) (*SetItemStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetItemStateResponse)
	err := c.cc.Invoke(ctx, ReaderService_SetItemState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) UndoMarkAllRead(ctx context.Context, in *UndoMarkAllReadRequest, opts ...grpc.CallOption) (*UndoMarkAllReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndoMarkAllReadResponse)
	err := c.cc.Invoke(ctx, ReaderService_UndoMarkAllRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAllReadResponse)
	err := c.cc.Invoke(ctx, ReaderService_MarkAllRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, ReaderService_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeResponse)
	err := c.cc.Invoke(ctx, ReaderService_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) ImportOpml(ctx context.Context, in *ImportOpmlRequest, opts ...grpc.CallOption) (*ImportOpmlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportOpmlResponse)
	err := c.cc.Invoke(ctx, ReaderService_ImportOpml_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) ExportOpml(ctx context.Context, in *ExportOpmlRequest, opts ...grpc.CallOption) (*ExportOpmlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportOpmlResponse)
	err := c.cc.Invoke(ctx, ReaderService_ExportOpml_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) AnalyzeSite(ctx context.Context, in *AnalyzeSiteRequest, opts ...grpc.CallOption) (*AnalyzeSiteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeSiteResponse)
	err := c.cc.Invoke(ctx, ReaderService_AnalyzeSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) SubscribeScrape(ctx context.Context, in *SubscribeScrapeRequest, opts ...grpc.CallOption) (*SubscribeScrapeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeScrapeResponse)
	err := c.cc.Invoke(ctx, ReaderService_SubscribeScrape_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, ReaderService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, ReaderService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) GetPrefs(ctx context.Context, in *GetPrefsRequest, opts ...grpc.CallOption) (*GetPrefsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrefsResponse)
	err := c.cc.Invoke(ctx, ReaderService_GetPrefs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) SetPrefs(ctx context.Context, in *SetPrefsRequest, opts ...grpc.CallOption) (*SetPrefsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPrefsResponse)
	err := c.cc.Invoke(ctx, ReaderService_SetPrefs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, ReaderService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) SetFeedTag(ctx context.Context, in *SetFeedTagRequest, opts ...grpc.CallOption) (*SetFeedTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFeedTagResponse)
	err := c.cc.Invoke(ctx, ReaderService_SetFeedTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTagResponse)
	err := c.cc.Invoke(ctx, ReaderService_UpdateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) ListFolders(ctx context.Context, in *ListFoldersRequest, opts ...grpc.CallOption) (*ListFoldersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFoldersResponse)
	err := c.cc.Invoke(ctx, ReaderService_ListFolders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) CreateFolder(ctx context.Context, in *CreateFolderRequest, opts ...grpc.CallOption) (*CreateFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFolderResponse)
	err := c.cc.Invoke(ctx, ReaderService_CreateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) RenameFolder(ctx context.Context, in *RenameFolderRequest, opts ...grpc.CallOption) (*RenameFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameFolderResponse)
	err := c.cc.Invoke(ctx, ReaderService_RenameFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) DeleteFolder(ctx context.Context, in *DeleteFolderRequest, opts ...grpc.CallOption) (*DeleteFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFolderResponse)
	err := c.cc.Invoke(ctx, ReaderService_DeleteFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) SetFeedFolder(ctx context.Context, in *SetFeedFolderRequest, opts ...grpc.CallOption) (*SetFeedFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFeedFolderResponse)
	err := c.cc.Invoke(ctx, ReaderService_SetFeedFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) SetNote(ctx context.Context, in *SetNoteRequest, opts ...grpc.CallOption) (*SetNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNoteResponse)
	err := c.cc.Invoke(ctx, ReaderService_SetNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotesResponse)
	err := c.cc.Invoke(ctx, ReaderService_ListNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) GetFeedSettings(ctx context.Context, in *GetFeedSettingsRequest, opts ...grpc.CallOption) (*GetFeedSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedSettingsResponse)
	err := c.cc.Invoke(ctx, ReaderService_GetFeedSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) UpdateFeedSettings(ctx context.Context, in *UpdateFeedSettingsRequest, opts ...grpc.CallOption) (*UpdateFeedSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFeedSettingsResponse)
	err := c.cc.Invoke(ctx, ReaderService_UpdateFeedSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) RecordEngagements(ctx context.Context, in *RecordEngagementsRequest, opts ...grpc.CallOption) (*RecordEngagementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordEngagementsResponse)
	err := c.cc.Invoke(ctx, ReaderService_RecordEngagements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) GetInterestProfile(ctx context.Context, in *GetInterestProfileRequest, opts ...grpc.CallOption) (*GetInterestProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterestProfileResponse)
	err := c.cc.Invoke(ctx, ReaderService_GetInterestProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) SteerInterest(ctx context.Context, in *SteerInterestRequest, opts ...grpc.CallOption) (*SteerInterestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SteerInterestResponse)
	err := c.cc.Invoke(ctx, ReaderService_SteerInterest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...grpc.CallOption) (*ListRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecommendationsResponse)
	err := c.cc.Invoke(ctx, ReaderService_ListRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) RefreshRecommendations(ctx context.Context, in *RefreshRecommendationsRequest, opts ...grpc.CallOption) (*RefreshRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshRecommendationsResponse)
	err := c.cc.Invoke(ctx, ReaderService_RefreshRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) AcceptRecommendation(ctx context.Context, in *AcceptRecommendationRequest, opts ...grpc.CallOption) (*AcceptRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptRecommendationResponse)
	err := c.cc.Invoke(ctx, ReaderService_AcceptRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) RejectRecommendation(ctx context.Context, in *RejectRecommendationRequest, opts ...grpc.CallOption) (*RejectRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectRecommendationResponse)
	err := c.cc.Invoke(ctx, ReaderService_RejectRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReaderServiceServer is the server API for ReaderService service.
// All implementations must embed UnimplementedReaderServiceServer
// for forward compatibility.
//
// ReaderService is the reading surface: the sidebar, the list, the article, and
// the four state changes a reader can make.
//
// One service rather than several because all three transports (§20.7) route
// through one service layer — the gRPC tunnel the web client uses, the plain
// HTTPS offline-pack channel, and the Google Reader-compatible REST API that
// Reeder and NetNewsWire speak. Splitting them would let "marked read in Reeder"
// diverge from the web UI, which is the failure the single layer exists to
// prevent.
type ReaderServiceServer interface {
	// ListFeeds returns the sidebar: every subscription with its unread count.
	ListFeeds(context.Context, *ListFeedsRequest) (*ListFeedsResponse, error)
	// ListItems returns one page of the item list.
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	// GetItem returns one item with its full content.
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
	// What an article used to say (TODO F34). Separate from GetItem because the
	// history is several full copies of a body and almost nobody asks for it: it
	// is a click on the "edited" badge, not part of opening an article.
	GetItemRevisions(context.Context, *GetItemRevisionsRequest) (*GetItemRevisionsResponse, error)
	// Scrolls a live view (§10.1d). Unary and coalesced client-side: wheel events
	// fire dozens per second and one RPC each would flood the tunnel to move a
	// page a few hundred pixels.
	ScrollLiveView(context.Context, *ScrollLiveViewRequest) (*ScrollLiveViewResponse, error)
	// SetItemState marks read/unread and starred/unstarred. One RPC rather than
	// four because they share a row, a rev, and an idempotency key — and because
	// the offline outbox replays them together.
	SetItemState(context.Context, *SetItemStateRequest) (*SetItemStateResponse, error)
	// UndoMarkAllRead reverses one bulk mark, using the token that mark returned.
	//
	// Bulk marking is the largest irreversible action in the app: one press turns
	// thousands of unread items into none, and a reader who meant one feed and had
	// "All feeds" selected has lost their backlog. Every row in a batch shares the
	// exact read_at the operation wrote, so the batch is identifiable without a
	// journal table — and rows that were ALREADY read keep their earlier stamp, so
	// an undo cannot resurrect something read last week.
	UndoMarkAllRead(context.Context, *UndoMarkAllReadRequest) (*UndoMarkAllReadResponse, error)
	// MarkAllRead marks a whole feed or the whole megafeed read.
	MarkAllRead(context.Context, *MarkAllReadRequest) (*MarkAllReadResponse, error)
	// Subscribe adds a feed by URL. The source is global (A14), so this usually
	// attaches an existing row rather than creating one.
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	// Unsubscribe removes the subscription. It never deletes the source (A22).
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)
	// ImportOpml subscribes to everything in an OPML file, folders and all.
	//
	// This is how somebody ARRIVES. Until it existed the only importer was
	// `articleflux import`, which needs a shell on the server — so on a
	// multi-tenant instance (A13) a member had no path at all, and the operator
	// had to SSH in to add a feed list. Every competitor ships this in the UI.
	//
	// The whole file travels in one message rather than a stream of rows: a
	// 151-feed export is ~32 KB, the parse has to see the document to unwrap a
	// FreshRSS "Subscriptions" wrapper, and a partial upload is not half an
	// import — it is a subscription list missing feeds nobody would notice.
	//
	// It subscribes without fetching. Filling 151 feeds is minutes of network,
	// and an import that appears to hang is one people interrupt halfway; the
	// poller fills them in behind the reader, who has a usable sidebar at once.
	ImportOpml(context.Context, *ImportOpmlRequest) (*ImportOpmlResponse, error)
	// ExportOpml writes this reader's subscriptions back out.
	//
	// An importer without an exporter is a roach motel. It is also the check on
	// the importer: the file this returns has to import back into the app.
	ExportOpml(context.Context, *ExportOpmlRequest) (*ExportOpmlResponse, error)
	// AnalyzeSite answers "can I follow this page?" for an address that is not
	// itself a feed — the subscribe ladder of §11, deterministic first.
	//
	// Rungs 1-3 are free and always run: <link rel="alternate">, then a short
	// list of conventional paths, each candidate FETCHED AND PARSED before it is
	// offered. The LLM proposes and the parser disposes, which here means no
	// candidate reaches the reader on a model's say-so.
	//
	// Rung 5 — a scrape rule written by the model — runs only when `smart` is set,
	// which the client sends only when the reader pressed the button that says
	// what it costs. It sends the page's markup to OpenAI (§18.8), so it is
	// per-request consent rather than a setting somebody turned on last month.
	AnalyzeSite(context.Context, *AnalyzeSiteRequest) (*AnalyzeSiteResponse, error)
	// SubscribeScrape subscribes to a page that has no feed, using a rule
	// AnalyzeSite produced and the reader accepted.
	//
	// Separate from Subscribe rather than a mode of it: this one carries a rule,
	// creates a source with kind='scrape', and is the only path that can write
	// scrape_rules. One RPC that meant two different things would have to accept
	// an empty rule and decide what that meant.
	SubscribeScrape(context.Context, *SubscribeScrapeRequest) (*SubscribeScrapeResponse, error)
	// Refresh polls sources now instead of waiting for the scheduler.
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	// Search runs a full-text query (FTS5, G1).
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// GetPrefs returns this user's UI preferences.
	//
	// Server-side rather than localStorage because layout is part of an account,
	// not of a browser: a reader that forgets your pane widths when you open it on
	// a different machine has not remembered anything useful.
	GetPrefs(context.Context, *GetPrefsRequest) (*GetPrefsResponse, error)
	// SetPrefs merges keys into this user's preferences. A merge, not a replace,
	// so a stale client cannot erase settings it does not know about.
	SetPrefs(context.Context, *SetPrefsRequest) (*SetPrefsResponse, error)
	// ListTags returns this user's tags and which feeds carry them.
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	// SetFeedTag adds or removes a tag on a feed, creating the tag on first use.
	// Nobody wants to manage a taxonomy; they want to label the thing in front of
	// them, and the tag list is the consequence.
	SetFeedTag(context.Context, *SetFeedTagRequest) (*SetFeedTagResponse, error)
	// UpdateTag changes how a tag looks in the rail — its label and its glyph —
	// without touching the tag itself.
	//
	// There is no matching GetTagSettings, and that asymmetry with the feed panel
	// is deliberate: ListTags already returns everything the tag panel shows, so
	// fetching it again would be a round trip for data the client is holding. The
	// panel opens instantly as a result, which a settings dialog should.
	UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error)
	// ListFolders returns this user's categories — the named groups the rail
	// files feeds under.
	//
	// A category is WHERE a feed lives; a tag is something you say ABOUT it. That
	// is why a feed has at most one folder and any number of tags, and why the
	// two are separate concepts rather than one with a flag.
	//
	// No feed counts on the wire: ListFeeds already carries folder_id on every
	// feed, so the rail derives them. A second source of the same number is a
	// second thing to keep in step, and the one that drifts is always the one
	// nobody is looking at.
	ListFolders(context.Context, *ListFoldersRequest) (*ListFoldersResponse, error)
	// CreateFolder makes a category. Naming one that already exists returns the
	// existing row rather than a duplicate — see the request message.
	CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResponse, error)
	// RenameFolder changes a category's name. Unlike a tag, the name IS editable:
	// nothing else refers to a folder by name, so renaming one renames the row
	// rather than orphaning a key.
	RenameFolder(context.Context, *RenameFolderRequest) (*RenameFolderResponse, error)
	// DeleteFolder removes the category and unfiles its feeds. It never
	// unsubscribes anything — deleting a shelf is not deleting the books.
	DeleteFolder(context.Context, *DeleteFolderRequest) (*DeleteFolderResponse, error)
	// SetFeedFolder files a feed, or unfiles it when folder_id is empty.
	SetFeedFolder(context.Context, *SetFeedFolderRequest) (*SetFeedFolderResponse, error)
	// SetNote writes or clears the note on an item. An empty body deletes it, so
	// "has a note" stays an existence check.
	SetNote(context.Context, *SetNoteRequest) (*SetNoteResponse, error)
	// ListNotes returns the items this user has annotated, most recently written
	// first — it is a list of your own writing, found by when you wrote it.
	ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error)
	// GetFeedSettings returns everything the per-feed panel shows, and
	// UpdateFeedSettings writes back only the fields that were sent.
	//
	// Two RPCs rather than folding this into ListFeeds: the sidebar asks for 151
	// feeds many times a session and does not want health strings, poll intervals
	// or cache depths on any of them.
	GetFeedSettings(context.Context, *GetFeedSettingsRequest) (*GetFeedSettingsResponse, error)
	UpdateFeedSettings(context.Context, *UpdateFeedSettingsRequest) (*UpdateFeedSettingsResponse, error)
	// RecordEngagements appends observations to the signals log (§18.1).
	//
	// Batched, because the alternative is an RPC per scroll sample. Partial
	// success is a normal outcome rather than an error: one malformed event in a
	// batch of two hundred must not discard the other 199, and the client cannot
	// usefully repair it anyway.
	//
	// This is the one RPC whose failure the client is expected to swallow. A
	// broken signals layer may cost a worse ranking; it may never cost a page
	// that will not load.
	RecordEngagements(context.Context, *RecordEngagementsRequest) (*RecordEngagementsResponse, error)
	// GetInterestProfile returns what the interest layer believes about this
	// reader, and SteerInterest is how they say it is wrong (§18.2, §18.9).
	//
	// These two are the other half of the ranked page. Every reason on a My Feed
	// row names a judgement — "about Pro Max, which you follow", "close to your
	// camera reading" — and until there was somewhere to see the whole set of
	// those judgements and change them, the explanation was a statement rather
	// than a control. On a real database the top followed thing was "Pro Max", a
	// phrase the extractor lifted out of a handset headline; nothing about the
	// ranked page was broken, and there was no way to say so.
	//
	// Read and write are separate RPCs rather than one patch-and-return, because
	// the read is expensive (topics, entities, feeds and the factor mix behind the
	// current ranking) and a reader adjusting four rows should not pay for it four
	// times.
	GetInterestProfile(context.Context, *GetInterestProfileRequest) (*GetInterestProfileResponse, error)
	SteerInterest(context.Context, *SteerInterestRequest) (*SteerInterestResponse, error)
	// ListRecommendations returns the reader's open suggestions (§18.7, M16) —
	// sites they do not follow yet, scored by internal/recommend and, when
	// Smart+'s relevance gate ran, reviewed against two of the candidate's own
	// posts first. Every entry's evidence is shown verbatim; see recommend.go's
	// package doc for why an unexplained suggestion is worth less than none.
	ListRecommendations(context.Context, *ListRecommendationsRequest) (*ListRecommendationsResponse, error)
	// RefreshRecommendations enqueues a fresh scoring pass (internal/recommendjob).
	// Async — the job runs on the pool, and the client re-polls ListRecommendations
	// rather than blocking a request on a batch of validating fetches.
	RefreshRecommendations(context.Context, *RefreshRecommendationsRequest) (*RefreshRecommendationsResponse, error)
	// AcceptRecommendation subscribes to the suggestion's feed URL — the one
	// internal/discover already validated, not a re-discovery from the domain —
	// and marks the suggestion accepted so it stops appearing in the open list.
	AcceptRecommendation(context.Context, *AcceptRecommendationRequest) (*AcceptRecommendationResponse, error)
	// RejectRecommendation is permanent (§18.7): the domain is never suggested
	// again on this account.
	RejectRecommendation(context.Context, *RejectRecommendationRequest) (*RejectRecommendationResponse, error)
	mustEmbedUnimplementedReaderServiceServer()
}

// UnimplementedReaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReaderServiceServer struct{}

func (UnimplementedReaderServiceServer) ListFeeds(context.Context, *ListFeedsRequest) (*ListFeedsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFeeds not implemented")
}
func (UnimplementedReaderServiceServer) ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedReaderServiceServer) GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedReaderServiceServer) GetItemRevisions(context.Context, *GetItemRevisionsRequest) (*GetItemRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItemRevisions not implemented")
}
func (UnimplementedReaderServiceServer) ScrollLiveView(context.Context, *ScrollLiveViewRequest) (*ScrollLiveViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScrollLiveView not implemented")
}
func (UnimplementedReaderServiceServer) SetItemState(context.Context, *SetItemStateRequest) (*SetItemStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetItemState not implemented")
}
func (UnimplementedReaderServiceServer) UndoMarkAllRead(context.Context, *UndoMarkAllReadRequest) (*UndoMarkAllReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UndoMarkAllRead not implemented")
}
func (UnimplementedReaderServiceServer) MarkAllRead(context.Context, *MarkAllReadRequest) (*MarkAllReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAllRead not implemented")
}
func (UnimplementedReaderServiceServer) Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedReaderServiceServer) Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedReaderServiceServer) ImportOpml(context.Context, *ImportOpmlRequest) (*ImportOpmlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportOpml not implemented")
}
func (UnimplementedReaderServiceServer) ExportOpml(context.Context, *ExportOpmlRequest) (*ExportOpmlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportOpml not implemented")
}
func (UnimplementedReaderServiceServer) AnalyzeSite(context.Context, *AnalyzeSiteRequest) (*AnalyzeSiteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeSite not implemented")
}
func (UnimplementedReaderServiceServer) SubscribeScrape(context.Context, *SubscribeScrapeRequest) (*SubscribeScrapeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubscribeScrape not implemented")
}
func (UnimplementedReaderServiceServer) Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedReaderServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedReaderServiceServer) GetPrefs(context.Context, *GetPrefsRequest) (*GetPrefsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrefs not implemented")
}
func (UnimplementedReaderServiceServer) SetPrefs(context.Context, *SetPrefsRequest) (*SetPrefsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPrefs not implemented")
}
func (UnimplementedReaderServiceServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedReaderServiceServer) SetFeedTag(context.Context, *SetFeedTagRequest) (*SetFeedTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFeedTag not implemented")
}
func (UnimplementedReaderServiceServer) UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTag not implemented")
}
func (UnimplementedReaderServiceServer) ListFolders(context.Context, *ListFoldersRequest) (*ListFoldersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFolders not implemented")
}
func (UnimplementedReaderServiceServer) CreateFolder(context.Context, *CreateFolderRequest) (*CreateFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFolder not implemented")
}
func (UnimplementedReaderServiceServer) RenameFolder(context.Context, *RenameFolderRequest) (*RenameFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameFolder not implemented")
}
func (UnimplementedReaderServiceServer) DeleteFolder(context.Context, *DeleteFolderRequest) (*DeleteFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFolder not implemented")
}
func (UnimplementedReaderServiceServer) SetFeedFolder(context.Context, *SetFeedFolderRequest) (*SetFeedFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFeedFolder not implemented")
}
func (UnimplementedReaderServiceServer) SetNote(context.Context, *SetNoteRequest) (*SetNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNote not implemented")
}
func (UnimplementedReaderServiceServer) ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotes not implemented")
}
func (UnimplementedReaderServiceServer) GetFeedSettings(context.Context, *GetFeedSettingsRequest) (*GetFeedSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedSettings not implemented")
}
func (UnimplementedReaderServiceServer) UpdateFeedSettings(context.Context, *UpdateFeedSettingsRequest) (*UpdateFeedSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFeedSettings not implemented")
}
func (UnimplementedReaderServiceServer) RecordEngagements(context.Context, *RecordEngagementsRequest) (*RecordEngagementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordEngagements not implemented")
}
func (UnimplementedReaderServiceServer) GetInterestProfile(context.Context, *GetInterestProfileRequest) (*GetInterestProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterestProfile not implemented")
}
func (UnimplementedReaderServiceServer) SteerInterest(context.Context, *SteerInterestRequest) (*SteerInterestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SteerInterest not implemented")
}
func (UnimplementedReaderServiceServer) ListRecommendations(context.Context, *ListRecommendationsRequest) (*ListRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecommendations not implemented")
}
func (UnimplementedReaderServiceServer) RefreshRecommendations(context.Context, *RefreshRecommendationsRequest) (*RefreshRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshRecommendations not implemented")
}
func (UnimplementedReaderServiceServer) AcceptRecommendation(context.Context, *AcceptRecommendationRequest) (*AcceptRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptRecommendation not implemented")
}
func (UnimplementedReaderServiceServer) RejectRecommendation(context.Context, *RejectRecommendationRequest) (*RejectRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectRecommendation not implemented")
}
func (UnimplementedReaderServiceServer) mustEmbedUnimplementedReaderServiceServer() {}
func (UnimplementedReaderServiceServer) testEmbeddedByValue()                       {}

// UnsafeReaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReaderServiceServer will
// result in compilation errors.
type UnsafeReaderServiceServer interface {
	mustEmbedUnimplementedReaderServiceServer()
}

func RegisterReaderServiceServer(s grpc.ServiceRegistrar, srv ReaderServiceServer) {
	// If the following call panics, it indicates UnimplementedReaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReaderService_ServiceDesc, srv)
}

func _ReaderService_ListFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ListFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ListFeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ListFeeds(ctx, req.(*ListFeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_GetItemRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).GetItemRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_GetItemRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).GetItemRevisions(ctx, req.(*GetItemRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_ScrollLiveView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrollLiveViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ScrollLiveView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ScrollLiveView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ScrollLiveView(ctx, req.(*ScrollLiveViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_SetItemState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).SetItemState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_SetItemState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).SetItemState(ctx, req.(*SetItemStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_UndoMarkAllRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndoMarkAllReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).UndoMarkAllRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_UndoMarkAllRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).UndoMarkAllRead(ctx, req.(*UndoMarkAllReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_MarkAllRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).MarkAllRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_MarkAllRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).MarkAllRead(ctx, req.(*MarkAllReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_ImportOpml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportOpmlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ImportOpml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ImportOpml_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ImportOpml(ctx, req.(*ImportOpmlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_ExportOpml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportOpmlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ExportOpml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ExportOpml_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ExportOpml(ctx, req.(*ExportOpmlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_AnalyzeSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).AnalyzeSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_AnalyzeSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).AnalyzeSite(ctx, req.(*AnalyzeSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_SubscribeScrape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeScrapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).SubscribeScrape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_SubscribeScrape_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).SubscribeScrape(ctx, req.(*SubscribeScrapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_GetPrefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).GetPrefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_GetPrefs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).GetPrefs(ctx, req.(*GetPrefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_SetPrefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPrefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).SetPrefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_SetPrefs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).SetPrefs(ctx, req.(*SetPrefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_SetFeedTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFeedTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).SetFeedTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_SetFeedTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).SetFeedTag(ctx, req.(*SetFeedTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_UpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).UpdateTag(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_ListFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ListFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ListFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ListFolders(ctx, req.(*ListFoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_CreateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).CreateFolder(ctx, req.(*CreateFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_RenameFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).RenameFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_RenameFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).RenameFolder(ctx, req.(*RenameFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_DeleteFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).DeleteFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_DeleteFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).DeleteFolder(ctx, req.(*DeleteFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_SetFeedFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFeedFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).SetFeedFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_SetFeedFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).SetFeedFolder(ctx, req.(*SetFeedFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_SetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).SetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_SetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).SetNote(ctx, req.(*SetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_ListNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ListNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ListNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ListNotes(ctx, req.(*ListNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_GetFeedSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).GetFeedSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_GetFeedSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).GetFeedSettings(ctx, req.(*GetFeedSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_UpdateFeedSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeedSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).UpdateFeedSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_UpdateFeedSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).UpdateFeedSettings(ctx, req.(*UpdateFeedSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_RecordEngagements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEngagementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).RecordEngagements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_RecordEngagements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).RecordEngagements(ctx, req.(*RecordEngagementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_GetInterestProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterestProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).GetInterestProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_GetInterestProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).GetInterestProfile(ctx, req.(*GetInterestProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_SteerInterest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SteerInterestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).SteerInterest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_SteerInterest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).SteerInterest(ctx, req.(*SteerInterestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_ListRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ListRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ListRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ListRecommendations(ctx, req.(*ListRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_RefreshRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).RefreshRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_RefreshRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).RefreshRecommendations(ctx, req.(*RefreshRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_AcceptRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).AcceptRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_AcceptRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).AcceptRecommendation(ctx, req.(*AcceptRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_RejectRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).RejectRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_RejectRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).RejectRecommendation(ctx, req.(*RejectRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReaderService_ServiceDesc is the grpc.ServiceDesc for ReaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "articleflux.v1.ReaderService",
	HandlerType: (*ReaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFeeds",
			Handler:    _ReaderService_ListFeeds_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _ReaderService_ListItems_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _ReaderService_GetItem_Handler,
		},
		{
			MethodName: "GetItemRevisions",
			Handler:    _ReaderService_GetItemRevisions_Handler,
		},
		{
			MethodName: "ScrollLiveView",
			Handler:    _ReaderService_ScrollLiveView_Handler,
		},
		{
			MethodName: "SetItemState",
			Handler:    _ReaderService_SetItemState_Handler,
		},
		{
			MethodName: "UndoMarkAllRead",
			Handler:    _ReaderService_UndoMarkAllRead_Handler,
		},
		{
			MethodName: "MarkAllRead",
			Handler:    _ReaderService_MarkAllRead_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _ReaderService_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _ReaderService_Unsubscribe_Handler,
		},
		{
			MethodName: "ImportOpml",
			Handler:    _ReaderService_ImportOpml_Handler,
		},
		{
			MethodName: "ExportOpml",
			Handler:    _ReaderService_ExportOpml_Handler,
		},
		{
			MethodName: "AnalyzeSite",
			Handler:    _ReaderService_AnalyzeSite_Handler,
		},
		{
			MethodName: "SubscribeScrape",
			Handler:    _ReaderService_SubscribeScrape_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _ReaderService_Refresh_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _ReaderService_Search_Handler,
		},
		{
			MethodName: "GetPrefs",
			Handler:    _ReaderService_GetPrefs_Handler,
		},
		{
			MethodName: "SetPrefs",
			Handler:    _ReaderService_SetPrefs_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _ReaderService_ListTags_Handler,
		},
		{
			MethodName: "SetFeedTag",
			Handler:    _ReaderService_SetFeedTag_Handler,
		},
		{
			MethodName: "UpdateTag",
			Handler:    _ReaderService_UpdateTag_Handler,
		},
		{
			MethodName: "ListFolders",
			Handler:    _ReaderService_ListFolders_Handler,
		},
		{
			MethodName: "CreateFolder",
			Handler:    _ReaderService_CreateFolder_Handler,
		},
		{
			MethodName: "RenameFolder",
			Handler:    _ReaderService_RenameFolder_Handler,
		},
		{
			MethodName: "DeleteFolder",
			Handler:    _ReaderService_DeleteFolder_Handler,
		},
		{
			MethodName: "SetFeedFolder",
			Handler:    _ReaderService_SetFeedFolder_Handler,
		},
		{
			MethodName: "SetNote",
			Handler:    _ReaderService_SetNote_Handler,
		},
		{
			MethodName: "ListNotes",
			Handler:    _ReaderService_ListNotes_Handler,
		},
		{
			MethodName: "GetFeedSettings",
			Handler:    _ReaderService_GetFeedSettings_Handler,
		},
		{
			MethodName: "UpdateFeedSettings",
			Handler:    _ReaderService_UpdateFeedSettings_Handler,
		},
		{
			MethodName: "RecordEngagements",
			Handler:    _ReaderService_RecordEngagements_Handler,
		},
		{
			MethodName: "GetInterestProfile",
			Handler:    _ReaderService_GetInterestProfile_Handler,
		},
		{
			MethodName: "SteerInterest",
			Handler:    _ReaderService_SteerInterest_Handler,
		},
		{
			MethodName: "ListRecommendations",
			Handler:    _ReaderService_ListRecommendations_Handler,
		},
		{
			MethodName: "RefreshRecommendations",
			Handler:    _ReaderService_RefreshRecommendations_Handler,
		},
		{
			MethodName: "AcceptRecommendation",
			Handler:    _ReaderService_AcceptRecommendation_Handler,
		},
		{
			MethodName: "RejectRecommendation",
			Handler:    _ReaderService_RejectRecommendation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "articleflux/v1/reader.proto",
}
