// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: articleflux/v1/smart.proto

package articlefluxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSmartConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSmartConfigRequest) Reset() {
	*x = GetSmartConfigRequest{}
	mi := &file_articleflux_v1_smart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSmartConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSmartConfigRequest) ProtoMessage() {}

func (x *GetSmartConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_smart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSmartConfigRequest.ProtoReflect.Descriptor instead.
func (*GetSmartConfigRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_smart_proto_rawDescGZIP(), []int{0}
}

type GetSmartConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether a key is stored AND usable. False means every Smart+ feature is
	// unavailable, which is the correct state for an instance nobody configured.
	Configured bool `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	// Last four characters of the stored key, or empty. Never the key.
	KeyHint string `protobuf:"bytes,2,opt,name=key_hint,json=keyHint,proto3" json:"key_hint,omitempty"`
	// Whether the server can encrypt secrets at all. False means it has no
	// encryption key on disk, and SetSmartConfig will refuse rather than store a
	// credential in the clear.
	CanStoreSecrets bool `protobuf:"varint,3,opt,name=can_store_secrets,json=canStoreSecrets,proto3" json:"can_store_secrets,omitempty"`
	// The model every Smart+ feature uses, and the built-in default when unset.
	Model        string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	DefaultModel string `protobuf:"bytes,5,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	// Tokens spent since this server process started. Not a bill — a signal.
	// Restart-scoped on purpose: a persisted counter that nobody resets becomes a
	// number people stop reading.
	InputTokens  int64 `protobuf:"varint,10,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens int64 `protobuf:"varint,11,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	Requests     int64 `protobuf:"varint,12,opt,name=requests,proto3" json:"requests,omitempty"`
	// True when the key came from OPENAI_API_KEY rather than from this screen.
	// The screen says so, because "I deleted the key and it still works" is
	// otherwise unexplainable.
	FromEnvironment bool `protobuf:"varint,20,opt,name=from_environment,json=fromEnvironment,proto3" json:"from_environment,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSmartConfigResponse) Reset() {
	*x = GetSmartConfigResponse{}
	mi := &file_articleflux_v1_smart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSmartConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSmartConfigResponse) ProtoMessage() {}

func (x *GetSmartConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_smart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSmartConfigResponse.ProtoReflect.Descriptor instead.
func (*GetSmartConfigResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_smart_proto_rawDescGZIP(), []int{1}
}

func (x *GetSmartConfigResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *GetSmartConfigResponse) GetKeyHint() string {
	if x != nil {
		return x.KeyHint
	}
	return ""
}

func (x *GetSmartConfigResponse) GetCanStoreSecrets() bool {
	if x != nil {
		return x.CanStoreSecrets
	}
	return false
}

func (x *GetSmartConfigResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetSmartConfigResponse) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

func (x *GetSmartConfigResponse) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *GetSmartConfigResponse) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *GetSmartConfigResponse) GetRequests() int64 {
	if x != nil {
		return x.Requests
	}
	return 0
}

func (x *GetSmartConfigResponse) GetFromEnvironment() bool {
	if x != nil {
		return x.FromEnvironment
	}
	return false
}

type SetSmartConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty leaves the stored key untouched, so the model can be changed without
	// re-pasting a credential.
	OpenaiApiKey string `protobuf:"bytes,1,opt,name=openai_api_key,json=openaiApiKey,proto3" json:"openai_api_key,omitempty"`
	// Removes the stored key. Explicit rather than inferred from an empty string,
	// because "leave it alone" and "delete it" are different intentions and a
	// form that confuses them deletes credentials by accident.
	ClearApiKey bool `protobuf:"varint,2,opt,name=clear_api_key,json=clearApiKey,proto3" json:"clear_api_key,omitempty"`
	// Empty leaves the model untouched.
	Model         string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSmartConfigRequest) Reset() {
	*x = SetSmartConfigRequest{}
	mi := &file_articleflux_v1_smart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSmartConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSmartConfigRequest) ProtoMessage() {}

func (x *SetSmartConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_smart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSmartConfigRequest.ProtoReflect.Descriptor instead.
func (*SetSmartConfigRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_smart_proto_rawDescGZIP(), []int{2}
}

func (x *SetSmartConfigRequest) GetOpenaiApiKey() string {
	if x != nil {
		return x.OpenaiApiKey
	}
	return ""
}

func (x *SetSmartConfigRequest) GetClearApiKey() bool {
	if x != nil {
		return x.ClearApiKey
	}
	return false
}

func (x *SetSmartConfigRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type SetSmartConfigResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Config        *GetSmartConfigResponse `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSmartConfigResponse) Reset() {
	*x = SetSmartConfigResponse{}
	mi := &file_articleflux_v1_smart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSmartConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSmartConfigResponse) ProtoMessage() {}

func (x *SetSmartConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_smart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSmartConfigResponse.ProtoReflect.Descriptor instead.
func (*SetSmartConfigResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_smart_proto_rawDescGZIP(), []int{3}
}

func (x *SetSmartConfigResponse) GetConfig() *GetSmartConfigResponse {
	if x != nil {
		return x.Config
	}
	return nil
}

type ListLanguagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguagesRequest) Reset() {
	*x = ListLanguagesRequest{}
	mi := &file_articleflux_v1_smart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguagesRequest) ProtoMessage() {}

func (x *ListLanguagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_smart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguagesRequest.ProtoReflect.Descriptor instead.
func (*ListLanguagesRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_smart_proto_rawDescGZIP(), []int{4}
}

type ListLanguagesResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Languages []*SmartLanguage       `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	// The locale the catalog is authored in — always available, never translated,
	// never billed.
	SourceLocale  string `protobuf:"bytes,2,opt,name=source_locale,json=sourceLocale,proto3" json:"source_locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguagesResponse) Reset() {
	*x = ListLanguagesResponse{}
	mi := &file_articleflux_v1_smart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguagesResponse) ProtoMessage() {}

func (x *ListLanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_smart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguagesResponse.ProtoReflect.Descriptor instead.
func (*ListLanguagesResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_smart_proto_rawDescGZIP(), []int{5}
}

func (x *ListLanguagesResponse) GetLanguages() []*SmartLanguage {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *ListLanguagesResponse) GetSourceLocale() string {
	if x != nil {
		return x.SourceLocale
	}
	return ""
}

type SmartLanguage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// The language's name in English, and in itself. Both, because a picker with
	// only endonyms cannot be navigated by someone who chose the wrong one.
	EnglishName string `protobuf:"bytes,2,opt,name=english_name,json=englishName,proto3" json:"english_name,omitempty"`
	NativeName  string `protobuf:"bytes,3,opt,name=native_name,json=nativeName,proto3" json:"native_name,omitempty"`
	// Already translated for this build: selecting it costs nothing.
	Cached        bool `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmartLanguage) Reset() {
	*x = SmartLanguage{}
	mi := &file_articleflux_v1_smart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmartLanguage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartLanguage) ProtoMessage() {}

func (x *SmartLanguage) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_smart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartLanguage.ProtoReflect.Descriptor instead.
func (*SmartLanguage) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_smart_proto_rawDescGZIP(), []int{6}
}

func (x *SmartLanguage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SmartLanguage) GetEnglishName() string {
	if x != nil {
		return x.EnglishName
	}
	return ""
}

func (x *SmartLanguage) GetNativeName() string {
	if x != nil {
		return x.NativeName
	}
	return ""
}

func (x *SmartLanguage) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

type TranslateUIRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Locale string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	// Re-translate even if a cached catalog exists.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateUIRequest) Reset() {
	*x = TranslateUIRequest{}
	mi := &file_articleflux_v1_smart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateUIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateUIRequest) ProtoMessage() {}

func (x *TranslateUIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_smart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateUIRequest.ProtoReflect.Descriptor instead.
func (*TranslateUIRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_smart_proto_rawDescGZIP(), []int{7}
}

func (x *TranslateUIRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *TranslateUIRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type TranslateUIResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Locale   string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	Messages []*UIMessage           `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	// True when this came from cache, so the UI can say the switch was free.
	Cached        bool `protobuf:"varint,3,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateUIResponse) Reset() {
	*x = TranslateUIResponse{}
	mi := &file_articleflux_v1_smart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateUIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateUIResponse) ProtoMessage() {}

func (x *TranslateUIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_smart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateUIResponse.ProtoReflect.Descriptor instead.
func (*TranslateUIResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_smart_proto_rawDescGZIP(), []int{8}
}

func (x *TranslateUIResponse) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *TranslateUIResponse) GetMessages() []*UIMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *TranslateUIResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

// UIMessage is one entry of the catalog, in the flat "namespace.key" form the
// client's i18n.T takes.
type UIMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The message. Empty when this is a pluralised message, in which case forms
	// carries it instead.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Plural forms, keyed by CLDR category: zero, one, two, few, many, other.
	Forms         map[string]string `protobuf:"bytes,3,rep,name=forms,proto3" json:"forms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIMessage) Reset() {
	*x = UIMessage{}
	mi := &file_articleflux_v1_smart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIMessage) ProtoMessage() {}

func (x *UIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_smart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIMessage.ProtoReflect.Descriptor instead.
func (*UIMessage) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_smart_proto_rawDescGZIP(), []int{9}
}

func (x *UIMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UIMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UIMessage) GetForms() map[string]string {
	if x != nil {
		return x.Forms
	}
	return nil
}

var File_articleflux_v1_smart_proto protoreflect.FileDescriptor

const file_articleflux_v1_smart_proto_rawDesc = "" +
	"\n" +
	"\x1aarticleflux/v1/smart.proto\x12\x0earticleflux.v1\"\x17\n" +
	"\x15GetSmartConfigRequest\"\xc9\x02\n" +
	"\x16GetSmartConfigResponse\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\x19\n" +
	"\bkey_hint\x18\x02 \x01(\tR\akeyHint\x12*\n" +
	"\x11can_store_secrets\x18\x03 \x01(\bR\x0fcanStoreSecrets\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12#\n" +
	"\rdefault_model\x18\x05 \x01(\tR\fdefaultModel\x12!\n" +
	"\finput_tokens\x18\n" +
	" \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\v \x01(\x03R\foutputTokens\x12\x1a\n" +
	"\brequests\x18\f \x01(\x03R\brequests\x12)\n" +
	"\x10from_environment\x18\x14 \x01(\bR\x0ffromEnvironment\"w\n" +
	"\x15SetSmartConfigRequest\x12$\n" +
	"\x0eopenai_api_key\x18\x01 \x01(\tR\fopenaiApiKey\x12\"\n" +
	"\rclear_api_key\x18\x02 \x01(\bR\vclearApiKey\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"X\n" +
	"\x16SetSmartConfigResponse\x12>\n" +
	"\x06config\x18\x01 \x01(\v2&.articleflux.v1.GetSmartConfigResponseR\x06config\"\x16\n" +
	"\x14ListLanguagesRequest\"y\n" +
	"\x15ListLanguagesResponse\x12;\n" +
	"\tlanguages\x18\x01 \x03(\v2\x1d.articleflux.v1.SmartLanguageR\tlanguages\x12#\n" +
	"\rsource_locale\x18\x02 \x01(\tR\fsourceLocale\"\x7f\n" +
	"\rSmartLanguage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\fenglish_name\x18\x02 \x01(\tR\venglishName\x12\x1f\n" +
	"\vnative_name\x18\x03 \x01(\tR\n" +
	"nativeName\x12\x16\n" +
	"\x06cached\x18\x04 \x01(\bR\x06cached\"B\n" +
	"\x12TranslateUIRequest\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"|\n" +
	"\x13TranslateUIResponse\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\x125\n" +
	"\bmessages\x18\x02 \x03(\v2\x19.articleflux.v1.UIMessageR\bmessages\x12\x16\n" +
	"\x06cached\x18\x03 \x01(\bR\x06cached\"\xa7\x01\n" +
	"\tUIMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12:\n" +
	"\x05forms\x18\x03 \x03(\v2$.articleflux.v1.UIMessage.FormsEntryR\x05forms\x1a8\n" +
	"\n" +
	"FormsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x86\x03\n" +
	"\fSmartService\x12_\n" +
	"\x0eGetSmartConfig\x12%.articleflux.v1.GetSmartConfigRequest\x1a&.articleflux.v1.GetSmartConfigResponse\x12_\n" +
	"\x0eSetSmartConfig\x12%.articleflux.v1.SetSmartConfigRequest\x1a&.articleflux.v1.SetSmartConfigResponse\x12\\\n" +
	"\rListLanguages\x12$.articleflux.v1.ListLanguagesRequest\x1a%.articleflux.v1.ListLanguagesResponse\x12V\n" +
	"\vTranslateUI\x12\".articleflux.v1.TranslateUIRequest\x1a#.articleflux.v1.TranslateUIResponseBPZNgithub.com/monstercameron/ArticleFlux/internal/pb/articleflux/v1;articlefluxv1b\x06proto3"

var (
	file_articleflux_v1_smart_proto_rawDescOnce sync.Once
	file_articleflux_v1_smart_proto_rawDescData []byte
)

func file_articleflux_v1_smart_proto_rawDescGZIP() []byte {
	file_articleflux_v1_smart_proto_rawDescOnce.Do(func() {
		file_articleflux_v1_smart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_articleflux_v1_smart_proto_rawDesc), len(file_articleflux_v1_smart_proto_rawDesc)))
	})
	return file_articleflux_v1_smart_proto_rawDescData
}

var file_articleflux_v1_smart_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_articleflux_v1_smart_proto_goTypes = []any{
	(*GetSmartConfigRequest)(nil),  // 0: articleflux.v1.GetSmartConfigRequest
	(*GetSmartConfigResponse)(nil), // 1: articleflux.v1.GetSmartConfigResponse
	(*SetSmartConfigRequest)(nil),  // 2: articleflux.v1.SetSmartConfigRequest
	(*SetSmartConfigResponse)(nil), // 3: articleflux.v1.SetSmartConfigResponse
	(*ListLanguagesRequest)(nil),   // 4: articleflux.v1.ListLanguagesRequest
	(*ListLanguagesResponse)(nil),  // 5: articleflux.v1.ListLanguagesResponse
	(*SmartLanguage)(nil),          // 6: articleflux.v1.SmartLanguage
	(*TranslateUIRequest)(nil),     // 7: articleflux.v1.TranslateUIRequest
	(*TranslateUIResponse)(nil),    // 8: articleflux.v1.TranslateUIResponse
	(*UIMessage)(nil),              // 9: articleflux.v1.UIMessage
	nil,                            // 10: articleflux.v1.UIMessage.FormsEntry
}
var file_articleflux_v1_smart_proto_depIdxs = []int32{
	1,  // 0: articleflux.v1.SetSmartConfigResponse.config:type_name -> articleflux.v1.GetSmartConfigResponse
	6,  // 1: articleflux.v1.ListLanguagesResponse.languages:type_name -> articleflux.v1.SmartLanguage
	9,  // 2: articleflux.v1.TranslateUIResponse.messages:type_name -> articleflux.v1.UIMessage
	10, // 3: articleflux.v1.UIMessage.forms:type_name -> articleflux.v1.UIMessage.FormsEntry
	0,  // 4: articleflux.v1.SmartService.GetSmartConfig:input_type -> articleflux.v1.GetSmartConfigRequest
	2,  // 5: articleflux.v1.SmartService.SetSmartConfig:input_type -> articleflux.v1.SetSmartConfigRequest
	4,  // 6: articleflux.v1.SmartService.ListLanguages:input_type -> articleflux.v1.ListLanguagesRequest
	7,  // 7: articleflux.v1.SmartService.TranslateUI:input_type -> articleflux.v1.TranslateUIRequest
	1,  // 8: articleflux.v1.SmartService.GetSmartConfig:output_type -> articleflux.v1.GetSmartConfigResponse
	3,  // 9: articleflux.v1.SmartService.SetSmartConfig:output_type -> articleflux.v1.SetSmartConfigResponse
	5,  // 10: articleflux.v1.SmartService.ListLanguages:output_type -> articleflux.v1.ListLanguagesResponse
	8,  // 11: articleflux.v1.SmartService.TranslateUI:output_type -> articleflux.v1.TranslateUIResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_articleflux_v1_smart_proto_init() }
func file_articleflux_v1_smart_proto_init() {
	if File_articleflux_v1_smart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_articleflux_v1_smart_proto_rawDesc), len(file_articleflux_v1_smart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_articleflux_v1_smart_proto_goTypes,
		DependencyIndexes: file_articleflux_v1_smart_proto_depIdxs,
		MessageInfos:      file_articleflux_v1_smart_proto_msgTypes,
	}.Build()
	File_articleflux_v1_smart_proto = out.File
	file_articleflux_v1_smart_proto_goTypes = nil
	file_articleflux_v1_smart_proto_depIdxs = nil
}
