// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: articleflux/v1/smart.proto

package articlefluxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmartService_GetSmartConfig_FullMethodName = "/articleflux.v1.SmartService/GetSmartConfig"
	SmartService_SetSmartConfig_FullMethodName = "/articleflux.v1.SmartService/SetSmartConfig"
	SmartService_ListLanguages_FullMethodName  = "/articleflux.v1.SmartService/ListLanguages"
	SmartService_TranslateUI_FullMethodName    = "/articleflux.v1.SmartService/TranslateUI"
)

// SmartServiceClient is the client API for SmartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SmartService is the Smart+ tier's control surface: the one API key every
// Smart+ feature spends, and the features that are configuration rather than
// per-article actions.
//
// It is a separate service from ReaderService on purpose. Everything here
// EGRESSES — it sends the reader's content, or the server's configuration, to a
// third party — and keeping that on its own service means the capability map
// (§7) can gate the whole surface with one entry rather than remembering to
// mark individual reader RPCs.
//
// **Every RPC here is owner-only.** The API key is instance configuration, and
// a translation is a spend against the instance's bill.
type SmartServiceClient interface {
	// GetSmartConfig reports whether Smart+ can run at all, and what it has spent.
	//
	// It NEVER returns the API key. `key_hint` is the last four characters, which
	// is enough to answer "is that the key I pasted" and useless to anyone who
	// intercepts it.
	GetSmartConfig(ctx context.Context, in *GetSmartConfigRequest, opts ...grpc.CallOption) (*GetSmartConfigResponse, error)
	// SetSmartConfig stores the OpenAI API key and the model.
	//
	// The key is encrypted at rest. An empty `openai_api_key` with
	// `clear_api_key` set removes it, which is how an instance is switched back
	// to being unable to egress at all.
	SetSmartConfig(ctx context.Context, in *SetSmartConfigRequest, opts ...grpc.CallOption) (*SetSmartConfigResponse, error)
	// ListLanguages returns the offered UI translation targets and which of them
	// are already cached for the running build's English.
	ListLanguages(ctx context.Context, in *ListLanguagesRequest, opts ...grpc.CallOption) (*ListLanguagesResponse, error)
	// TranslateUI returns the whole UI catalog in one language.
	//
	// Cached per locale against a hash of the English catalog, so a build that
	// changes a string re-translates and one that does not is free. `force`
	// bypasses the cache — the only lever a reader has when a translation came
	// back wrong.
	TranslateUI(ctx context.Context, in *TranslateUIRequest, opts ...grpc.CallOption) (*TranslateUIResponse, error)
}

type smartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartServiceClient(cc grpc.ClientConnInterface) SmartServiceClient {
	return &smartServiceClient{cc}
}

func (c *smartServiceClient) GetSmartConfig(ctx context.Context, in *GetSmartConfigRequest, opts ...grpc.CallOption) (*GetSmartConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSmartConfigResponse)
	err := c.cc.Invoke(ctx, SmartService_GetSmartConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartServiceClient) SetSmartConfig(ctx context.Context, in *SetSmartConfigRequest, opts ...grpc.CallOption) (*SetSmartConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSmartConfigResponse)
	err := c.cc.Invoke(ctx, SmartService_SetSmartConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartServiceClient) ListLanguages(ctx context.Context, in *ListLanguagesRequest, opts ...grpc.CallOption) (*ListLanguagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLanguagesResponse)
	err := c.cc.Invoke(ctx, SmartService_ListLanguages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartServiceClient) TranslateUI(ctx context.Context, in *TranslateUIRequest, opts ...grpc.CallOption) (*TranslateUIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslateUIResponse)
	err := c.cc.Invoke(ctx, SmartService_TranslateUI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartServiceServer is the server API for SmartService service.
// All implementations must embed UnimplementedSmartServiceServer
// for forward compatibility.
//
// SmartService is the Smart+ tier's control surface: the one API key every
// Smart+ feature spends, and the features that are configuration rather than
// per-article actions.
//
// It is a separate service from ReaderService on purpose. Everything here
// EGRESSES — it sends the reader's content, or the server's configuration, to a
// third party — and keeping that on its own service means the capability map
// (§7) can gate the whole surface with one entry rather than remembering to
// mark individual reader RPCs.
//
// **Every RPC here is owner-only.** The API key is instance configuration, and
// a translation is a spend against the instance's bill.
type SmartServiceServer interface {
	// GetSmartConfig reports whether Smart+ can run at all, and what it has spent.
	//
	// It NEVER returns the API key. `key_hint` is the last four characters, which
	// is enough to answer "is that the key I pasted" and useless to anyone who
	// intercepts it.
	GetSmartConfig(context.Context, *GetSmartConfigRequest) (*GetSmartConfigResponse, error)
	// SetSmartConfig stores the OpenAI API key and the model.
	//
	// The key is encrypted at rest. An empty `openai_api_key` with
	// `clear_api_key` set removes it, which is how an instance is switched back
	// to being unable to egress at all.
	SetSmartConfig(context.Context, *SetSmartConfigRequest) (*SetSmartConfigResponse, error)
	// ListLanguages returns the offered UI translation targets and which of them
	// are already cached for the running build's English.
	ListLanguages(context.Context, *ListLanguagesRequest) (*ListLanguagesResponse, error)
	// TranslateUI returns the whole UI catalog in one language.
	//
	// Cached per locale against a hash of the English catalog, so a build that
	// changes a string re-translates and one that does not is free. `force`
	// bypasses the cache — the only lever a reader has when a translation came
	// back wrong.
	TranslateUI(context.Context, *TranslateUIRequest) (*TranslateUIResponse, error)
	mustEmbedUnimplementedSmartServiceServer()
}

// UnimplementedSmartServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmartServiceServer struct{}

func (UnimplementedSmartServiceServer) GetSmartConfig(context.Context, *GetSmartConfigRequest) (*GetSmartConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSmartConfig not implemented")
}
func (UnimplementedSmartServiceServer) SetSmartConfig(context.Context, *SetSmartConfigRequest) (*SetSmartConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSmartConfig not implemented")
}
func (UnimplementedSmartServiceServer) ListLanguages(context.Context, *ListLanguagesRequest) (*ListLanguagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLanguages not implemented")
}
func (UnimplementedSmartServiceServer) TranslateUI(context.Context, *TranslateUIRequest) (*TranslateUIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TranslateUI not implemented")
}
func (UnimplementedSmartServiceServer) mustEmbedUnimplementedSmartServiceServer() {}
func (UnimplementedSmartServiceServer) testEmbeddedByValue()                      {}

// UnsafeSmartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartServiceServer will
// result in compilation errors.
type UnsafeSmartServiceServer interface {
	mustEmbedUnimplementedSmartServiceServer()
}

func RegisterSmartServiceServer(s grpc.ServiceRegistrar, srv SmartServiceServer) {
	// If the following call pancis, it indicates UnimplementedSmartServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmartService_ServiceDesc, srv)
}

func _SmartService_GetSmartConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSmartConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartServiceServer).GetSmartConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartService_GetSmartConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartServiceServer).GetSmartConfig(ctx, req.(*GetSmartConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartService_SetSmartConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSmartConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartServiceServer).SetSmartConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartService_SetSmartConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartServiceServer).SetSmartConfig(ctx, req.(*SetSmartConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartService_ListLanguages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartServiceServer).ListLanguages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartService_ListLanguages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartServiceServer).ListLanguages(ctx, req.(*ListLanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartService_TranslateUI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateUIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartServiceServer).TranslateUI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartService_TranslateUI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartServiceServer).TranslateUI(ctx, req.(*TranslateUIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartService_ServiceDesc is the grpc.ServiceDesc for SmartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "articleflux.v1.SmartService",
	HandlerType: (*SmartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSmartConfig",
			Handler:    _SmartService_GetSmartConfig_Handler,
		},
		{
			MethodName: "SetSmartConfig",
			Handler:    _SmartService_SetSmartConfig_Handler,
		},
		{
			MethodName: "ListLanguages",
			Handler:    _SmartService_ListLanguages_Handler,
		},
		{
			MethodName: "TranslateUI",
			Handler:    _SmartService_TranslateUI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "articleflux/v1/smart.proto",
}
