// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: articleflux/v1/system.proto

// Package articleflux.v1 is the single contract behind all three transports (§20.7):
// the gRPC tunnel, the plain-HTTPS pack channel, and the Google Reader-compatible
// REST sync API. Additive changes only within v1 — `buf breaking` in CI enforces
// that rather than discipline, because the sync API and SW-cached wasm both
// guarantee old clients in the wild (§22.10).

package articlefluxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServingStatus int32

const (
	ServingStatus_SERVING_STATUS_UNSPECIFIED ServingStatus = 0
	// Reads and writes both available.
	ServingStatus_SERVING_STATUS_SERVING ServingStatus = 1
	// Reads available, writes refused — storage read-only, or a migration running.
	ServingStatus_SERVING_STATUS_DEGRADED ServingStatus = 2
	// Not ready to serve. Distinct from unreachable, which the client sees as a
	// transport error instead.
	ServingStatus_SERVING_STATUS_NOT_SERVING ServingStatus = 3
)

// Enum value maps for ServingStatus.
var (
	ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_DEGRADED",
		3: "SERVING_STATUS_NOT_SERVING",
	}
	ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING_STATUS_SERVING":     1,
		"SERVING_STATUS_DEGRADED":    2,
		"SERVING_STATUS_NOT_SERVING": 3,
	}
)

func (x ServingStatus) Enum() *ServingStatus {
	p := new(ServingStatus)
	*p = x
	return p
}

func (x ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_articleflux_v1_system_proto_enumTypes[0].Descriptor()
}

func (ServingStatus) Type() protoreflect.EnumType {
	return &file_articleflux_v1_system_proto_enumTypes[0]
}

func (x ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServingStatus.Descriptor instead.
func (ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{0}
}

type GetServerStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStatsRequest) Reset() {
	*x = GetServerStatsRequest{}
	mi := &file_articleflux_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatsRequest) ProtoMessage() {}

func (x *GetServerStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatsRequest.ProtoReflect.Descriptor instead.
func (*GetServerStatsRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{0}
}

type GetServerStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	SchemaVersion int64                  `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Seconds since the process started.
	UptimeS   int64  `protobuf:"varint,4,opt,name=uptime_s,json=uptimeS,proto3" json:"uptime_s,omitempty"`
	StartedAt string `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Storage.
	DbBytes  int64  `protobuf:"varint,10,opt,name=db_bytes,json=dbBytes,proto3" json:"db_bytes,omitempty"`
	WalBytes int64  `protobuf:"varint,11,opt,name=wal_bytes,json=walBytes,proto3" json:"wal_bytes,omitempty"`
	DbPath   string `protobuf:"bytes,12,opt,name=db_path,json=dbPath,proto3" json:"db_path,omitempty"`
	// How much of everything there is. Scoped to the caller, not global.
	Feeds  int32 `protobuf:"varint,20,opt,name=feeds,proto3" json:"feeds,omitempty"`
	Items  int32 `protobuf:"varint,21,opt,name=items,proto3" json:"items,omitempty"`
	Unread int32 `protobuf:"varint,22,opt,name=unread,proto3" json:"unread,omitempty"`
	Notes  int32 `protobuf:"varint,23,opt,name=notes,proto3" json:"notes,omitempty"`
	Tags   int32 `protobuf:"varint,24,opt,name=tags,proto3" json:"tags,omitempty"`
	Rated  int32 `protobuf:"varint,25,opt,name=rated,proto3" json:"rated,omitempty"`
	Saved  int32 `protobuf:"varint,26,opt,name=saved,proto3" json:"saved,omitempty"` // read later
	// Runtime. Go's own numbers, because "is it the reader or is it my box" is the
	// first question and a heap figure answers it.
	HeapBytes  int64 `protobuf:"varint,30,opt,name=heap_bytes,json=heapBytes,proto3" json:"heap_bytes,omitempty"`
	Goroutines int32 `protobuf:"varint,31,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	GcCycles   int32 `protobuf:"varint,32,opt,name=gc_cycles,json=gcCycles,proto3" json:"gc_cycles,omitempty"`
	// Polling.
	LastPollAt    string        `protobuf:"bytes,40,opt,name=last_poll_at,json=lastPollAt,proto3" json:"last_poll_at,omitempty"`
	PollIntervalS int32         `protobuf:"varint,41,opt,name=poll_interval_s,json=pollIntervalS,proto3" json:"poll_interval_s,omitempty"`
	DormantFeeds  int32         `protobuf:"varint,42,opt,name=dormant_feeds,json=dormantFeeds,proto3" json:"dormant_feeds,omitempty"`
	Methods       []*MethodStat `protobuf:"bytes,50,rep,name=methods,proto3" json:"methods,omitempty"`
	LogCounts     []*LevelCount `protobuf:"bytes,51,rep,name=log_counts,json=logCounts,proto3" json:"log_counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerStatsResponse) Reset() {
	*x = GetServerStatsResponse{}
	mi := &file_articleflux_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatsResponse) ProtoMessage() {}

func (x *GetServerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatsResponse.ProtoReflect.Descriptor instead.
func (*GetServerStatsResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerStatsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetServerStatsResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GetServerStatsResponse) GetSchemaVersion() int64 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *GetServerStatsResponse) GetUptimeS() int64 {
	if x != nil {
		return x.UptimeS
	}
	return 0
}

func (x *GetServerStatsResponse) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *GetServerStatsResponse) GetDbBytes() int64 {
	if x != nil {
		return x.DbBytes
	}
	return 0
}

func (x *GetServerStatsResponse) GetWalBytes() int64 {
	if x != nil {
		return x.WalBytes
	}
	return 0
}

func (x *GetServerStatsResponse) GetDbPath() string {
	if x != nil {
		return x.DbPath
	}
	return ""
}

func (x *GetServerStatsResponse) GetFeeds() int32 {
	if x != nil {
		return x.Feeds
	}
	return 0
}

func (x *GetServerStatsResponse) GetItems() int32 {
	if x != nil {
		return x.Items
	}
	return 0
}

func (x *GetServerStatsResponse) GetUnread() int32 {
	if x != nil {
		return x.Unread
	}
	return 0
}

func (x *GetServerStatsResponse) GetNotes() int32 {
	if x != nil {
		return x.Notes
	}
	return 0
}

func (x *GetServerStatsResponse) GetTags() int32 {
	if x != nil {
		return x.Tags
	}
	return 0
}

func (x *GetServerStatsResponse) GetRated() int32 {
	if x != nil {
		return x.Rated
	}
	return 0
}

func (x *GetServerStatsResponse) GetSaved() int32 {
	if x != nil {
		return x.Saved
	}
	return 0
}

func (x *GetServerStatsResponse) GetHeapBytes() int64 {
	if x != nil {
		return x.HeapBytes
	}
	return 0
}

func (x *GetServerStatsResponse) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *GetServerStatsResponse) GetGcCycles() int32 {
	if x != nil {
		return x.GcCycles
	}
	return 0
}

func (x *GetServerStatsResponse) GetLastPollAt() string {
	if x != nil {
		return x.LastPollAt
	}
	return ""
}

func (x *GetServerStatsResponse) GetPollIntervalS() int32 {
	if x != nil {
		return x.PollIntervalS
	}
	return 0
}

func (x *GetServerStatsResponse) GetDormantFeeds() int32 {
	if x != nil {
		return x.DormantFeeds
	}
	return 0
}

func (x *GetServerStatsResponse) GetMethods() []*MethodStat {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *GetServerStatsResponse) GetLogCounts() []*LevelCount {
	if x != nil {
		return x.LogCounts
	}
	return nil
}

// MethodStat is one row of the latency table. Durations are milliseconds:
// microsecond precision on a screen a person reads is noise.
type MethodStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Calls         int64                  `protobuf:"varint,2,opt,name=calls,proto3" json:"calls,omitempty"`
	Errors        int64                  `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	P50Ms         float64                `protobuf:"fixed64,4,opt,name=p50_ms,json=p50Ms,proto3" json:"p50_ms,omitempty"`
	P95Ms         float64                `protobuf:"fixed64,5,opt,name=p95_ms,json=p95Ms,proto3" json:"p95_ms,omitempty"`
	MaxMs         float64                `protobuf:"fixed64,6,opt,name=max_ms,json=maxMs,proto3" json:"max_ms,omitempty"`
	MeanMs        float64                `protobuf:"fixed64,7,opt,name=mean_ms,json=meanMs,proto3" json:"mean_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodStat) Reset() {
	*x = MethodStat{}
	mi := &file_articleflux_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodStat) ProtoMessage() {}

func (x *MethodStat) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodStat.ProtoReflect.Descriptor instead.
func (*MethodStat) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{2}
}

func (x *MethodStat) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MethodStat) GetCalls() int64 {
	if x != nil {
		return x.Calls
	}
	return 0
}

func (x *MethodStat) GetErrors() int64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *MethodStat) GetP50Ms() float64 {
	if x != nil {
		return x.P50Ms
	}
	return 0
}

func (x *MethodStat) GetP95Ms() float64 {
	if x != nil {
		return x.P95Ms
	}
	return 0
}

func (x *MethodStat) GetMaxMs() float64 {
	if x != nil {
		return x.MaxMs
	}
	return 0
}

func (x *MethodStat) GetMeanMs() float64 {
	if x != nil {
		return x.MeanMs
	}
	return 0
}

type LevelCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelCount) Reset() {
	*x = LevelCount{}
	mi := &file_articleflux_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelCount) ProtoMessage() {}

func (x *LevelCount) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelCount.ProtoReflect.Descriptor instead.
func (*LevelCount) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{3}
}

func (x *LevelCount) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LevelCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Limit int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Minimum level: DEBUG | INFO | WARN | ERROR. Empty means INFO.
	MinLevel      string `protobuf:"bytes,2,opt,name=min_level,json=minLevel,proto3" json:"min_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogsRequest) Reset() {
	*x = ListLogsRequest{}
	mi := &file_articleflux_v1_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogsRequest) ProtoMessage() {}

func (x *ListLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogsRequest.ProtoReflect.Descriptor instead.
func (*ListLogsRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{4}
}

func (x *ListLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListLogsRequest) GetMinLevel() string {
	if x != nil {
		return x.MinLevel
	}
	return ""
}

type ListLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*LogRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogsResponse) Reset() {
	*x = ListLogsResponse{}
	mi := &file_articleflux_v1_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogsResponse) ProtoMessage() {}

func (x *ListLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogsResponse.ProtoReflect.Descriptor instead.
func (*ListLogsResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{5}
}

func (x *ListLogsResponse) GetRecords() []*LogRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type LogRecord struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Time    string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Level   string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Attributes pre-rendered as `key=value` pairs. The consumer is a settings
	// screen, not a query engine.
	Attrs         string `protobuf:"bytes,4,opt,name=attrs,proto3" json:"attrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_articleflux_v1_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{6}
}

func (x *LogRecord) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *LogRecord) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRecord) GetAttrs() string {
	if x != nil {
		return x.Attrs
	}
	return ""
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_articleflux_v1_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{7}
}

type GetVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Semantic version of the server build.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Git commit the binary was built from, or "unknown" for a local build.
	Commit string `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	// Highest applied migration. The client compares this across reconnects to
	// detect that it is talking to a different schema than it started on.
	SchemaVersion int64 `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_articleflux_v1_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{8}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GetVersionResponse) GetSchemaVersion() int64 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_articleflux_v1_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{9}
}

type CheckHealthResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status ServingStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=articleflux.v1.ServingStatus" json:"status,omitempty"`
	// Human-readable and always safe to display (§20.7): internal detail goes to
	// the log with the request id, never to the client.
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResponse) Reset() {
	*x = CheckHealthResponse{}
	mi := &file_articleflux_v1_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResponse) ProtoMessage() {}

func (x *CheckHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{10}
}

func (x *CheckHealthResponse) GetStatus() ServingStatus {
	if x != nil {
		return x.Status
	}
	return ServingStatus_SERVING_STATUS_UNSPECIFIED
}

func (x *CheckHealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ListAudioTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAudioTracksRequest) Reset() {
	*x = ListAudioTracksRequest{}
	mi := &file_articleflux_v1_system_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAudioTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAudioTracksRequest) ProtoMessage() {}

func (x *ListAudioTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAudioTracksRequest.ProtoReflect.Descriptor instead.
func (*ListAudioTracksRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{11}
}

// AudioTrack is one bed, as the settings picker needs it.
type AudioTrack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable slug, and the only thing GetAudioTrack accepts. It is matched against
	// a fixed set on the server rather than joined onto a path, so it cannot name
	// a file outside the audio directory.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The track's name, as its author wrote it. A proper noun: not translated.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// How big it is. The client shows nothing with this today; it is here because
	// "the reader is about to pull four megabytes through the tunnel" is a fact
	// the UI will eventually want to state, and adding it later is a wire change.
	Bytes int64 `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// What the track is FOR: "bed" for the low music under the whole broadcast,
	// "sting" for the louder piece that opens it.
	//
	// The server owns this rather than the client, for the same reason it owns the
	// catalogue: which piece works under speech and which one works as an opening
	// is a property of the recording, and a client deciding it by filename would
	// be a client that guesses wrong the day somebody adds a fifth file.
	//
	// A role the client does not recognise is treated as a bed, which is the
	// quieter of the two mistakes.
	Role          string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioTrack) Reset() {
	*x = AudioTrack{}
	mi := &file_articleflux_v1_system_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioTrack) ProtoMessage() {}

func (x *AudioTrack) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioTrack.ProtoReflect.Descriptor instead.
func (*AudioTrack) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{12}
}

func (x *AudioTrack) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AudioTrack) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AudioTrack) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *AudioTrack) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ListAudioTracksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*AudioTrack          `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAudioTracksResponse) Reset() {
	*x = ListAudioTracksResponse{}
	mi := &file_articleflux_v1_system_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAudioTracksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAudioTracksResponse) ProtoMessage() {}

func (x *ListAudioTracksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAudioTracksResponse.ProtoReflect.Descriptor instead.
func (*ListAudioTracksResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{13}
}

func (x *ListAudioTracksResponse) GetTracks() []*AudioTrack {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type GetAudioTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAudioTrackRequest) Reset() {
	*x = GetAudioTrackRequest{}
	mi := &file_articleflux_v1_system_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAudioTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAudioTrackRequest) ProtoMessage() {}

func (x *GetAudioTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAudioTrackRequest.ProtoReflect.Descriptor instead.
func (*GetAudioTrackRequest) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{14}
}

func (x *GetAudioTrackRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetAudioTrackResponse is a slice of one track, in order.
//
// A bare bytes field with no offset or index: gRPC delivers a server stream in
// order, so a sequence number would be a second source of truth for something
// the transport already guarantees — and one that could disagree with it.
type GetAudioTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAudioTrackResponse) Reset() {
	*x = GetAudioTrackResponse{}
	mi := &file_articleflux_v1_system_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAudioTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAudioTrackResponse) ProtoMessage() {}

func (x *GetAudioTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleflux_v1_system_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAudioTrackResponse.ProtoReflect.Descriptor instead.
func (*GetAudioTrackResponse) Descriptor() ([]byte, []int) {
	return file_articleflux_v1_system_proto_rawDescGZIP(), []int{15}
}

func (x *GetAudioTrackResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_articleflux_v1_system_proto protoreflect.FileDescriptor

const file_articleflux_v1_system_proto_rawDesc = "" +
	"\n" +
	"\x1barticleflux/v1/system.proto\x12\x0earticleflux.v1\"\x17\n" +
	"\x15GetServerStatsRequest\"\xd2\x05\n" +
	"\x16GetServerStatsResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\x03R\rschemaVersion\x12\x19\n" +
	"\buptime_s\x18\x04 \x01(\x03R\auptimeS\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x19\n" +
	"\bdb_bytes\x18\n" +
	" \x01(\x03R\adbBytes\x12\x1b\n" +
	"\twal_bytes\x18\v \x01(\x03R\bwalBytes\x12\x17\n" +
	"\adb_path\x18\f \x01(\tR\x06dbPath\x12\x14\n" +
	"\x05feeds\x18\x14 \x01(\x05R\x05feeds\x12\x14\n" +
	"\x05items\x18\x15 \x01(\x05R\x05items\x12\x16\n" +
	"\x06unread\x18\x16 \x01(\x05R\x06unread\x12\x14\n" +
	"\x05notes\x18\x17 \x01(\x05R\x05notes\x12\x12\n" +
	"\x04tags\x18\x18 \x01(\x05R\x04tags\x12\x14\n" +
	"\x05rated\x18\x19 \x01(\x05R\x05rated\x12\x14\n" +
	"\x05saved\x18\x1a \x01(\x05R\x05saved\x12\x1d\n" +
	"\n" +
	"heap_bytes\x18\x1e \x01(\x03R\theapBytes\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x1f \x01(\x05R\n" +
	"goroutines\x12\x1b\n" +
	"\tgc_cycles\x18  \x01(\x05R\bgcCycles\x12 \n" +
	"\flast_poll_at\x18( \x01(\tR\n" +
	"lastPollAt\x12&\n" +
	"\x0fpoll_interval_s\x18) \x01(\x05R\rpollIntervalS\x12#\n" +
	"\rdormant_feeds\x18* \x01(\x05R\fdormantFeeds\x124\n" +
	"\amethods\x182 \x03(\v2\x1a.articleflux.v1.MethodStatR\amethods\x129\n" +
	"\n" +
	"log_counts\x183 \x03(\v2\x1a.articleflux.v1.LevelCountR\tlogCounts\"\xb0\x01\n" +
	"\n" +
	"MethodStat\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x14\n" +
	"\x05calls\x18\x02 \x01(\x03R\x05calls\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\x03R\x06errors\x12\x15\n" +
	"\x06p50_ms\x18\x04 \x01(\x01R\x05p50Ms\x12\x15\n" +
	"\x06p95_ms\x18\x05 \x01(\x01R\x05p95Ms\x12\x15\n" +
	"\x06max_ms\x18\x06 \x01(\x01R\x05maxMs\x12\x17\n" +
	"\amean_ms\x18\a \x01(\x01R\x06meanMs\"8\n" +
	"\n" +
	"LevelCount\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"D\n" +
	"\x0fListLogsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tmin_level\x18\x02 \x01(\tR\bminLevel\"G\n" +
	"\x10ListLogsResponse\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.articleflux.v1.LogRecordR\arecords\"e\n" +
	"\tLogRecord\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05attrs\x18\x04 \x01(\tR\x05attrs\"\x13\n" +
	"\x11GetVersionRequest\"m\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\x03R\rschemaVersion\"\x14\n" +
	"\x12CheckHealthRequest\"d\n" +
	"\x13CheckHealthResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.articleflux.v1.ServingStatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x18\n" +
	"\x16ListAudioTracksRequest\"\\\n" +
	"\n" +
	"AudioTrack\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x03R\x05bytes\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"M\n" +
	"\x17ListAudioTracksResponse\x122\n" +
	"\x06tracks\x18\x01 \x03(\v2\x1a.articleflux.v1.AudioTrackR\x06tracks\"&\n" +
	"\x14GetAudioTrackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x15GetAudioTrackResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*\x88\x01\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1b\n" +
	"\x17SERVING_STATUS_DEGRADED\x10\x02\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x032\xb0\x04\n" +
	"\rSystemService\x12S\n" +
	"\n" +
	"GetVersion\x12!.articleflux.v1.GetVersionRequest\x1a\".articleflux.v1.GetVersionResponse\x12V\n" +
	"\vCheckHealth\x12\".articleflux.v1.CheckHealthRequest\x1a#.articleflux.v1.CheckHealthResponse\x12_\n" +
	"\x0eGetServerStats\x12%.articleflux.v1.GetServerStatsRequest\x1a&.articleflux.v1.GetServerStatsResponse\x12M\n" +
	"\bListLogs\x12\x1f.articleflux.v1.ListLogsRequest\x1a .articleflux.v1.ListLogsResponse\x12b\n" +
	"\x0fListAudioTracks\x12&.articleflux.v1.ListAudioTracksRequest\x1a'.articleflux.v1.ListAudioTracksResponse\x12^\n" +
	"\rGetAudioTrack\x12$.articleflux.v1.GetAudioTrackRequest\x1a%.articleflux.v1.GetAudioTrackResponse0\x01BPZNgithub.com/monstercameron/ArticleFlux/internal/pb/articleflux/v1;articlefluxv1b\x06proto3"

var (
	file_articleflux_v1_system_proto_rawDescOnce sync.Once
	file_articleflux_v1_system_proto_rawDescData []byte
)

func file_articleflux_v1_system_proto_rawDescGZIP() []byte {
	file_articleflux_v1_system_proto_rawDescOnce.Do(func() {
		file_articleflux_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_articleflux_v1_system_proto_rawDesc), len(file_articleflux_v1_system_proto_rawDesc)))
	})
	return file_articleflux_v1_system_proto_rawDescData
}

var file_articleflux_v1_system_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_articleflux_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_articleflux_v1_system_proto_goTypes = []any{
	(ServingStatus)(0),              // 0: articleflux.v1.ServingStatus
	(*GetServerStatsRequest)(nil),   // 1: articleflux.v1.GetServerStatsRequest
	(*GetServerStatsResponse)(nil),  // 2: articleflux.v1.GetServerStatsResponse
	(*MethodStat)(nil),              // 3: articleflux.v1.MethodStat
	(*LevelCount)(nil),              // 4: articleflux.v1.LevelCount
	(*ListLogsRequest)(nil),         // 5: articleflux.v1.ListLogsRequest
	(*ListLogsResponse)(nil),        // 6: articleflux.v1.ListLogsResponse
	(*LogRecord)(nil),               // 7: articleflux.v1.LogRecord
	(*GetVersionRequest)(nil),       // 8: articleflux.v1.GetVersionRequest
	(*GetVersionResponse)(nil),      // 9: articleflux.v1.GetVersionResponse
	(*CheckHealthRequest)(nil),      // 10: articleflux.v1.CheckHealthRequest
	(*CheckHealthResponse)(nil),     // 11: articleflux.v1.CheckHealthResponse
	(*ListAudioTracksRequest)(nil),  // 12: articleflux.v1.ListAudioTracksRequest
	(*AudioTrack)(nil),              // 13: articleflux.v1.AudioTrack
	(*ListAudioTracksResponse)(nil), // 14: articleflux.v1.ListAudioTracksResponse
	(*GetAudioTrackRequest)(nil),    // 15: articleflux.v1.GetAudioTrackRequest
	(*GetAudioTrackResponse)(nil),   // 16: articleflux.v1.GetAudioTrackResponse
}
var file_articleflux_v1_system_proto_depIdxs = []int32{
	3,  // 0: articleflux.v1.GetServerStatsResponse.methods:type_name -> articleflux.v1.MethodStat
	4,  // 1: articleflux.v1.GetServerStatsResponse.log_counts:type_name -> articleflux.v1.LevelCount
	7,  // 2: articleflux.v1.ListLogsResponse.records:type_name -> articleflux.v1.LogRecord
	0,  // 3: articleflux.v1.CheckHealthResponse.status:type_name -> articleflux.v1.ServingStatus
	13, // 4: articleflux.v1.ListAudioTracksResponse.tracks:type_name -> articleflux.v1.AudioTrack
	8,  // 5: articleflux.v1.SystemService.GetVersion:input_type -> articleflux.v1.GetVersionRequest
	10, // 6: articleflux.v1.SystemService.CheckHealth:input_type -> articleflux.v1.CheckHealthRequest
	1,  // 7: articleflux.v1.SystemService.GetServerStats:input_type -> articleflux.v1.GetServerStatsRequest
	5,  // 8: articleflux.v1.SystemService.ListLogs:input_type -> articleflux.v1.ListLogsRequest
	12, // 9: articleflux.v1.SystemService.ListAudioTracks:input_type -> articleflux.v1.ListAudioTracksRequest
	15, // 10: articleflux.v1.SystemService.GetAudioTrack:input_type -> articleflux.v1.GetAudioTrackRequest
	9,  // 11: articleflux.v1.SystemService.GetVersion:output_type -> articleflux.v1.GetVersionResponse
	11, // 12: articleflux.v1.SystemService.CheckHealth:output_type -> articleflux.v1.CheckHealthResponse
	2,  // 13: articleflux.v1.SystemService.GetServerStats:output_type -> articleflux.v1.GetServerStatsResponse
	6,  // 14: articleflux.v1.SystemService.ListLogs:output_type -> articleflux.v1.ListLogsResponse
	14, // 15: articleflux.v1.SystemService.ListAudioTracks:output_type -> articleflux.v1.ListAudioTracksResponse
	16, // 16: articleflux.v1.SystemService.GetAudioTrack:output_type -> articleflux.v1.GetAudioTrackResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_articleflux_v1_system_proto_init() }
func file_articleflux_v1_system_proto_init() {
	if File_articleflux_v1_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_articleflux_v1_system_proto_rawDesc), len(file_articleflux_v1_system_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_articleflux_v1_system_proto_goTypes,
		DependencyIndexes: file_articleflux_v1_system_proto_depIdxs,
		EnumInfos:         file_articleflux_v1_system_proto_enumTypes,
		MessageInfos:      file_articleflux_v1_system_proto_msgTypes,
	}.Build()
	File_articleflux_v1_system_proto = out.File
	file_articleflux_v1_system_proto_goTypes = nil
	file_articleflux_v1_system_proto_depIdxs = nil
}
