package lexicon

import "github.com/monstercameron/ArticleFlux/internal/classify"

// books is the Books & Writing category (plan.md §27.3d #20).
func books() classify.Label {
	return classify.Label{
		Slug: "books",
		Name: "Books & Writing",
		Terms: []classify.Term{
			{Text: "booker prize", Weight: 2.6},
			{Text: "pulitzer prize", Weight: 2.6},
			{Text: "banned book", Weight: 2.2},
			{Text: "bestseller list", Weight: 2.2},
			{Text: "poet laureate", Weight: 2.2},
			{Text: "national book award", Weight: 2.2},
			{Text: "book deal", Weight: 2.0},
			{Text: "literary award", Weight: 2.0},
			{Text: "essay collection", Weight: 2.0},
			{Text: "short story collection", Weight: 2.0},
			{Text: "book banning", Weight: 2.0},
			{Text: "debut novel", Weight: 2.0},
			{Text: "manuscript rejection", Weight: 1.8},
			{Text: "literary agent", Weight: 1.8},
			{Text: "poetry collection", Weight: 1.8},
			{Text: "ghostwriter", Weight: 1.8},
			{Text: "self-published", Weight: 1.8},
			{Text: "literary fiction", Weight: 1.8},
			{Text: "young adult fiction", Weight: 1.8},
			{Text: "graphic novel", Weight: 1.8},
			{Text: "first edition", Weight: 1.8},
			{Text: "literary magazine", Weight: 1.8},
			{Text: "literary festival", Weight: 1.8},
			{Text: "book tour", Weight: 1.8},
			{Text: "publishing house", Weight: 1.8},
			{Text: "memoir", Weight: 1.8},
			{Text: "book excerpt", Weight: 1.6},
			{Text: "book review", Weight: 1.6},
			{Text: "literary criticism", Weight: 1.6},
			{Text: "rare book", Weight: 1.6},
			{Text: "out of print", Weight: 1.6},
			{Text: "memoirist", Weight: 1.6},
			{Text: "book signing", Weight: 1.6},
			{Text: "audiobook", Weight: 1.6},
			{Text: "manuscript", Weight: 1.6},
			{Text: "novelist", Weight: 1.4},
			{Text: "translation", Weight: 1.4},
			{Text: "narrative voice", Weight: 1.4},
			{Text: "short story", Weight: 1.4},
			{Text: "publishing industry", Weight: 1.4},
			{Text: "autobiography", Weight: 1.4},
			{Text: "nonfiction", Weight: 1.2},
			{Text: "biography", Weight: 1.2},
			{Text: "character development", Weight: 1.2},
			{Text: "foreword", Weight: 1.2},
			{Text: "epilogue", Weight: 1.2},
			{Text: "prologue", Weight: 1.2},
			{Text: "publisher", Weight: 1.1},
			{Text: "book club", Weight: 1.1},
			{Text: "unreliable narrator", Weight: 1.6},
			{Text: "small press", Weight: 1.6},
			{Text: "vanity press", Weight: 1.4},
			{Text: "book jacket", Weight: 1.0},
			{Text: "prose", Weight: 1.0},
			{Text: "novel", Weight: 1.0},
			{Text: "reading list", Weight: 0.9},
			{Text: "bookstore", Weight: 0.8},
			{Text: "editor", Weight: 0.6},
			{Text: "chapter", Weight: 0.5},
			{Text: "library", Weight: 0.6},
			{Text: "plot", Weight: 0.6},
		},
		MinScore: 0,
		Prompt: "Assign for books, authors and the publishing world. Not for a book adapted into " +
			"a film considered as a film (see Film & TV), and not for library funding as a civic " +
			"budget story (see Politics & Policy).",
	}
}
