package lexicon

import "github.com/monstercameron/ArticleFlux/internal/classify"

// culture is the Art & Culture category (plan.md §27.3d #19, slug `culture`).
func culture() classify.Label {
	return classify.Label{
		Slug: "culture",
		Name: "Art & Culture",
		Terms: []classify.Term{
			{Text: "world heritage site", Weight: 2.4},
			{Text: "art auction", Weight: 2.2},
			{Text: "biennale", Weight: 2.0},
			{Text: "art restoration", Weight: 2.0},
			{Text: "art forgery", Weight: 2.0},
			{Text: "looted art", Weight: 2.0},
			{Text: "sotheby's", Weight: 2.0},
			{Text: "christie's", Weight: 2.0},
			{Text: "gallery opening", Weight: 2.0},
			{Text: "art exhibition", Weight: 2.0},
			{Text: "cultural heritage", Weight: 1.8},
			{Text: "historic preservation", Weight: 1.8},
			{Text: "art installation", Weight: 1.8},
			{Text: "ancient artifact", Weight: 1.8},
			{Text: "antiquities", Weight: 1.8},
			{Text: "traveling exhibition", Weight: 1.8},
			{Text: "art fair", Weight: 1.8},
			{Text: "auction house", Weight: 1.8},
			{Text: "art conservation", Weight: 1.8},
			{Text: "contemporary art", Weight: 1.8},
			{Text: "performance art", Weight: 1.8},
			{Text: "repatriation", Weight: 1.8},
			{Text: "fresco", Weight: 1.8},
			{Text: "national gallery", Weight: 1.8},
			{Text: "street art", Weight: 1.6},
			{Text: "art critic", Weight: 1.6},
			{Text: "art collector", Weight: 1.6},
			{Text: "art market", Weight: 1.6},
			{Text: "sculpture", Weight: 1.6},
			{Text: "choreography", Weight: 1.6},
			{Text: "theatre production", Weight: 1.6},
			{Text: "playwright", Weight: 1.6},
			{Text: "permanent collection", Weight: 1.6},
			{Text: "tapestry", Weight: 1.6},
			{Text: "restoration project", Weight: 1.6},
			{Text: "art museum", Weight: 1.6},
			{Text: "mural", Weight: 1.4},
			{Text: "art history", Weight: 1.4},
			{Text: "art collection", Weight: 1.4},
			{Text: "cultural institution", Weight: 1.4},
			{Text: "museum director", Weight: 1.4},
			{Text: "curator", Weight: 1.4},
			{Text: "fine art", Weight: 1.4},
			{Text: "ballet", Weight: 1.4},
			{Text: "art heist", Weight: 2.0},
			{Text: "art residency", Weight: 1.6},
			{Text: "digital art", Weight: 1.4},
			{Text: "cultural exchange", Weight: 1.2},
			{Text: "dance performance", Weight: 1.4},
			{Text: "stage production", Weight: 1.4},
			{Text: "masterpiece", Weight: 1.4},
			{Text: "artifact", Weight: 1.2},
			{Text: "craftsmanship", Weight: 1.2},
			{Text: "ceramics", Weight: 1.2},
			{Text: "archive", Weight: 1.0},
			{Text: "museum", Weight: 1.0},
			{Text: "gallery", Weight: 0.9},
			{Text: "exhibit", Weight: 0.9},
			{Text: "artisan", Weight: 0.9},
			{Text: "painting", Weight: 0.8},
			{Text: "pottery", Weight: 0.8},
		},
		MinScore: 0,
		Prompt: "Assign for visual and performing arts, museums and cultural heritage. Not for a " +
			"film or album considered as commerce (see Film & TV or Music), and not for a novel or " +
			"essay's own content (see Books & Writing).",
	}
}
