package lexicon

import "github.com/monstercameron/ArticleFlux/internal/classify"

// design is the Design & Typography category (plan.md §27.3d #24).
func design() classify.Label {
	return classify.Label{
		Slug: "design",
		Name: "Design & Typography",
		Terms: []classify.Term{
			{Text: "kerning", Weight: 2.4},
			{Text: "type foundry", Weight: 2.2},
			{Text: "wireframe", Weight: 2.0},
			{Text: "figma", Weight: 2.0},
			{Text: "design system", Weight: 2.0},
			{Text: "usability testing", Weight: 2.0},
			{Text: "information architecture", Weight: 2.0},
			{Text: "typeface", Weight: 1.9},
			{Text: "brand identity", Weight: 1.8},
			{Text: "logo design", Weight: 1.8},
			{Text: "typography", Weight: 1.8},
			{Text: "visual hierarchy", Weight: 1.8},
			{Text: "brand guidelines", Weight: 1.8},
			{Text: "design language", Weight: 1.8},
			{Text: "iconography", Weight: 1.8},
			{Text: "adobe illustrator", Weight: 1.8},
			{Text: "adobe photoshop", Weight: 1.8},
			{Text: "logo redesign", Weight: 1.8},
			{Text: "packaging design", Weight: 1.8},
			{Text: "industrial design", Weight: 1.8},
			{Text: "interaction design", Weight: 1.8},
			{Text: "motion design", Weight: 1.8},
			{Text: "responsive design", Weight: 1.8},
			{Text: "serif font", Weight: 1.8},
			{Text: "sans-serif", Weight: 1.8},
			{Text: "design award", Weight: 1.8},
			{Text: "ux researcher", Weight: 1.8},
			{Text: "wayfinding", Weight: 1.8},
			{Text: "screen reader", Weight: 1.8},
			{Text: "contrast ratio", Weight: 1.8},
			{Text: "color palette", Weight: 1.6},
			{Text: "ux design", Weight: 1.6},
			{Text: "font family", Weight: 1.6},
			{Text: "grid system", Weight: 1.6},
			{Text: "design critique", Weight: 1.6},
			{Text: "style guide", Weight: 1.6},
			{Text: "vector graphic", Weight: 1.6},
			{Text: "mockup", Weight: 1.6},
			{Text: "rebrand", Weight: 1.6},
			{Text: "product design", Weight: 1.6},
			{Text: "maximalism", Weight: 1.6},
			{Text: "color theory", Weight: 1.6},
			{Text: "poster design", Weight: 1.6},
			{Text: "editorial design", Weight: 1.6},
			{Text: "negative space", Weight: 1.6},
			{Text: "ui design", Weight: 1.4},
			{Text: "user experience", Weight: 1.4},
			{Text: "user interface", Weight: 1.4},
			{Text: "graphic design", Weight: 1.4},
			{Text: "accessibility", Weight: 1.4},
			{Text: "dark mode", Weight: 1.4},
			{Text: "design trend", Weight: 1.4},
			{Text: "minimalism", Weight: 1.4},
			{Text: "web design", Weight: 1.4},
			{Text: "print design", Weight: 1.4},
			{Text: "branding", Weight: 1.2},
			{Text: "illustration", Weight: 1.2},
			{Text: "prototype", Weight: 1.0},
			{Text: "whitespace", Weight: 1.0},
			{Text: "layout", Weight: 0.7},
		},
		MinScore: 0,
		Prompt: "Assign for visual and product design craft: typography, UX, branding, layout. " +
			"Not for software engineering with no design-craft angle (see Software & Development), " +
			"and not for fine art (see Art & Culture).",
	}
}
