package lexicon

import "github.com/monstercameron/ArticleFlux/internal/classify"

// education is the Education category (plan.md §27.3d #26).
func education() classify.Label {
	return classify.Label{
		Slug: "education",
		Name: "Education",
		Terms: []classify.Term{
			{Text: "admissions scandal", Weight: 2.6},
			{Text: "student loan forgiveness", Weight: 2.4},
			{Text: "title ix", Weight: 2.2},
			{Text: "teacher shortage", Weight: 2.2},
			{Text: "teacher strike", Weight: 2.2},
			{Text: "early childhood education", Weight: 2.2},
			{Text: "mooc", Weight: 2.2},
			{Text: "student debt", Weight: 2.2},
			{Text: "college admissions", Weight: 2.0},
			{Text: "standardized test", Weight: 2.0},
			{Text: "accreditation", Weight: 2.0},
			{Text: "pedagogy", Weight: 2.0},
			{Text: "charter school", Weight: 2.0},
			{Text: "literacy rate", Weight: 2.0},
			{Text: "dropout rate", Weight: 2.0},
			{Text: "tenure track", Weight: 2.0},
			{Text: "academic freedom", Weight: 2.0},
			{Text: "vocational training", Weight: 2.0},
			{Text: "special education", Weight: 2.0},
			{Text: "achievement gap", Weight: 2.0},
			{Text: "k-12", Weight: 2.0},
			{Text: "student loan", Weight: 2.0},
			{Text: "higher education", Weight: 1.8},
			{Text: "online learning", Weight: 1.8},
			{Text: "school board", Weight: 1.8},
			{Text: "homeschooling", Weight: 1.8},
			{Text: "graduation rate", Weight: 1.8},
			{Text: "college rankings", Weight: 1.8},
			{Text: "ivy league", Weight: 1.8},
			{Text: "community college", Weight: 1.8},
			{Text: "apprenticeship", Weight: 1.8},
			{Text: "sat score", Weight: 1.8},
			{Text: "campus safety", Weight: 1.8},
			{Text: "school funding", Weight: 1.8},
			{Text: "education policy", Weight: 1.8},
			{Text: "financial aid", Weight: 1.6},
			{Text: "tuition", Weight: 1.6},
			{Text: "curriculum", Weight: 1.6},
			{Text: "distance learning", Weight: 1.6},
			{Text: "school district", Weight: 1.6},
			{Text: "grant funding", Weight: 1.6},
			{Text: "test scores", Weight: 1.6},
			{Text: "provost", Weight: 1.6},
			{Text: "learning outcomes", Weight: 1.6},
			{Text: "public school", Weight: 1.4},
			{Text: "private school", Weight: 1.4},
			{Text: "scholarship", Weight: 1.4},
			{Text: "enrollment", Weight: 1.4},
			{Text: "syllabus", Weight: 1.4},
			{Text: "campus protest", Weight: 1.2},
			{Text: "faculty", Weight: 1.2},
			{Text: "dean", Weight: 1.2},
			{Text: "textbook", Weight: 1.2},
			{Text: "university", Weight: 1.0},
			{Text: "professor", Weight: 1.0},
			{Text: "student union", Weight: 1.0},
			{Text: "semester", Weight: 0.7},
			{Text: "classroom", Weight: 0.7},
			{Text: "student", Weight: 0.5},
		},
		MinScore: 0,
		Prompt: "Assign for schools, universities and learning: curricula, admissions, funding, " +
			"policy. Not for a scientific research finding produced at a university (see Science & " +
			"Research), and not for university sports (see Sport).",
	}
}
