package lexicon

import "github.com/monstercameron/ArticleFlux/internal/classify"

// filmTV is the Film & TV category (plan.md §27.3d #17, slug `film-tv`).
func filmTV() classify.Label {
	return classify.Label{
		Slug: "filmtv",
		Name: "Film & TV",
		Terms: []classify.Term{
			{Text: "box office", Weight: 2.6},
			{Text: "oscar nomination", Weight: 2.4},
			{Text: "academy awards", Weight: 2.2},
			{Text: "season finale", Weight: 2.2},
			{Text: "biopic", Weight: 2.0},
			{Text: "golden globes", Weight: 2.0},
			{Text: "emmy awards", Weight: 2.0},
			{Text: "series finale", Weight: 2.0},
			{Text: "renewed for season", Weight: 2.0},
			{Text: "opening weekend", Weight: 2.0},
			{Text: "streaming wars", Weight: 2.0},
			{Text: "live-action remake", Weight: 2.0},
			{Text: "a24", Weight: 2.0},
			{Text: "film festival", Weight: 2.0},
			{Text: "movie premiere", Weight: 2.0},
			{Text: "film franchise", Weight: 1.8},
			{Text: "cancelled series", Weight: 1.8},
			{Text: "miniseries", Weight: 1.8},
			{Text: "docuseries", Weight: 1.8},
			{Text: "cinematography", Weight: 1.8},
			{Text: "theatrical release", Weight: 1.8},
			{Text: "streaming exclusive", Weight: 1.8},
			{Text: "film noir", Weight: 1.8},
			{Text: "indie film", Weight: 1.8},
			{Text: "showrunner", Weight: 1.8},
			{Text: "director's cut", Weight: 1.8},
			{Text: "pilot episode", Weight: 1.8},
			{Text: "rotten tomatoes", Weight: 1.8},
			{Text: "cast announcement", Weight: 1.8},
			{Text: "red carpet", Weight: 1.8},
			{Text: "disney plus", Weight: 1.8},
			{Text: "netflix", Weight: 1.8},
			{Text: "film adaptation", Weight: 1.8},
			{Text: "streaming service", Weight: 1.8},
			{Text: "teaser trailer", Weight: 1.6},
			{Text: "plot twist", Weight: 1.6},
			{Text: "supporting actor", Weight: 1.6},
			{Text: "animated film", Weight: 1.6},
			{Text: "film score", Weight: 1.6},
			{Text: "film critic", Weight: 1.6},
			{Text: "screenplay", Weight: 1.6},
			{Text: "prequel", Weight: 1.6},
			{Text: "hbo", Weight: 1.6},
			{Text: "blockbuster", Weight: 1.6},
			{Text: "movie review", Weight: 1.4},
			{Text: "screenwriter", Weight: 1.4},
			{Text: "voice actor", Weight: 1.4},
			{Text: "lead role", Weight: 1.4},
			{Text: "sequel", Weight: 1.4},
			{Text: "reboot", Weight: 1.4},
			{Text: "film studio", Weight: 1.4},
			{Text: "hollywood", Weight: 1.4},
			{Text: "character arc", Weight: 1.4},
			{Text: "tv series", Weight: 1.2},
			{Text: "season premiere", Weight: 1.6},
			{Text: "spinoff series", Weight: 1.4},
			{Text: "marvel", Weight: 1.2},
			{Text: "comic con", Weight: 1.3},
			{Text: "anime", Weight: 1.2},
			{Text: "cosplay", Weight: 1.3},
			{Text: "tv network", Weight: 1.2},
			{Text: "director", Weight: 1.0},
			{Text: "movie theater", Weight: 1.0},
			{Text: "trailer", Weight: 1.0},
			{Text: "cinema", Weight: 0.8},
			{Text: "cast", Weight: 0.7},
		},
		Exclude: []classify.Term{
			{Text: "plaster cast", Weight: 1.5},
			{Text: "cast a vote", Weight: 1.5},
		},
		MinScore: 0,
		Prompt: "Assign for movies and television as an industry and an art form: releases, " +
			"awards, production, streaming. Not for a celebrity's unrelated personal news, and not " +
			"for a film's soundtrack considered as music (see Music).",
	}
}
