package lexicon

import "github.com/monstercameron/ArticleFlux/internal/classify"

// food is the Food & Drink category (plan.md §27.3d #22).
func food() classify.Label {
	return classify.Label{
		Slug: "food",
		Name: "Food & Drink",
		Terms: []classify.Term{
			{Text: "michelin star", Weight: 2.8},
			{Text: "sourdough", Weight: 2.6},
			{Text: "sourdough starter", Weight: 2.4},
			{Text: "james beard award", Weight: 2.4},
			{Text: "charcuterie", Weight: 2.0},
			{Text: "fermentation", Weight: 2.0},
			{Text: "espresso", Weight: 2.0},
			{Text: "tasting menu", Weight: 2.0},
			{Text: "farm to table", Weight: 2.0},
			{Text: "sommelier", Weight: 2.0},
			{Text: "wine tasting", Weight: 2.0},
			{Text: "pastry chef", Weight: 2.0},
			{Text: "umami", Weight: 1.8},
			{Text: "gastronomy", Weight: 1.8},
			{Text: "craft beer", Weight: 1.8},
			{Text: "mixology", Weight: 1.8},
			{Text: "cocktail recipe", Weight: 1.8},
			{Text: "craft cocktail", Weight: 1.8},
			{Text: "food critic", Weight: 1.8},
			{Text: "culinary school", Weight: 1.8},
			{Text: "pop-up restaurant", Weight: 1.8},
			{Text: "fine dining", Weight: 1.8},
			{Text: "plant-based diet", Weight: 1.8},
			{Text: "coffee roasting", Weight: 1.8},
			{Text: "specialty coffee", Weight: 1.8},
			{Text: "celebrity chef", Weight: 1.8},
			{Text: "wine region", Weight: 1.8},
			{Text: "distillery", Weight: 1.8},
			{Text: "wine pairing", Weight: 1.8},
			{Text: "supper club", Weight: 1.8},
			{Text: "restaurant review", Weight: 1.8},
			{Text: "culinary tradition", Weight: 1.6},
			{Text: "regional cuisine", Weight: 1.6},
			{Text: "street food", Weight: 1.6},
			{Text: "seasonal produce", Weight: 1.6},
			{Text: "farmers market", Weight: 1.6},
			{Text: "food waste", Weight: 1.6},
			{Text: "omakase", Weight: 2.0},
			{Text: "tasting flight", Weight: 1.6},
			{Text: "heirloom variety", Weight: 1.6},
			{Text: "farm stand", Weight: 1.4},
			{Text: "test kitchen", Weight: 1.6},
			{Text: "cookbook", Weight: 1.6},
			{Text: "vineyard", Weight: 1.6},
			{Text: "culinary arts", Weight: 1.6},
			{Text: "tasting notes", Weight: 1.6},
			{Text: "barista", Weight: 1.4},
			{Text: "food truck", Weight: 1.6},
			{Text: "brewing", Weight: 1.4},
			{Text: "meal prep", Weight: 1.4},
			{Text: "gluten-free", Weight: 1.4},
			{Text: "recipe", Weight: 1.4},
			{Text: "whiskey", Weight: 1.2},
			{Text: "food delivery", Weight: 1.4},
			{Text: "coffee shop", Weight: 1.2},
			{Text: "comfort food", Weight: 1.2},
			{Text: "chef", Weight: 1.0},
			{Text: "vegan", Weight: 1.0},
			{Text: "baking", Weight: 1.0},
			{Text: "brunch", Weight: 0.9},
		},
		MinScore: 0,
		Prompt: "Assign for cooking, restaurants, and drink culture. Not for agricultural policy " +
			"or food-supply economics (see Business & Companies or Climate & Environment), and not " +
			"for nutrition as a medical topic (see Health & Medicine).",
	}
}
