package lexicon

import "github.com/monstercameron/ArticleFlux/internal/classify"

// sport is the Sport category (plan.md §27.3d #21).
func sport() classify.Label {
	return classify.Label{
		Slug: "sport",
		Name: "Sport",
		Terms: []classify.Term{
			{Text: "super bowl", Weight: 2.6},
			{Text: "world cup", Weight: 2.4},
			{Text: "world series", Weight: 2.2},
			{Text: "stanley cup", Weight: 2.2},
			{Text: "march madness", Weight: 2.2},
			{Text: "formula 1", Weight: 2.2},
			{Text: "penalty shootout", Weight: 2.2},
			{Text: "relegation", Weight: 2.2},
			{Text: "concussion protocol", Weight: 2.2},
			{Text: "doping scandal", Weight: 2.2},
			{Text: "tennis grand slam", Weight: 2.2},
			{Text: "transfer window", Weight: 2.2},
			{Text: "hat trick", Weight: 2.0},
			{Text: "red card", Weight: 2.0},
			{Text: "free agency", Weight: 2.0},
			{Text: "draft pick", Weight: 2.0},
			{Text: "trade deadline", Weight: 2.0},
			{Text: "knockout round", Weight: 2.0},
			{Text: "anti-doping", Weight: 2.0},
			{Text: "transfer fee", Weight: 2.0},
			{Text: "salary cap", Weight: 2.0},
			{Text: "championship game", Weight: 2.0},
			{Text: "grand prix", Weight: 2.0},
			{Text: "wimbledon", Weight: 2.0},
			{Text: "pga tour", Weight: 2.0},
			{Text: "nba draft", Weight: 2.0},
			{Text: "nfl draft", Weight: 2.0},
			{Text: "mlb draft", Weight: 2.0},
			{Text: "injury report", Weight: 2.0},
			{Text: "yellow card", Weight: 1.8},
			{Text: "three pointer", Weight: 1.8},
			{Text: "slam dunk", Weight: 1.8},
			{Text: "quarterfinal", Weight: 1.8},
			{Text: "semifinal", Weight: 1.8},
			{Text: "league table", Weight: 1.8},
			{Text: "var decision", Weight: 1.8},
			{Text: "tournament bracket", Weight: 1.8},
			{Text: "world championship", Weight: 1.8},
			{Text: "gold medal", Weight: 1.8},
			{Text: "sprint final", Weight: 1.8},
			{Text: "decathlon", Weight: 1.8},
			{Text: "major championship", Weight: 1.8},
			{Text: "olympics", Weight: 1.8},
			{Text: "penalty kick", Weight: 1.8},
			{Text: "wild card", Weight: 1.6},
			{Text: "contract extension", Weight: 1.6},
			{Text: "silver medal", Weight: 1.6},
			{Text: "bronze medal", Weight: 1.6},
			{Text: "world record", Weight: 1.6},
			{Text: "triathlon", Weight: 1.6},
			{Text: "home run", Weight: 1.6},
			{Text: "touchdown", Weight: 1.6},
			{Text: "league standings", Weight: 1.6},
			{Text: "extra time", Weight: 1.4},
			{Text: "overtime", Weight: 1.4},
			{Text: "matchday", Weight: 1.4},
			{Text: "personal best", Weight: 1.4},
			{Text: "marathon", Weight: 1.4},
			{Text: "head coach", Weight: 1.2},
			{Text: "fixture", Weight: 1.2},
			{Text: "roster", Weight: 1.0},
			{Text: "athlete", Weight: 0.8},
			{Text: "stadium", Weight: 0.7},
			{Text: "scoreboard", Weight: 0.7},
			{Text: "coach", Weight: 0.5},
			{Text: "arena", Weight: 0.5},
		},
		MinScore: 0,
		Prompt: "Assign for competitive sport: fixtures, results, transfers, athletes. Not for a " +
			"team's business ownership deal with no on-field content (see Business & Companies), " +
			"and not for exercise or fitness as a lifestyle topic.",
	}
}
