package lexicon

import "github.com/monstercameron/ArticleFlux/internal/classify"

// travel is the Travel & Outdoors category (plan.md §27.3d #23).
func travel() classify.Label {
	return classify.Label{
		Slug: "travel",
		Name: "Travel & Outdoors",
		Terms: []classify.Term{
			{Text: "overtourism", Weight: 2.4},
			{Text: "national park", Weight: 2.2},
			{Text: "eco-tourism", Weight: 2.0},
			{Text: "digital nomad", Weight: 2.0},
			{Text: "all-inclusive resort", Weight: 2.0},
			{Text: "travel advisory", Weight: 2.0},
			{Text: "flight route", Weight: 2.0},
			{Text: "visa requirement", Weight: 2.0},
			{Text: "national forest", Weight: 1.8},
			{Text: "wilderness area", Weight: 1.8},
			{Text: "trailhead", Weight: 1.8},
			{Text: "hiking trail", Weight: 1.8},
			{Text: "backpacking", Weight: 1.8},
			{Text: "cruise ship", Weight: 1.8},
			{Text: "boutique hotel", Weight: 1.8},
			{Text: "sustainable tourism", Weight: 1.8},
			{Text: "adventure travel", Weight: 1.8},
			{Text: "mountaineering", Weight: 1.8},
			{Text: "travel visa", Weight: 1.8},
			{Text: "travel guide", Weight: 1.6},
			{Text: "solo travel", Weight: 1.6},
			{Text: "travel insurance", Weight: 1.6},
			{Text: "airbnb", Weight: 1.6},
			{Text: "vacation rental", Weight: 1.6},
			{Text: "staycation", Weight: 1.6},
			{Text: "weekend getaway", Weight: 1.6},
			{Text: "scenic route", Weight: 1.6},
			{Text: "road trip", Weight: 1.6},
			{Text: "jet lag", Weight: 1.6},
			{Text: "duty-free", Weight: 1.6},
			{Text: "trekking", Weight: 1.6},
			{Text: "safari", Weight: 1.6},
			{Text: "visa waiver", Weight: 1.8},
			{Text: "travel warning", Weight: 1.8},
			{Text: "package holiday", Weight: 1.6},
			{Text: "gap year", Weight: 1.6},
			{Text: "scenic drive", Weight: 1.4},
			{Text: "day trip", Weight: 1.2},
			{Text: "ski resort", Weight: 1.6},
			{Text: "scuba diving", Weight: 1.6},
			{Text: "itinerary", Weight: 1.6},
			{Text: "hostel", Weight: 1.6},
			{Text: "guided tour", Weight: 1.4},
			{Text: "walking tour", Weight: 1.4},
			{Text: "campsite", Weight: 1.4},
			{Text: "camping trip", Weight: 1.4},
			{Text: "backpacker", Weight: 1.4},
			{Text: "tourist attraction", Weight: 1.4},
			{Text: "expedition", Weight: 1.4},
			{Text: "snorkeling", Weight: 1.4},
			{Text: "beach resort", Weight: 1.4},
			{Text: "layover", Weight: 1.4},
			{Text: "honeymoon", Weight: 1.2},
			{Text: "passport", Weight: 1.2},
			{Text: "travel destination", Weight: 1.2},
			{Text: "border control", Weight: 1.0},
			{Text: "travel ban", Weight: 1.0},
			{Text: "carry-on", Weight: 1.0},
			{Text: "ferry", Weight: 1.0},
			{Text: "luggage", Weight: 0.8},
		},
		MinScore: 0,
		Prompt: "Assign for travel, tourism and the outdoors: destinations, trails, trip planning. " +
			"Not for airline industry business (see Transport & Mobility), and not for immigration " +
			"policy (see Politics & Policy).",
	}
}
