// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: tidings/v1/reader.proto

package tidingsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReaderService_ListFeeds_FullMethodName          = "/tidings.v1.ReaderService/ListFeeds"
	ReaderService_ListItems_FullMethodName          = "/tidings.v1.ReaderService/ListItems"
	ReaderService_GetItem_FullMethodName            = "/tidings.v1.ReaderService/GetItem"
	ReaderService_SetItemState_FullMethodName       = "/tidings.v1.ReaderService/SetItemState"
	ReaderService_MarkAllRead_FullMethodName        = "/tidings.v1.ReaderService/MarkAllRead"
	ReaderService_Subscribe_FullMethodName          = "/tidings.v1.ReaderService/Subscribe"
	ReaderService_Unsubscribe_FullMethodName        = "/tidings.v1.ReaderService/Unsubscribe"
	ReaderService_Refresh_FullMethodName            = "/tidings.v1.ReaderService/Refresh"
	ReaderService_Search_FullMethodName             = "/tidings.v1.ReaderService/Search"
	ReaderService_GetPrefs_FullMethodName           = "/tidings.v1.ReaderService/GetPrefs"
	ReaderService_SetPrefs_FullMethodName           = "/tidings.v1.ReaderService/SetPrefs"
	ReaderService_ListTags_FullMethodName           = "/tidings.v1.ReaderService/ListTags"
	ReaderService_SetFeedTag_FullMethodName         = "/tidings.v1.ReaderService/SetFeedTag"
	ReaderService_SetNote_FullMethodName            = "/tidings.v1.ReaderService/SetNote"
	ReaderService_ListNotes_FullMethodName          = "/tidings.v1.ReaderService/ListNotes"
	ReaderService_GetFeedSettings_FullMethodName    = "/tidings.v1.ReaderService/GetFeedSettings"
	ReaderService_UpdateFeedSettings_FullMethodName = "/tidings.v1.ReaderService/UpdateFeedSettings"
)

// ReaderServiceClient is the client API for ReaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReaderService is the reading surface: the sidebar, the list, the article, and
// the four state changes a reader can make.
//
// One service rather than several because all three transports (§20.7) route
// through one service layer — the gRPC tunnel the web client uses, the plain
// HTTPS offline-pack channel, and the Google Reader-compatible REST API that
// Reeder and NetNewsWire speak. Splitting them would let "marked read in Reeder"
// diverge from the web UI, which is the failure the single layer exists to
// prevent.
type ReaderServiceClient interface {
	// ListFeeds returns the sidebar: every subscription with its unread count.
	ListFeeds(ctx context.Context, in *ListFeedsRequest, opts ...grpc.CallOption) (*ListFeedsResponse, error)
	// ListItems returns one page of the item list.
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	// GetItem returns one item with its full content.
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
	// SetItemState marks read/unread and starred/unstarred. One RPC rather than
	// four because they share a row, a rev, and an idempotency key — and because
	// the offline outbox replays them together.
	SetItemState(ctx context.Context, in *SetItemStateRequest, opts ...grpc.CallOption) (*SetItemStateResponse, error)
	// MarkAllRead marks a whole feed or the whole megafeed read.
	MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error)
	// Subscribe adds a feed by URL. The source is global (A14), so this usually
	// attaches an existing row rather than creating one.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	// Unsubscribe removes the subscription. It never deletes the source (A22).
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
	// Refresh polls sources now instead of waiting for the scheduler.
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	// Search runs a full-text query (FTS5, G1).
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// GetPrefs returns this user's UI preferences.
	//
	// Server-side rather than localStorage because layout is part of an account,
	// not of a browser: a reader that forgets your pane widths when you open it on
	// a different machine has not remembered anything useful.
	GetPrefs(ctx context.Context, in *GetPrefsRequest, opts ...grpc.CallOption) (*GetPrefsResponse, error)
	// SetPrefs merges keys into this user's preferences. A merge, not a replace,
	// so a stale client cannot erase settings it does not know about.
	SetPrefs(ctx context.Context, in *SetPrefsRequest, opts ...grpc.CallOption) (*SetPrefsResponse, error)
	// ListTags returns this user's tags and which feeds carry them.
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	// SetFeedTag adds or removes a tag on a feed, creating the tag on first use.
	// Nobody wants to manage a taxonomy; they want to label the thing in front of
	// them, and the tag list is the consequence.
	SetFeedTag(ctx context.Context, in *SetFeedTagRequest, opts ...grpc.CallOption) (*SetFeedTagResponse, error)
	// SetNote writes or clears the note on an item. An empty body deletes it, so
	// "has a note" stays an existence check.
	SetNote(ctx context.Context, in *SetNoteRequest, opts ...grpc.CallOption) (*SetNoteResponse, error)
	// ListNotes returns the items this user has annotated, most recently written
	// first — it is a list of your own writing, found by when you wrote it.
	ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error)
	// GetFeedSettings returns everything the per-feed panel shows, and
	// UpdateFeedSettings writes back only the fields that were sent.
	//
	// Two RPCs rather than folding this into ListFeeds: the sidebar asks for 151
	// feeds many times a session and does not want health strings, poll intervals
	// or cache depths on any of them.
	GetFeedSettings(ctx context.Context, in *GetFeedSettingsRequest, opts ...grpc.CallOption) (*GetFeedSettingsResponse, error)
	UpdateFeedSettings(ctx context.Context, in *UpdateFeedSettingsRequest, opts ...grpc.CallOption) (*UpdateFeedSettingsResponse, error)
}

type readerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReaderServiceClient(cc grpc.ClientConnInterface) ReaderServiceClient {
	return &readerServiceClient{cc}
}

func (c *readerServiceClient) ListFeeds(ctx context.Context, in *ListFeedsRequest, opts ...grpc.CallOption) (*ListFeedsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeedsResponse)
	err := c.cc.Invoke(ctx, ReaderService_ListFeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, ReaderService_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemResponse)
	err := c.cc.Invoke(ctx, ReaderService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) SetItemState(ctx context.Context, in *SetItemStateRequest, opts ...grpc.CallOption) (*SetItemStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetItemStateResponse)
	err := c.cc.Invoke(ctx, ReaderService_SetItemState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAllReadResponse)
	err := c.cc.Invoke(ctx, ReaderService_MarkAllRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, ReaderService_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeResponse)
	err := c.cc.Invoke(ctx, ReaderService_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, ReaderService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, ReaderService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) GetPrefs(ctx context.Context, in *GetPrefsRequest, opts ...grpc.CallOption) (*GetPrefsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrefsResponse)
	err := c.cc.Invoke(ctx, ReaderService_GetPrefs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) SetPrefs(ctx context.Context, in *SetPrefsRequest, opts ...grpc.CallOption) (*SetPrefsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPrefsResponse)
	err := c.cc.Invoke(ctx, ReaderService_SetPrefs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, ReaderService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) SetFeedTag(ctx context.Context, in *SetFeedTagRequest, opts ...grpc.CallOption) (*SetFeedTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFeedTagResponse)
	err := c.cc.Invoke(ctx, ReaderService_SetFeedTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) SetNote(ctx context.Context, in *SetNoteRequest, opts ...grpc.CallOption) (*SetNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNoteResponse)
	err := c.cc.Invoke(ctx, ReaderService_SetNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotesResponse)
	err := c.cc.Invoke(ctx, ReaderService_ListNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) GetFeedSettings(ctx context.Context, in *GetFeedSettingsRequest, opts ...grpc.CallOption) (*GetFeedSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedSettingsResponse)
	err := c.cc.Invoke(ctx, ReaderService_GetFeedSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readerServiceClient) UpdateFeedSettings(ctx context.Context, in *UpdateFeedSettingsRequest, opts ...grpc.CallOption) (*UpdateFeedSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFeedSettingsResponse)
	err := c.cc.Invoke(ctx, ReaderService_UpdateFeedSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReaderServiceServer is the server API for ReaderService service.
// All implementations must embed UnimplementedReaderServiceServer
// for forward compatibility.
//
// ReaderService is the reading surface: the sidebar, the list, the article, and
// the four state changes a reader can make.
//
// One service rather than several because all three transports (§20.7) route
// through one service layer — the gRPC tunnel the web client uses, the plain
// HTTPS offline-pack channel, and the Google Reader-compatible REST API that
// Reeder and NetNewsWire speak. Splitting them would let "marked read in Reeder"
// diverge from the web UI, which is the failure the single layer exists to
// prevent.
type ReaderServiceServer interface {
	// ListFeeds returns the sidebar: every subscription with its unread count.
	ListFeeds(context.Context, *ListFeedsRequest) (*ListFeedsResponse, error)
	// ListItems returns one page of the item list.
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	// GetItem returns one item with its full content.
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
	// SetItemState marks read/unread and starred/unstarred. One RPC rather than
	// four because they share a row, a rev, and an idempotency key — and because
	// the offline outbox replays them together.
	SetItemState(context.Context, *SetItemStateRequest) (*SetItemStateResponse, error)
	// MarkAllRead marks a whole feed or the whole megafeed read.
	MarkAllRead(context.Context, *MarkAllReadRequest) (*MarkAllReadResponse, error)
	// Subscribe adds a feed by URL. The source is global (A14), so this usually
	// attaches an existing row rather than creating one.
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	// Unsubscribe removes the subscription. It never deletes the source (A22).
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)
	// Refresh polls sources now instead of waiting for the scheduler.
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	// Search runs a full-text query (FTS5, G1).
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// GetPrefs returns this user's UI preferences.
	//
	// Server-side rather than localStorage because layout is part of an account,
	// not of a browser: a reader that forgets your pane widths when you open it on
	// a different machine has not remembered anything useful.
	GetPrefs(context.Context, *GetPrefsRequest) (*GetPrefsResponse, error)
	// SetPrefs merges keys into this user's preferences. A merge, not a replace,
	// so a stale client cannot erase settings it does not know about.
	SetPrefs(context.Context, *SetPrefsRequest) (*SetPrefsResponse, error)
	// ListTags returns this user's tags and which feeds carry them.
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	// SetFeedTag adds or removes a tag on a feed, creating the tag on first use.
	// Nobody wants to manage a taxonomy; they want to label the thing in front of
	// them, and the tag list is the consequence.
	SetFeedTag(context.Context, *SetFeedTagRequest) (*SetFeedTagResponse, error)
	// SetNote writes or clears the note on an item. An empty body deletes it, so
	// "has a note" stays an existence check.
	SetNote(context.Context, *SetNoteRequest) (*SetNoteResponse, error)
	// ListNotes returns the items this user has annotated, most recently written
	// first — it is a list of your own writing, found by when you wrote it.
	ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error)
	// GetFeedSettings returns everything the per-feed panel shows, and
	// UpdateFeedSettings writes back only the fields that were sent.
	//
	// Two RPCs rather than folding this into ListFeeds: the sidebar asks for 151
	// feeds many times a session and does not want health strings, poll intervals
	// or cache depths on any of them.
	GetFeedSettings(context.Context, *GetFeedSettingsRequest) (*GetFeedSettingsResponse, error)
	UpdateFeedSettings(context.Context, *UpdateFeedSettingsRequest) (*UpdateFeedSettingsResponse, error)
	mustEmbedUnimplementedReaderServiceServer()
}

// UnimplementedReaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReaderServiceServer struct{}

func (UnimplementedReaderServiceServer) ListFeeds(context.Context, *ListFeedsRequest) (*ListFeedsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFeeds not implemented")
}
func (UnimplementedReaderServiceServer) ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedReaderServiceServer) GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedReaderServiceServer) SetItemState(context.Context, *SetItemStateRequest) (*SetItemStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetItemState not implemented")
}
func (UnimplementedReaderServiceServer) MarkAllRead(context.Context, *MarkAllReadRequest) (*MarkAllReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkAllRead not implemented")
}
func (UnimplementedReaderServiceServer) Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedReaderServiceServer) Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedReaderServiceServer) Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedReaderServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedReaderServiceServer) GetPrefs(context.Context, *GetPrefsRequest) (*GetPrefsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrefs not implemented")
}
func (UnimplementedReaderServiceServer) SetPrefs(context.Context, *SetPrefsRequest) (*SetPrefsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPrefs not implemented")
}
func (UnimplementedReaderServiceServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedReaderServiceServer) SetFeedTag(context.Context, *SetFeedTagRequest) (*SetFeedTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFeedTag not implemented")
}
func (UnimplementedReaderServiceServer) SetNote(context.Context, *SetNoteRequest) (*SetNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNote not implemented")
}
func (UnimplementedReaderServiceServer) ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotes not implemented")
}
func (UnimplementedReaderServiceServer) GetFeedSettings(context.Context, *GetFeedSettingsRequest) (*GetFeedSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedSettings not implemented")
}
func (UnimplementedReaderServiceServer) UpdateFeedSettings(context.Context, *UpdateFeedSettingsRequest) (*UpdateFeedSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFeedSettings not implemented")
}
func (UnimplementedReaderServiceServer) mustEmbedUnimplementedReaderServiceServer() {}
func (UnimplementedReaderServiceServer) testEmbeddedByValue()                       {}

// UnsafeReaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReaderServiceServer will
// result in compilation errors.
type UnsafeReaderServiceServer interface {
	mustEmbedUnimplementedReaderServiceServer()
}

func RegisterReaderServiceServer(s grpc.ServiceRegistrar, srv ReaderServiceServer) {
	// If the following call pancis, it indicates UnimplementedReaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReaderService_ServiceDesc, srv)
}

func _ReaderService_ListFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ListFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ListFeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ListFeeds(ctx, req.(*ListFeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_SetItemState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).SetItemState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_SetItemState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).SetItemState(ctx, req.(*SetItemStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_MarkAllRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).MarkAllRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_MarkAllRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).MarkAllRead(ctx, req.(*MarkAllReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_GetPrefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).GetPrefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_GetPrefs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).GetPrefs(ctx, req.(*GetPrefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_SetPrefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPrefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).SetPrefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_SetPrefs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).SetPrefs(ctx, req.(*SetPrefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_SetFeedTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFeedTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).SetFeedTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_SetFeedTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).SetFeedTag(ctx, req.(*SetFeedTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_SetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).SetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_SetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).SetNote(ctx, req.(*SetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_ListNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).ListNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_ListNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).ListNotes(ctx, req.(*ListNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_GetFeedSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).GetFeedSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_GetFeedSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).GetFeedSettings(ctx, req.(*GetFeedSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReaderService_UpdateFeedSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeedSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReaderServiceServer).UpdateFeedSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReaderService_UpdateFeedSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReaderServiceServer).UpdateFeedSettings(ctx, req.(*UpdateFeedSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReaderService_ServiceDesc is the grpc.ServiceDesc for ReaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tidings.v1.ReaderService",
	HandlerType: (*ReaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFeeds",
			Handler:    _ReaderService_ListFeeds_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _ReaderService_ListItems_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _ReaderService_GetItem_Handler,
		},
		{
			MethodName: "SetItemState",
			Handler:    _ReaderService_SetItemState_Handler,
		},
		{
			MethodName: "MarkAllRead",
			Handler:    _ReaderService_MarkAllRead_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _ReaderService_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _ReaderService_Unsubscribe_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _ReaderService_Refresh_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _ReaderService_Search_Handler,
		},
		{
			MethodName: "GetPrefs",
			Handler:    _ReaderService_GetPrefs_Handler,
		},
		{
			MethodName: "SetPrefs",
			Handler:    _ReaderService_SetPrefs_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _ReaderService_ListTags_Handler,
		},
		{
			MethodName: "SetFeedTag",
			Handler:    _ReaderService_SetFeedTag_Handler,
		},
		{
			MethodName: "SetNote",
			Handler:    _ReaderService_SetNote_Handler,
		},
		{
			MethodName: "ListNotes",
			Handler:    _ReaderService_ListNotes_Handler,
		},
		{
			MethodName: "GetFeedSettings",
			Handler:    _ReaderService_GetFeedSettings_Handler,
		},
		{
			MethodName: "UpdateFeedSettings",
			Handler:    _ReaderService_UpdateFeedSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tidings/v1/reader.proto",
}
