// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tidings/v1/system.proto

// Package tidings.v1 is the single contract behind all three transports (§20.7):
// the gRPC tunnel, the plain-HTTPS pack channel, and the Google Reader-compatible
// REST sync API. Additive changes only within v1 — `buf breaking` in CI enforces
// that rather than discipline, because the sync API and SW-cached wasm both
// guarantee old clients in the wild (§22.10).

package tidingsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServingStatus int32

const (
	ServingStatus_SERVING_STATUS_UNSPECIFIED ServingStatus = 0
	// Reads and writes both available.
	ServingStatus_SERVING_STATUS_SERVING ServingStatus = 1
	// Reads available, writes refused — storage read-only, or a migration running.
	ServingStatus_SERVING_STATUS_DEGRADED ServingStatus = 2
	// Not ready to serve. Distinct from unreachable, which the client sees as a
	// transport error instead.
	ServingStatus_SERVING_STATUS_NOT_SERVING ServingStatus = 3
)

// Enum value maps for ServingStatus.
var (
	ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_DEGRADED",
		3: "SERVING_STATUS_NOT_SERVING",
	}
	ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING_STATUS_SERVING":     1,
		"SERVING_STATUS_DEGRADED":    2,
		"SERVING_STATUS_NOT_SERVING": 3,
	}
)

func (x ServingStatus) Enum() *ServingStatus {
	p := new(ServingStatus)
	*p = x
	return p
}

func (x ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tidings_v1_system_proto_enumTypes[0].Descriptor()
}

func (ServingStatus) Type() protoreflect.EnumType {
	return &file_tidings_v1_system_proto_enumTypes[0]
}

func (x ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServingStatus.Descriptor instead.
func (ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_tidings_v1_system_proto_rawDescGZIP(), []int{0}
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_tidings_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tidings_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_tidings_v1_system_proto_rawDescGZIP(), []int{0}
}

type GetVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Semantic version of the server build.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Git commit the binary was built from, or "unknown" for a local build.
	Commit string `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	// Highest applied migration. The client compares this across reconnects to
	// detect that it is talking to a different schema than it started on.
	SchemaVersion int64 `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_tidings_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tidings_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_tidings_v1_system_proto_rawDescGZIP(), []int{1}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GetVersionResponse) GetSchemaVersion() int64 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_tidings_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tidings_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_tidings_v1_system_proto_rawDescGZIP(), []int{2}
}

type CheckHealthResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status ServingStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=tidings.v1.ServingStatus" json:"status,omitempty"`
	// Human-readable and always safe to display (§20.7): internal detail goes to
	// the log with the request id, never to the client.
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResponse) Reset() {
	*x = CheckHealthResponse{}
	mi := &file_tidings_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResponse) ProtoMessage() {}

func (x *CheckHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tidings_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return file_tidings_v1_system_proto_rawDescGZIP(), []int{3}
}

func (x *CheckHealthResponse) GetStatus() ServingStatus {
	if x != nil {
		return x.Status
	}
	return ServingStatus_SERVING_STATUS_UNSPECIFIED
}

func (x *CheckHealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_tidings_v1_system_proto protoreflect.FileDescriptor

const file_tidings_v1_system_proto_rawDesc = "" +
	"\n" +
	"\x17tidings/v1/system.proto\x12\n" +
	"tidings.v1\"\x13\n" +
	"\x11GetVersionRequest\"m\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\x03R\rschemaVersion\"\x14\n" +
	"\x12CheckHealthRequest\"`\n" +
	"\x13CheckHealthResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.tidings.v1.ServingStatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail*\x88\x01\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1b\n" +
	"\x17SERVING_STATUS_DEGRADED\x10\x02\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x032\xac\x01\n" +
	"\rSystemService\x12K\n" +
	"\n" +
	"GetVersion\x12\x1d.tidings.v1.GetVersionRequest\x1a\x1e.tidings.v1.GetVersionResponse\x12N\n" +
	"\vCheckHealth\x12\x1e.tidings.v1.CheckHealthRequest\x1a\x1f.tidings.v1.CheckHealthResponseBDZBgithub.com/monstercameron/Tidings/internal/pb/tidings/v1;tidingsv1b\x06proto3"

var (
	file_tidings_v1_system_proto_rawDescOnce sync.Once
	file_tidings_v1_system_proto_rawDescData []byte
)

func file_tidings_v1_system_proto_rawDescGZIP() []byte {
	file_tidings_v1_system_proto_rawDescOnce.Do(func() {
		file_tidings_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tidings_v1_system_proto_rawDesc), len(file_tidings_v1_system_proto_rawDesc)))
	})
	return file_tidings_v1_system_proto_rawDescData
}

var file_tidings_v1_system_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tidings_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tidings_v1_system_proto_goTypes = []any{
	(ServingStatus)(0),          // 0: tidings.v1.ServingStatus
	(*GetVersionRequest)(nil),   // 1: tidings.v1.GetVersionRequest
	(*GetVersionResponse)(nil),  // 2: tidings.v1.GetVersionResponse
	(*CheckHealthRequest)(nil),  // 3: tidings.v1.CheckHealthRequest
	(*CheckHealthResponse)(nil), // 4: tidings.v1.CheckHealthResponse
}
var file_tidings_v1_system_proto_depIdxs = []int32{
	0, // 0: tidings.v1.CheckHealthResponse.status:type_name -> tidings.v1.ServingStatus
	1, // 1: tidings.v1.SystemService.GetVersion:input_type -> tidings.v1.GetVersionRequest
	3, // 2: tidings.v1.SystemService.CheckHealth:input_type -> tidings.v1.CheckHealthRequest
	2, // 3: tidings.v1.SystemService.GetVersion:output_type -> tidings.v1.GetVersionResponse
	4, // 4: tidings.v1.SystemService.CheckHealth:output_type -> tidings.v1.CheckHealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tidings_v1_system_proto_init() }
func file_tidings_v1_system_proto_init() {
	if File_tidings_v1_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tidings_v1_system_proto_rawDesc), len(file_tidings_v1_system_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tidings_v1_system_proto_goTypes,
		DependencyIndexes: file_tidings_v1_system_proto_depIdxs,
		EnumInfos:         file_tidings_v1_system_proto_enumTypes,
		MessageInfos:      file_tidings_v1_system_proto_msgTypes,
	}.Build()
	File_tidings_v1_system_proto = out.File
	file_tidings_v1_system_proto_goTypes = nil
	file_tidings_v1_system_proto_depIdxs = nil
}
