package grpcsrv

import (
	"context"
	"path/filepath"
	"testing"
	"time"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	pb "github.com/monstercameron/ArticleFlux/internal/pb/articleflux/v1"
	"github.com/monstercameron/ArticleFlux/internal/reader"
	"github.com/monstercameron/ArticleFlux/internal/store"
	"github.com/monstercameron/ArticleFlux/internal/topics"
)

// The interest profile at the wire edge (§18.2, §18.9).
//
// Tested here rather than only at the repository because two of the three things
// that can go wrong are transport-shaped: the multiplier-to-word conversion in
// both directions, and the "exactly one target" rule. The third — that a
// correction survives a rebuild — belongs to the store and is tested there.

func newInterestServer(t *testing.T) (*ReaderServer, *store.ReaderRepo, store.Scope, *int) {
	t.Helper()
	ctx := context.Background()

	db, err := store.Open(store.Options{Path: filepath.Join(t.TempDir(), "test.db")})
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })
	if _, err := db.Migrate(ctx); err != nil {
		t.Fatalf("migrate: %v", err)
	}

	repo := store.NewReaderRepo(db)
	now := time.Now().UTC().Format(time.RFC3339Nano)
	if err := repo.CreateTenantAndUser(ctx, store.NewTenant{
		TenantID: "t1", Name: "Test", UserID: "u1", Username: "cam",
		Hash: "x", Role: "superadmin", Now: now,
	}); err != nil {
		t.Fatalf("create tenant: %v", err)
	}
	sc := store.Scope{TenantID: "t1", UserID: "u1", Role: "superadmin"}

	if _, _, err := repo.Subscribe(ctx, sc, store.NewSubscription{
		NaturalKey: "feed:a", FeedURL: "https://a.example/feed", Title: "Alpha Journal",
	}); err != nil {
		t.Fatalf("subscribe: %v", err)
	}
	if err := repo.ReplaceTopics(ctx, sc, []topics.Topic{{
		TopTerms: []string{"schema", "migration", "index"}, Label: "Migrations",
		Members: []string{}, MemberScores: map[string]float64{}, Trend: topics.TrendSteady,
	}}); err != nil {
		t.Fatalf("ReplaceTopics: %v", err)
	}
	if err := repo.ReplaceEntityAffinity(ctx, sc, []store.Entity{
		{Name: "pro max", Label: "Pro Max", Kind: store.EntityPhrase, Weight: 37, Mentions: 2},
	}); err != nil {
		t.Fatalf("ReplaceEntityAffinity: %v", err)
	}

	// The rebuild hook, counted. A steer that never asks for a re-derivation is
	// a correction the reader cannot see the effect of, which is the failure
	// SetPrefs' own hook exists to prevent.
	rebuilds := 0
	svc := reader.New(repo, nil).WithRankPrefHook(func(store.Scope) { rebuilds++ })
	srv := NewReaderServer(svc, func(context.Context) (store.Scope, error) { return sc, nil })
	return srv, repo, sc, &rebuilds
}

func TestInterestProfileReportsWhatTheRankerBelieves(t *testing.T) {
	ctx := context.Background()
	srv, _, _, _ := newInterestServer(t)

	res, err := srv.GetInterestProfile(ctx, &pb.GetInterestProfileRequest{})
	if err != nil {
		t.Fatalf("GetInterestProfile: %v", err)
	}
	if len(res.GetTopics()) != 1 || res.GetTopics()[0].GetLabel() != "Migrations" {
		t.Fatalf("topics = %+v, want the one cluster", res.GetTopics())
	}
	// The default reads back as a POSITION, not as unspecified. Four unpressed
	// chips is a segmented control with no current answer, which reads as broken.
	if got := res.GetTopics()[0].GetLevel(); got != pb.SteerLevel_STEER_LEVEL_NORMAL {
		t.Errorf("a fresh topic's level = %v, want NORMAL", got)
	}
	if len(res.GetEntities()) != 1 {
		t.Fatalf("entities = %+v, want one", res.GetEntities())
	}
	// The pair that exposes a misread: a weight of 37 built out of two headlines.
	// Both numbers or neither — the weight alone reads as a subject somebody
	// follows.
	e := res.GetEntities()[0]
	if e.GetWeight() != 37 || e.GetMentions() != 2 {
		t.Errorf("entity evidence = weight %v from %d mentions, want 37 from 2",
			e.GetWeight(), e.GetMentions())
	}
	// No engagement has been recorded, so nothing is ranked and no pick cites a
	// topic. The screen has to be able to say that rather than showing an empty
	// list that looks like a fault.
	if !res.GetColdStart() {
		t.Error("cold_start is false on an instance with nothing ranked")
	}
}

func TestSteerRoundTripsThroughTheWire(t *testing.T) {
	ctx := context.Background()
	srv, _, _, rebuilds := newInterestServer(t)

	profile, err := srv.GetInterestProfile(ctx, &pb.GetInterestProfileRequest{})
	if err != nil {
		t.Fatal(err)
	}
	// The KEY. A topic id is regenerated by every derivation, which is why the
	// first version of this screen answered NotFound on the second press.
	topicKey := profile.GetTopics()[0].GetKey()
	if topicKey == "" {
		t.Fatal("the profile sent no steering key for a topic")
	}

	for _, level := range []pb.SteerLevel{
		pb.SteerLevel_STEER_LEVEL_MORE,
		pb.SteerLevel_STEER_LEVEL_LESS,
		pb.SteerLevel_STEER_LEVEL_NEVER,
		pb.SteerLevel_STEER_LEVEL_NORMAL,
	} {
		res, err := srv.SteerInterest(ctx, &pb.SteerInterestRequest{TopicKey: topicKey, Level: level})
		if err != nil {
			t.Fatalf("SteerInterest(%v): %v", level, err)
		}
		if !res.GetRebuilding() {
			t.Errorf("SteerInterest(%v) reported no rebuild, but a hook is wired", level)
		}
		back, err := srv.GetInterestProfile(ctx, &pb.GetInterestProfileRequest{})
		if err != nil {
			t.Fatal(err)
		}
		if got := back.GetTopics()[0].GetLevel(); got != level {
			t.Errorf("wrote %v, read back %v", level, got)
		}
	}
	if *rebuilds != 4 {
		t.Errorf("fired %d rebuilds for 4 steers", *rebuilds)
	}
}

// Coming back from Never lands on Normal rather than on whatever was set before
// it. A dial that remembers a position the screen stopped showing surprises the
// person undoing their own correction.
func TestNeverForgetsTheMultiplierItReplaced(t *testing.T) {
	ctx := context.Background()
	srv, repo, sc, _ := newInterestServer(t)

	profile, _ := srv.GetInterestProfile(ctx, &pb.GetInterestProfileRequest{})
	key := profile.GetTopics()[0].GetKey()

	for _, l := range []pb.SteerLevel{
		pb.SteerLevel_STEER_LEVEL_MORE, pb.SteerLevel_STEER_LEVEL_NEVER,
	} {
		if _, err := srv.SteerInterest(ctx, &pb.SteerInterestRequest{TopicKey: key, Level: l}); err != nil {
			t.Fatal(err)
		}
	}
	rows, err := repo.Topics(ctx, sc)
	if err != nil {
		t.Fatal(err)
	}
	if !rows[0].Suppressed || rows[0].Steer != store.SteerNormal {
		t.Errorf("after never: suppressed=%v steer=%v, want true/%v",
			rows[0].Suppressed, rows[0].Steer, store.SteerNormal)
	}
	// Suppressed wins over the multiplier when the level is reported back, or a
	// reader who set "more" and then "never" would be shown the louder of their
	// two answers.
	back, _ := srv.GetInterestProfile(ctx, &pb.GetInterestProfileRequest{})
	if got := back.GetTopics()[0].GetLevel(); got != pb.SteerLevel_STEER_LEVEL_NEVER {
		t.Errorf("level after never = %v", got)
	}
}

func TestSteerRefusesAmbiguousAndEmptyRequests(t *testing.T) {
	ctx := context.Background()
	srv, _, _, _ := newInterestServer(t)
	profile, _ := srv.GetInterestProfile(ctx, &pb.GetInterestProfileRequest{})
	key := profile.GetTopics()[0].GetKey()

	cases := []struct {
		name string
		req  *pb.SteerInterestRequest
		want codes.Code
	}{
		{"neither target", &pb.SteerInterestRequest{
			Level: pb.SteerLevel_STEER_LEVEL_LESS}, codes.InvalidArgument},
		{"both targets", &pb.SteerInterestRequest{
			TopicKey: key, EntityName: "pro max", Level: pb.SteerLevel_STEER_LEVEL_LESS,
		}, codes.InvalidArgument},
		// An unset level is a client that forgot the field, not a request to
		// reset a dial nobody touched.
		{"no level", &pb.SteerInterestRequest{TopicKey: key}, codes.InvalidArgument},
		{"unknown topic", &pb.SteerInterestRequest{
			TopicKey: "nope", Level: pb.SteerLevel_STEER_LEVEL_LESS}, codes.NotFound},
		{"unknown entity", &pb.SteerInterestRequest{
			EntityName: "nothing at all", Level: pb.SteerLevel_STEER_LEVEL_LESS}, codes.NotFound},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			_, err := srv.SteerInterest(ctx, c.req)
			if status.Code(err) != c.want {
				t.Errorf("code = %v (%v), want %v", status.Code(err), err, c.want)
			}
		})
	}
}

// The label is not the key. A client that echoed back "Pro Max" must still
// address the row the derivation stores under "pro max", or a correction made
// from the screen silently misses.
func TestSteerNormalisesAnEntityName(t *testing.T) {
	ctx := context.Background()
	srv, repo, sc, _ := newInterestServer(t)

	if _, err := srv.SteerInterest(ctx, &pb.SteerInterestRequest{
		EntityName: "  Pro Max  ", Level: pb.SteerLevel_STEER_LEVEL_NEVER,
	}); err != nil {
		t.Fatalf("SteerInterest: %v", err)
	}
	all, err := repo.AllEntities(ctx, sc, 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(all) != 1 || !all[0].Suppressed {
		t.Errorf("entities = %+v, want the one row suppressed", all)
	}
}

// The bug this screen shipped with, pinned: a topic's steering handle must
// survive the derivation that a steer itself schedules.
//
// Every derivation deletes and reinserts the topics table with fresh ids, so a
// screen holding an id could steer exactly once and got NotFound for every press
// after that — which is what a reader hit, seconds after their first correction
// had actually worked.
func TestSteeringATopicSurvivesARebuildOfTheTopicsTable(t *testing.T) {
	ctx := context.Background()
	srv, repo, sc, _ := newInterestServer(t)

	profile, err := srv.GetInterestProfile(ctx, &pb.GetInterestProfileRequest{})
	if err != nil {
		t.Fatal(err)
	}
	key := profile.GetTopics()[0].GetKey()
	oldID := profile.GetTopics()[0].GetId()

	// A derivation, exactly as the steer's own rebuild hook would cause.
	if err := repo.ReplaceTopics(ctx, sc, []topics.Topic{{
		TopTerms: []string{"schema", "migration", "index"}, Label: "Migrations",
		Members: []string{}, MemberScores: map[string]float64{}, Trend: topics.TrendSteady,
	}}); err != nil {
		t.Fatal(err)
	}
	rows, err := repo.Topics(ctx, sc)
	if err != nil {
		t.Fatal(err)
	}
	if rows[0].ID == oldID {
		t.Fatal("the id did not change; this test can no longer see the bug it pins")
	}

	// The screen is still holding the pre-rebuild response. Its press must land.
	if _, err := srv.SteerInterest(ctx, &pb.SteerInterestRequest{
		TopicKey: key, Level: pb.SteerLevel_STEER_LEVEL_NEVER,
	}); err != nil {
		t.Fatalf("a steer from a screen loaded before a rebuild: %v", err)
	}
	after, err := repo.Topics(ctx, sc)
	if err != nil {
		t.Fatal(err)
	}
	if !after[0].Suppressed {
		t.Error("the correction did not reach the cluster it named")
	}
}
