<#
    ArticleFlux task runner — TODO 1.4.

    This is `make.ps1` and not a `Makefile` for one reason: **there is no `make` on
    this box.** Verified 2026-07-26 (`command -v make` → missing), and per the
    Windows-native testing rule there is no WSL or Docker in the loop to borrow one
    from. Shipping a Makefile nobody here can run, plus a script everyone actually
    runs, is two build systems where one of them is a lie.

    The verb set is exactly the one TODO 1.4 specifies, so the names stay portable
    if a Makefile ever becomes worth having:

        gen build test wasm run lint migrate

    plus `tools` (build gwc.exe), `dev` (build + serve, the loop Cam watches) and
    `clean`.

    Usage:  ./scripts/make.ps1 <verb> [-Port 9000]

    It lives in scripts/ but every path it touches is the REPOSITORY root, which
    is $PSScriptRoot's parent — see $Root below. Nothing in here may use
    $PSScriptRoot directly: that is scripts/, and the difference is silent. A
    path built from the wrong one produces scripts/bin/articleflux.exe, which is a
    build that succeeds into a directory nobody serves from.
#>

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('gen', 'build', 'test', 'wasm', 'demo', 'run', 'dev', 'e2e', 'lint', 'migrate', 'tools', 'clean', 'help')]
    [string]$Target = 'help',

    # 9000 is the port Cam watches to follow along; changing the default moves the
    # thing he has open in a tab.
    [int]$Port = 9000,

    # What a `demo` build calls itself. The release workflow passes the tag it
    # was triggered by; a build from a laptop is honestly "dev".
    [string]$Version = 'dev'
)

$ErrorActionPreference = 'Stop'

# The repository root, one level up from scripts/. Every path below hangs off
# this and never off $PSScriptRoot, and the working directory is set to it so
# that `go build ./...`, `buf lint` and the guards resolve the way they do when
# a person runs them by hand.
$Root = Split-Path $PSScriptRoot -Parent
Set-Location $Root

$GWC       = Join-Path $Root 'bin\gwc.exe'
$GWCSource = Join-Path (Split-Path $Root -Parent) 'GoWebComponents'
$ClientApp = Join-Path $Root 'client\app'
$WebSrc    = Join-Path $Root 'web'
$OutDir    = Join-Path $Root 'bin\web'
$WasmOut   = Join-Path $OutDir 'app.wasm'
$DemoDir   = Join-Path $Root 'bin\demo'

function Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Fail($msg) { Write-Host "!!! $msg" -ForegroundColor Red; exit 1 }

# Native commands set $LASTEXITCODE; PowerShell will not stop on it by itself.
function Invoke-Checked {
    param([string]$What, [scriptblock]$Body)
    & $Body
    if ($LASTEXITCODE -ne 0) { Fail "$What failed (exit $LASTEXITCODE)" }
}

function Ensure-Tools {
    if (-not (Test-Path $GWC)) {
        Step 'gwc.exe missing — building it from the GWC checkout'
        Invoke-Tools
    }
}

function Invoke-Tools {
    Step "building gwc.exe from $GWCSource"
    if (-not (Test-Path $GWCSource)) {
        Fail "GWC checkout not found at $GWCSource. D0: v5.0.0 was never tagged, so the sibling checkout is not optional."
    }
    Push-Location $GWCSource
    try { Invoke-Checked 'go build (gwc)' { go build -o $GWC ./tools/gwc } }
    finally { Pop-Location }
    Write-Host "    $GWC" -ForegroundColor DarkGray
}

function Invoke-Gen {
    Step 'buf generate'
    Invoke-Checked 'buf lint'     { buf lint }
    Invoke-Checked 'buf generate' { buf generate }
}

function Invoke-Build {
    Step 'go build ./...'
    Invoke-Checked 'go build' { go build -o bin\articleflux.exe ./cmd/articleflux }
    Invoke-Checked 'go vet'   { go build ./... }
    # `go build ./...` does NOT compile the client (8b.32). The wasm packages sit
    # behind `//go:build js`, so a native build skips them entirely — during one
    # batch the wasm build was broken for a stretch while the native build and
    # every Go test stayed green. Catching it here is catching it before CI.
    Invoke-Checked 'go build (wasm client)' {
        $env:GOOS = 'js'; $env:GOARCH = 'wasm'
        try { go build ./client/... }
        finally { Remove-Item Env:GOOS, Env:GOARCH -ErrorAction SilentlyContinue }
    }
}

function Invoke-Test {
    Step 'go test ./...'
    Invoke-Checked 'go test' { go test ./... }
}

function Invoke-Wasm {
    Ensure-Tools
    if (-not (Test-Path $ClientApp)) {
        Write-Host '    client/app has no main yet (Tier 8) — skipping wasm' -ForegroundColor DarkGray
        return
    }
    Step 'building the web root -> bin/web'
    New-Item -ItemType Directory -Force $OutDir | Out-Null

    # web/ is source; bin/web is the assembled output. Copying rather than
    # serving from web/ keeps every generated byte inside the one ignored
    # directory, so "is this file source?" is answerable from its path.
    Copy-Item (Join-Path $WebSrc 'index.html') (Join-Path $OutDir 'index.html') -Force
    # index.html registers sw.js by relative path, so a build that does not ship
    # it 404s on every load and the offline shell silently never exists (8.4).
    Copy-Item (Join-Path $WebSrc 'sw.js') (Join-Path $OutDir 'sw.js') -Force

    # `go build` directly rather than `gwc build`: the launcher wraps the same
    # toolchain, and this keeps the exact flags visible — -trimpath and -s -w are
    # what the G5 baseline in wasm-baseline.txt was measured with, so building
    # differently would make the CI ratchet compare two different things.
    $env:GOOS = 'js'; $env:GOARCH = 'wasm'
    try {
        Invoke-Checked 'go build (wasm)' {
            go build -trimpath -ldflags="-s -w" -o $WasmOut ./client/app
        }
    } finally { Remove-Item Env:GOOS, Env:GOARCH -ErrorAction SilentlyContinue }

    # wasm_exec.js comes from the toolchain, so it must match the compiler that
    # produced the module. A stale copy from an older Go fails at instantiate
    # with an import mismatch that reads like a corrupt binary.
    $exec = Join-Path (go env GOROOT) 'lib\wasm\wasm_exec.js'
    if (-not (Test-Path $exec)) { $exec = Join-Path (go env GOROOT) 'misc\wasm\wasm_exec.js' }
    Copy-Item $exec (Join-Path $OutDir 'wasm_exec.js') -Force

    # Precompressed siblings. G5 measured 23.8 MB raw against 5.2 MB gzipped;
    # the server prefers the .gz when the client accepts it.
    #
    # Written to a temp file and MOVED into place, never compressed in situ. The
    # server prefers app.wasm.gz over app.wasm, so a .gz that is stale — or
    # truncated, which is what File::Create leaves behind when the compressor
    # throws — means the browser silently runs the previous build. That failure
    # looks exactly like "my change did nothing", and it costs an hour every time.
    #
    # CompressionLevel::Optimal, not SmallestSize: SmallestSize is .NET 5+, and on
    # Windows PowerShell 5.1 it resolves to $null, which surfaces as an
    # unrelated-looking "cannot find an overload for GZipStream".
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    foreach ($f in @($WasmOut, (Join-Path $OutDir 'wasm_exec.js'))) {
        $tmp = "$f.gz.tmp"
        $in  = [System.IO.File]::OpenRead($f)
        $out = [System.IO.File]::Create($tmp)
        $gz  = New-Object System.IO.Compression.GZipStream($out, [System.IO.Compression.CompressionLevel]::Optimal)
        try { $in.CopyTo($gz) } finally { $gz.Dispose(); $out.Dispose(); $in.Dispose() }
        Move-Item $tmp "$f.gz" -Force
    }

    # G5 / R4: the wasm size decides whether A5 (offline packs in the browser)
    # stays affordable. Print it every build so the number is never a surprise.
    $raw = [math]::Round((Get-Item $WasmOut).Length / 1MB, 1)
    $gzs = [math]::Round((Get-Item "$WasmOut.gz").Length / 1MB, 1)
    Write-Host "    app.wasm = $raw MB raw / $gzs MB gzipped  (G5 ratchet - plan.md R4)" -ForegroundColor DarkGray
}

# The GitHub Pages demo (client/demo + client/demodata), built exactly the way
# .github/workflows/pages.yml builds it.
#
# "Exactly" is the point of having this verb at all: the deployed demo is the
# only build of this application that strangers see, and a local one that
# differed from it — by shipping the uncompressed module, say — would be a
# rehearsal of a different performance. So the output directory here holds the
# same three files the workflow uploads, and nothing else.
#
# The version is a parameter for the same reason it is a linker flag in CI:
# a build that identifies itself as something it is not is worse than one that
# says "dev".
function Invoke-Demo {
    param([string]$DemoVersion = 'dev')

    Step "building the demo -> bin/demo  ($DemoVersion)"
    New-Item -ItemType Directory -Force $DemoDir | Out-Null
    Copy-Item (Join-Path $WebSrc 'index.html') (Join-Path $DemoDir 'index.html') -Force
    Copy-Item (Join-Path $WebSrc 'sw.js') (Join-Path $DemoDir 'sw.js') -Force

    $raw = Join-Path $DemoDir 'app.wasm'
    $env:GOOS = 'js'; $env:GOARCH = 'wasm'
    try {
        Invoke-Checked 'go build (demo wasm)' {
            go build -trimpath -ldflags="-s -w -X main.version=$DemoVersion" -o $raw ./client/demo
        }
    } finally { Remove-Item Env:GOOS, Env:GOARCH -ErrorAction SilentlyContinue }

    # wasm_exec.js must come from the toolchain that produced the module.
    $exec = Join-Path (go env GOROOT) 'lib\wasm\wasm_exec.js'
    if (-not (Test-Path $exec)) { $exec = Join-Path (go env GOROOT) 'misc\wasm\wasm_exec.js' }
    Copy-Item $exec (Join-Path $DemoDir 'wasm_exec.js') -Force

    # Compressed, and then the raw module is DELETED — which is the one place
    # this differs from `wasm`, and it is deliberate. A static host cannot
    # negotiate an encoding, so the boot shim fetches app.wasm.gz and
    # decompresses it itself (see web/index.html); leaving app.wasm next to it
    # would mean the shim never took that path locally and the first time anyone
    # exercised it was on the public demo.
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $tmp = "$raw.gz.tmp"
    $in  = [System.IO.File]::OpenRead($raw)
    $out = [System.IO.File]::Create($tmp)
    $gz  = New-Object System.IO.Compression.GZipStream($out, [System.IO.Compression.CompressionLevel]::Optimal)
    try { $in.CopyTo($gz) } finally { $gz.Dispose(); $out.Dispose(); $in.Dispose() }
    Move-Item $tmp "$raw.gz" -Force
    $rawMB = [math]::Round((Get-Item $raw).Length / 1MB, 1)
    $gzMB  = [math]::Round((Get-Item "$raw.gz").Length / 1MB, 1)
    Remove-Item $raw -Force

    Write-Host "    demo.wasm = $rawMB MB raw / $gzMB MB shipped (gzipped)" -ForegroundColor DarkGray
    Write-Host "    serve bin/demo with any static file server to look at it" -ForegroundColor DarkGray
}

function Invoke-Lint {
    Step 'go vet'
    Invoke-Checked 'go vet' { go vet ./... }
    Step 'buf lint'
    Invoke-Checked 'buf lint' { buf lint }
    Step 'structural guards (A26 + tenancy)'
    Invoke-Checked 'guards' { go run ./internal/tools/guards }
}

function Invoke-Migrate {
    Ensure-Build
    Step 'articleflux migrate'
    Invoke-Checked 'migrate' { & (Join-Path $Root 'bin\articleflux.exe') migrate }
}

function Ensure-Build { if (-not (Test-Path 'bin\articleflux.exe')) { Invoke-Build } }

function Invoke-Run {
    Invoke-Build
    Step "serving on http://127.0.0.1:$Port"
    & (Join-Path $Root 'bin\articleflux.exe') serve -addr "127.0.0.1:$Port"
}

switch ($Target) {
    'tools'   { Invoke-Tools }
    'gen'     { Invoke-Gen }
    'build'   { Invoke-Build }
    'test'    { Invoke-Test }
    'wasm'    { Invoke-Wasm }
    'demo'    { Invoke-Demo -DemoVersion $Version }
    'lint'    { Invoke-Lint }
    'migrate' { Invoke-Migrate }
    'run'     { Invoke-Run }
    'dev'     { Invoke-Wasm; Invoke-Run }
    'e2e'     {
        Invoke-Build
        Invoke-Wasm
        Step 'playwright'
        Push-Location (Join-Path $Root 'e2e')
        try {
            if (-not (Test-Path 'node_modules')) { Invoke-Checked 'npm install' { npm install } }
            Invoke-Checked 'playwright' { npx playwright test }
        } finally { Pop-Location }
    }
    'clean'   {
        Step 'clean'
        # One directory, because everything generated lives in it.
        if (Test-Path 'bin') { Remove-Item -Recurse -Force 'bin' }
    }
    default {
        Write-Host @'
ArticleFlux task runner (TODO 1.4)

  ./scripts/make.ps1 tools      build gwc.exe from ../GoWebComponents  (D0: no published tag)
  ./scripts/make.ps1 gen        buf lint + buf generate -> internal/pb
  ./scripts/make.ps1 build      go build -> bin/articleflux.exe
  ./scripts/make.ps1 test       go test ./...
  ./scripts/make.ps1 wasm       build the client into bin/web, prints the G5 size
  ./scripts/make.ps1 demo       build the GitHub Pages demo into bin/demo (-Version v1.0.0)
  ./scripts/make.ps1 lint       go vet + buf lint + the A26/tenancy structural guards
  ./scripts/make.ps1 migrate    apply migrations
  ./scripts/make.ps1 run        build, then serve on :9000
  ./scripts/make.ps1 dev        wasm + run          <- the loop to leave open
  ./scripts/make.ps1 e2e        build, then run the Playwright suite (desktop + phone)
  ./scripts/make.ps1 clean      remove bin/ (which is all generated output)

Run it from anywhere: it sets the working directory to the repository root
itself, so ./scripts/make.ps1 and scripts/make.ps1 behave identically.

Override the port with -Port; 9000 is the default because that is the tab Cam
has open.
'@
    }
}
